/* Ergänzende Übungen für den Katalog (Haltungen, die bisher weder als Übung noch als Strichmännchen vorhanden waren).
   Die Beschreibungen sind eigene, knappe Zusammenfassungen. Sanskrit-Namen sind Standardbezeichnungen (im Skript nicht belegt).
   man = nur manuell wählbar (wird vom Generator nicht automatisch vorgeschlagen).
   FIG_KAT = Haltung/Bewegungsrichtung je Übung (wird in kategorien.js als Feinkorrektur übernommen). */
const FIG_KAT = {};
function N(o) {
  const kat = o.kat; delete o.kat;
  const e = Object.assign({
    s: 0, m: 1.5, e: '', h: '', sv: false, man: false, script: false, st: ['hatha'], d: '', w: '', sa: '', src: 'Eigene Ergänzung'
  }, o);
  e.t = typeof o.t === 'string' ? o.t.split(' ') : (o.t || []);
  e.x = typeof o.x === 'string' ? (o.x ? o.x.split(' ') : []) : (o.x || []);
  e.st = typeof o.st === 'string' ? o.st.split(' ') : e.st;
  e.o = EX.length;
  EX.push(e);
  if (kat) FIG_KAT[e.id] = kat;
}

// ---------- Stand ----------
N({ id: 'arme_ruecken', n: 'Arme auf dem Rücken (Gebetshände hinten)', sa: 'Paschima Namaskarasana', c: 'stand', lv: 2, m: 1, pose: 'y130a', t: 'schulter herz', x: 'schulter handgelenk', d: 'Im Stand die Handflächen hinter dem Rücken zusammenführen, Brustbein heben; auch als Vorbeuge mit den Armen auf dem Rücken möglich – öffnet Schultern und Brust.', kat: { pos: ['stehen'] } });
N({ id: 'stern', n: 'Fünfzackiger Stern', c: 'stand', lv: 1, m: 1, pose: 'y154', t: 'energie wurzel', d: 'Weiter Stand, Arme diagonal nach oben gestreckt: der Körper bildet einen Stern; weitet Brust und Flanken.', kat: { pos: ['stehen'] } });
N({ id: 'pada_hastasana', n: 'Hände unter die Füße', sa: 'Pada Hastasana', c: 'stand', lv: 1, m: 1, pose: 'y105c', t: 'ruecken loslassen', x: 'ruecken blutdruck schwindel', e: 'vorbeuge', d: 'Vorbeuge im Stand, die Hände unter die Fußsohlen schieben; Knie dürfen gebeugt bleiben – dehnt Rückseite der Beine und Rücken.', kat: { pos: ['stehen'], dir: ['vor'] } });
N({ id: 'leonardo', n: 'Leonardo (weiter Stand, Arme seitlich)', c: 'stand', lv: 1, m: 1, pose: 'y171', t: 'wurzel energie', d: 'Beine weit gegrätscht, Arme seitlich auf Schulterhöhe – stabiler, offener Stand.', kat: { pos: ['stehen'] } });
N({ id: 'uddiyana', n: 'Aufwärts-Bauchverschluss', sa: 'Uddiyana Bandha', c: 'stand', lv: 2, m: 1, pose: 'y153', t: 'atem energie', x: 'blutdruck schwindel', d: 'Nach vollständiger Ausatmung den Bauch nach innen und oben ziehen, Hände auf den Oberschenkeln.', w: 'Nur mit leerem Magen und nach der Ausatmung üben; nicht bei Bluthochdruck, Herzproblemen oder in der Schwangerschaft.', kat: { pos: ['stehen'] } });
N({ id: 'ellenbogen_knie', n: 'Ellenbogen–Knie', c: 'balance', lv: 2, m: 1, pose: 'y175', t: 'balance kraft', x: 'schwindel', d: 'Im Stand Knie und Ellenbogen vor dem Körper zusammenführen: aktiviert den Rumpf und schult das Gleichgewicht.', kat: { pos: ['stehen', 'balance'] } });
N({ id: 'natarajasana', n: 'Tänzer', sa: 'Natarajasana', c: 'balance', lv: 3, m: 1.5, pose: 'y138', t: 'balance herz kraft', x: 'schwindel knie schulter blutdruck ruecken', e: 'baum', d: 'Einbeiniger Stand, das andere Bein nach hinten greifen und gegen die Hand drücken, Brustbein öffnet sich.', kat: { pos: ['stehen', 'balance'], dir: ['rueck'] } });
N({ id: 'standspagat', n: 'Standspagat', sa: 'Urdhva Prasarita Eka Padasana', c: 'balance', lv: 3, m: 1.5, pose: 'y193', t: 'balance huefte', x: 'schwindel ruecken huefte blutdruck knie', d: 'Aus der Vorbeuge ein Bein senkrecht nach oben führen, Hände am Boden oder am Standbein.', kat: { pos: ['stehen', 'balance'], dir: ['vor'] } });
N({ id: 'sprung_vorbereiten', n: 'Sprung vorbereiten', c: 'kraft', lv: 2, m: 1, pose: 'y119', t: 'kraft energie', x: 'knie handgelenk ruecken', man: true, d: 'Tiefe Vorbereitungshaltung mit Händen am Boden, aus der ein Sprung oder Übergang gestartet wird.', kat: { pos: ['stuetz'] } });
N({ id: 'drache', n: 'Verdrehter Drache (Budokon)', c: 'stand', lv: 3, m: 1.5, pose: 'y143', t: 'kraft huefte', x: 'knie huefte ruecken schwindel', man: true, d: 'Dynamischer Übergang aus der Budokon-Praxis mit Drehung und weit geöffneten Armen.', kat: { pos: ['stehen'], dir: ['dreh'] } });
N({ id: 'doppelblock', n: 'Doppelblock (Budokon)', c: 'stand', lv: 2, m: 1, pose: 'y191', t: 'kraft', x: 'knie huefte', man: true, d: 'Tiefer Ausfallschritt mit abwehrenden Armen aus der Budokon-Praxis.', kat: { pos: ['stehen'] } });
N({ id: 'bogenschuetze', n: 'Gedrehter Bogenschütze (Budokon)', sa: 'Parivrtta Akarna Dhanurasana', c: 'stand', lv: 3, m: 1.5, pose: 'y192', t: 'kraft huefte', x: 'knie huefte ruecken schulter', man: true, d: 'Tiefer Ausfallschritt mit Drehung des Oberkörpers, die Arme spannen einen imaginären Bogen.', kat: { pos: ['stehen'], dir: ['dreh'] } });
N({ id: 'kriegerbasis', n: 'Kriegerbasis (Budokon)', c: 'stand', lv: 2, m: 1, pose: 'y251', t: 'kraft wurzel', x: 'knie huefte', man: true, d: 'Tiefe, stabile Ausgangsstellung der Budokon-Folgen.', kat: { pos: ['stehen'] } });

// ---------- Sitzen ----------
N({ id: 'sukhasana', n: 'Leichter Sitz', sa: 'Sukhasana', c: 'boden', lv: 1, m: 1, pose: 'y226a', t: 'ruhe wurzel', x: 'knie huefte', d: 'Bequemer Schneidersitz mit aufrechter Wirbelsäule; Grundhaltung für Atem und Meditation, bei Bedarf auf einem Kissen.', kat: { pos: ['sitzen'] } });
N({ id: 'anjali_mudra', n: 'Añjali Mudra (Gebetshaltung)', sa: 'Anjali Mudra', c: 'boden', lv: 1, m: 1, pose: 'y226b', t: 'herz ruhe', d: 'Im Sitz die Handflächen vor dem Herzen zusammenführen; sammelt und beruhigt.', kat: { pos: ['sitzen'] } });
N({ id: 'dhyana', n: 'Meditationssitz', sa: 'Dhyana', c: 'boden', lv: 1, m: 2, pose: 'y228g', t: 'ruhe', x: 'knie huefte', d: 'Aufrechter Sitz in der Meditationshaltung, Hände ruhen auf den Knien.', kat: { pos: ['sitzen'] } });
N({ id: 'padmasana', n: 'Lotussitz', sa: 'Padmasana', c: 'boden', lv: 3, m: 1.5, pose: 'y228a', t: 'ruhe wurzel huefte', x: 'knie huefte fuss', e: 'sukhasana', d: 'Beide Füße auf den gegenüberliegenden Oberschenkeln, Wirbelsäule aufrecht.', w: 'Nur bei beweglichen Hüften; nie das Knie erzwingen.', kat: { pos: ['sitzen'] } });
N({ id: 'dandasana', n: 'Stock', sa: 'Dandasana', c: 'boden', lv: 1, m: 1, pose: 'y219a', t: 'ruecken wurzel', d: 'Aufrechter Sitz mit gestreckten Beinen, Füße gebeugt, Hände neben dem Becken; richtet die Wirbelsäule auf.', kat: { pos: ['sitzen'] } });
N({ id: 'mahamudra', n: 'Großes Siegel', sa: 'Mahamudra', c: 'boden', lv: 2, m: 1.5, pose: 'y223', t: 'ruecken loslassen', x: 'ruecken blutdruck', d: 'Ein Bein gestreckt, das andere angewinkelt, Vorbeuge zum gestreckten Bein und Fuß greifen.', kat: { pos: ['sitzen'], dir: ['vor'] } });
N({ id: 'marichyasana_1', n: 'Marichi I', sa: 'Marichyasana I', c: 'boden', lv: 2, m: 1.5, pose: 'y242a', t: 'ruecken huefte loslassen', x: 'ruecken huefte', d: 'Ein Bein gestreckt, das andere aufgestellt; Vorbeuge über das gestreckte Bein.', kat: { pos: ['sitzen'], dir: ['vor'] } });
N({ id: 'marichyasana_3', n: 'Marichi III (Drehsitz)', sa: 'Marichyasana III', c: 'boden', lv: 2, m: 1.5, pose: 'y242b', t: 'ruecken huefte loslassen', x: 'ruecken osteoporose', d: 'Ein Bein gestreckt, das andere aufgestellt; Oberkörper zum aufgestellten Bein hindrehen.', kat: { pos: ['sitzen'], dir: ['dreh'] } });
N({ id: 'parivrtta_janu', n: 'Gedrehter Kopf-zum-Knie', sa: 'Parivrtta Janu Sirsasana', c: 'boden', lv: 2, m: 1.5, pose: 'y212b', t: 'ruecken seit loslassen', x: 'ruecken knie osteoporose', e: 'janu', d: 'Sitzende Seitbeuge über das gestreckte Bein mit leichter Drehung in der Brustwirbelsäule.', kat: { pos: ['sitzen'], dir: ['seit', 'dreh'] } });
N({ id: 'kompass', n: 'Kompass', sa: 'Parivrtta Surya Yantrasana', c: 'boden', lv: 3, m: 1.5, pose: 'y229', t: 'huefte schulter', x: 'huefte ruecken schulter knie', d: 'Ein Bein über die Schulter legen und den Oberkörper in die Gegenrichtung strecken.', kat: { pos: ['sitzen'], dir: ['seit'] } });
N({ id: 'supta_kurmasana', n: 'Liegende Schildkröte', sa: 'Supta Kurmasana', c: 'boden', lv: 3, m: 1.5, pose: 'y202b', t: 'huefte ruecken loslassen', x: 'ruecken huefte knie nacken', d: 'Tiefe Vorbeuge, die Beine liegen über den Schultern, die Hände verschränken sich hinter dem Rücken.', kat: { pos: ['sitzen'], dir: ['vor'] } });
N({ id: 'drop_stance', n: 'Drop Stance (Budokon)', c: 'boden', lv: 2, m: 1, pose: 'y250', t: 'kraft huefte', x: 'knie huefte', man: true, d: 'Tiefes Absenken ins Gleichgewicht zwischen Sitz und Ausfallschritt aus der Budokon-Praxis.', kat: { pos: ['sitzen'] } });
N({ id: 'einbeiniger_durchsitz', n: 'Einbeiniger Durchsitz (Budokon)', c: 'boden', lv: 2, m: 1, pose: 'y212', t: 'huefte loslassen', x: 'huefte knie', man: true, d: 'Aus dem Sitz ein Bein unter dem anderen durchführen und die Hüfte öffnen.', kat: { pos: ['sitzen'] } });

// ---------- Knien / Vierfüßler ----------
N({ id: 'vierfuessler', n: 'Vierfüßlerstand', sa: 'Bharmanasana', c: 'boden', lv: 1, m: 1, pose: 'y314', t: 'ruecken wurzel', x: 'handgelenk knie', d: 'Hände unter den Schultern, Knie unter den Hüften; neutrale Wirbelsäule als Ausgangsposition vieler Übungen.', kat: { pos: ['knien'] } });
N({ id: 'akarna_dhanu', n: 'Bogen und Pfeil', sa: 'Akarna Dhanurasana', c: 'boden', lv: 2, m: 1.5, pose: 'y329', t: 'huefte schulter', x: 'huefte knie', d: 'Im Sitz ein Fuß wie eine Bogensehne zum Ohr führen, das andere Bein bleibt gestreckt.', kat: { pos: ['sitzen'] } });
N({ id: 'agni_sara', n: 'Feuerreinigung (Atemübung)', sa: 'Agni Sara', c: 'boden', lv: 1, m: 1.5, pose: 'y327', t: 'atem energie', x: 'blutdruck', d: 'Nach der Ausatmung den Bauch rhythmisch nach innen ziehen und loslassen; belebt den Bauchraum.', w: 'Nur mit leerem Magen; nicht in der Schwangerschaft oder bei Bluthochdruck.', kat: { pos: ['knien'] } });
N({ id: 'parighasana', n: 'Querbalken', sa: 'Parighasana', c: 'boden', lv: 1, m: 1.5, pose: 'y309a', t: 'seit huefte', x: 'knie', d: 'Aus dem Kniestand ein Bein seitlich strecken und mit dem Oberkörper zur Seite beugen – dehnt Flanke und Oberschenkel.', kat: { pos: ['knien'], dir: ['seit'] } });
N({ id: 'sasangasana', n: 'Hase', sa: 'Sasangasana', c: 'boden', lv: 2, m: 1.5, pose: 'y332', t: 'ruecken nacken loslassen', x: 'nacken knie blutdruck osteoporose', d: 'Aus der Kindhaltung die Hüfte anheben und den Scheitel Richtung Boden führen; dehnt den ganzen Rücken.', w: 'Gewicht nicht auf den Kopf legen; bei Nackenproblemen weglassen.', kat: { pos: ['knien'], dir: ['vor'] } });

// ---------- Rückenlage ----------
N({ id: 'karnapidasana', n: 'Ohrdruck-Haltung', sa: 'Karnapidasana', c: 'boden', lv: 3, m: 1.5, pose: 'y407', t: 'ruecken loslassen ruhe', x: 'nacken ruecken blutdruck osteoporose', d: 'Aus dem Pflug die Knie neben die Ohren sinken lassen; tiefe, beruhigende Dehnung des Rückens.', kat: { pos: ['umkehr'], dir: ['vor'] } });
N({ id: 'supta_konasana', n: 'Liegende Grätsche', sa: 'Supta Konasana', c: 'boden', lv: 3, m: 1.5, pose: 'y433', t: 'huefte ruecken', x: 'ruecken nacken blutdruck', d: 'Aus der Rückenlage die gestreckten Beine über den Kopf führen und seitlich spreizen.', kat: { pos: ['liegen'] } });
N({ id: 'anantasana', n: 'Ruhender Vishnu', sa: 'Anantasana', c: 'boden', lv: 2, m: 1.5, pose: 'y402', t: 'huefte balance', x: 'schulter huefte', d: 'Seitlage, der obere Fuß wird mit der Hand gegriffen und das Bein senkrecht gestreckt.', kat: { pos: ['liegen'], dir: ['seit'] } });
N({ id: 'tisch_vier', n: 'Umgekehrter Tisch', sa: 'Chatus Pada Pitham', c: 'kraft', lv: 2, m: 1, pose: 'y424', t: 'kraft herz schulter', x: 'handgelenk schulter nacken', d: 'Auf dem Rücken die Hüfte anheben, Hände und Füße am Boden: Rumpf und Oberschenkel bilden eine waagerechte Tischplatte.', kat: { pos: ['stuetz'], dir: ['rueck'] } });
N({ id: 'purvottanasana', n: 'Umgekehrte Planke', sa: 'Purvottanasana', c: 'kraft', lv: 2, m: 1, pose: 'y607a', t: 'kraft herz schulter', x: 'handgelenk schulter nacken', e: 'tisch_vier', d: 'Im Sitz die Hüfte anheben, Körper bildet eine schräge Linie, Brust öffnet sich.', kat: { pos: ['stuetz'], dir: ['rueck'] } });
N({ id: 'kancho_drehung', n: 'Kanchos Drehung (Budokon)', c: 'boden', lv: 2, m: 1, pose: 'y425c', t: 'ruecken loslassen', x: 'osteoporose', man: true, d: 'Liegende Drehung aus der Budokon-Praxis.', kat: { pos: ['liegen'], dir: ['dreh'] } });

// ---------- Bauchlage ----------
N({ id: 'ashtanga_namaskara', n: 'Gruß mit acht Gliedern', sa: 'Ashtanga Namaskara', c: 'kraft', lv: 2, m: 1, pose: 'y529', t: 'kraft', x: 'handgelenk schulter', d: 'Knie, Brust und Kinn sowie beide Hände und Füße berühren den Boden, die Hüfte bleibt oben; Übergang im Sonnengruß.', kat: { pos: ['stuetz'] } });
N({ id: 'sarpasana', n: 'Klapperschlange', sa: 'Sarpasana', c: 'boden', lv: 3, m: 1.5, pose: 'y528', t: 'ruecken kraft', x: 'ruecken nacken schulter', d: 'Bauchlage, Hände hinter dem Rücken verschränkt, Brust und Beine heben sich vom Boden.', kat: { pos: ['liegen'], dir: ['rueck'] } });
N({ id: 'bauchlage', n: 'Bauchlage', c: 'boden', lv: 1, m: 1, pose: 'y515a', t: 'ruhe loslassen', d: 'Entspannte Bauchlage, Kopf zur Seite oder auf den Händen; Ausgleich nach Rückbeugen.', kat: { pos: ['liegen'] } });
N({ id: 'vogel', n: 'Vogel', c: 'boden', lv: 1, m: 1, pose: 'y524', t: 'ruecken kraft', x: 'ruecken', d: 'In Bauchlage gegenüberliegenden Arm und Bein anheben; kräftigt den Rücken.', kat: { pos: ['liegen'], dir: ['rueck'] } });

// ---------- Stütz- und Armbalancen ----------
N({ id: 'bakasana', n: 'Kranich', sa: 'Bakasana', c: 'balance', lv: 3, m: 1, pose: 'y605e', t: 'balance kraft', x: 'handgelenk schulter schwindel', d: 'Aus der Hocke die Knie hoch an die Oberarme führen und das Gewicht auf die Hände verlagern.', kat: { pos: ['stuetz', 'balance'] } });
N({ id: 'delfin', n: 'Delfin', sa: 'Ardha Pincha Mayurasana', c: 'kraft', lv: 2, m: 1, pose: 'y619f', t: 'kraft schulter', x: 'schulter nacken blutdruck', d: 'Wie der Herabschauende Hund, aber auf den Unterarmen; kräftigt Schultern und dehnt die Rückseite der Beine.', kat: { pos: ['umkehr'], dir: ['vor'] } });
N({ id: 'tittibhasana', n: 'Glühwürmchen', sa: 'Tittibhasana', c: 'balance', lv: 3, m: 1, pose: 'y637', t: 'balance kraft huefte', x: 'handgelenk schulter huefte schwindel', d: 'Die Beine liegen über den Oberarmen und werden nach vorn gestreckt, das Becken schwebt über dem Boden.', kat: { pos: ['stuetz', 'balance'] } });
N({ id: 'mayurasana', n: 'Pfau', sa: 'Mayurasana', c: 'balance', lv: 3, m: 1, pose: 'y620', t: 'balance kraft bauch', x: 'handgelenk blutdruck schulter', d: 'Ellbogen im Bauch gestützt, der Körper wird waagerecht vom Boden gehoben.', kat: { pos: ['stuetz', 'balance'] } });
N({ id: 'tolasana', n: 'Waage', sa: 'Tolasana', c: 'balance', lv: 2, m: 1, pose: 'y610a', t: 'kraft balance', x: 'handgelenk schulter', d: 'Im Sitz die Hände neben die Hüften stützen und den Körper vom Boden anheben.', kat: { pos: ['stuetz', 'balance'] } });
N({ id: 'parsva_kakasana', n: 'Seitliche Krähe', sa: 'Parsva Kakasana', c: 'balance', lv: 3, m: 1, pose: 'y605b', t: 'balance kraft dreh', x: 'handgelenk schulter schwindel', d: 'Aus einer Drehung beide Knie seitlich auf einen Oberarm legen und auf den Händen balancieren.', kat: { pos: ['stuetz', 'balance'], dir: ['dreh'] } });
N({ id: 'schimpanse', n: 'Schimpanse (Budokon)', c: 'kraft', lv: 2, m: 1, pose: 'y646b', t: 'kraft', x: 'handgelenk knie', man: true, d: 'Tiefe Hocke mit Stütz auf den Händen aus der Budokon-Praxis.', kat: { pos: ['stuetz'] } });
N({ id: 'gorilla', n: 'Gorilla (Budokon)', c: 'kraft', lv: 2, m: 1, pose: 'y646c', t: 'kraft huefte', x: 'knie huefte', man: true, d: 'Weite, tiefe Hocke mit hängenden Armen aus der Budokon-Praxis.', kat: { pos: ['stehen'] } });
N({ id: 'affe_budokon', n: 'Affe (Budokon)', c: 'kraft', lv: 2, m: 1, pose: 'y646a', t: 'kraft', x: 'handgelenk knie', man: true, d: 'Gehen auf Händen und Füßen mit hoher Hüfte aus der Budokon-Praxis.', kat: { pos: ['stuetz'] } });
N({ id: 'sprung_budokon', n: 'Sprung (Budokon)', c: 'kraft', lv: 3, m: 1, pose: 'y606', t: 'kraft energie', x: 'knie handgelenk schulter schwindel', man: true, d: 'Sprung über die Hände in den Stütz aus der Budokon-Praxis.', kat: { pos: ['stuetz'] } });
N({ id: 'fallender_krieger', n: 'Fallender Krieger (Budokon)', c: 'kraft', lv: 3, m: 1, pose: 'y615j', t: 'kraft balance', x: 'knie handgelenk schulter', man: true, d: 'Aus dem Stütz ein Bein nach hinten anheben und seitlich absenken (Budokon).', kat: { pos: ['stuetz'] } });
N({ id: 'kriegerbruecke', n: 'Kriegerbrücke (Budokon)', c: 'kraft', lv: 3, m: 1, pose: 'y607c', t: 'kraft herz', x: 'handgelenk schulter nacken', man: true, d: 'Umgekehrter Stütz mit angehobener Hüfte aus der Budokon-Praxis.', kat: { pos: ['stuetz'], dir: ['rueck'] } });

// ---- weitere Haltungen ----
N({ id: 'siddhasana', n: 'Vollendeter Sitz', sa: 'Siddhasana', c: 'boden', lv: 1, m: 1.5, pose: 'z1', t: 'ruhe wurzel', x: 'knie huefte', d: 'Aufrechter Meditationssitz, eine Ferse am Damm, die andere davor; Hände ruhen auf den Knien.', kat: {'pos':['sitzen']} });
N({ id: 'attitude', n: 'Attitude', c: 'balance', lv: 2, m: 1, pose: 'z3', t: 'balance huefte', x: 'schwindel knie', man: true, d: 'Einbeiniger Stand, das andere Bein angewinkelt nach hinten angehoben, ein Arm streckt sich nach oben (Tanzhaltung).', kat: {'pos':['stehen','balance']} });
N({ id: 'swastikasana', n: 'Glückssitz', sa: 'Swastikasana', c: 'boden', lv: 1, m: 1.5, pose: 'z4', t: 'ruhe wurzel', x: 'knie huefte', d: 'Sitz mit überkreuzten Beinen, die Füße liegen zwischen Oberschenkel und Wade; aufrechter Rücken.', kat: {'pos':['sitzen']} });
N({ id: 'tisch_knie_nase', n: 'Balancierender Tisch – Knie zur Nase', sa: 'Dandayamana Bharmanasana Knee To Nose', c: 'kraft', lv: 1, m: 1, pose: 'z6', t: 'kraft balance bauch', x: 'handgelenk knie', d: 'Aus dem Vierfüßlerstand ein Bein nach hinten strecken, dann Knie und Stirn unter dem Körper zusammenführen.', kat: {'pos':['knien']} });
N({ id: 'bananasana', n: 'Banane', sa: 'Bananasana', c: 'boden', lv: 1, m: 1.5, pose: 'z7', t: 'seit loslassen ruhe', x: 'nacken', d: 'Rückenlage, Arme und Beine wandern in einem Bogen zur Seite – dehnt die ganze Flanke.', kat: {'pos':['liegen'],'dir':['seit']} });
N({ id: 'bharadvajasana', n: 'Bharadvaja-Drehsitz', sa: 'Bharadvajasana', c: 'boden', lv: 2, m: 1.5, pose: 'z8', t: 'ruecken loslassen', x: 'ruecken knie osteoporose', d: 'Sitz mit den Füßen seitlich neben dem Gesäß, Oberkörper dreht sich aufrecht zur Seite.', kat: {'pos':['sitzen'],'dir':['dreh']} });
N({ id: 'padangusthasana', n: 'Große-Zehen-Vorbeuge', sa: 'Padangusthasana', c: 'stand', lv: 1, m: 1, pose: 'z9', t: 'ruecken loslassen', x: 'ruecken blutdruck schwindel', d: 'Vorbeuge im Stand, die Finger umgreifen die großen Zehen; Knie dürfen gebeugt bleiben.', kat: {'pos':['stehen'],'dir':['vor']} });
N({ id: 'stuhl_zehenspitzen', n: 'Stuhl auf Zehenspitzen', sa: 'Utkatasana on Tiptoes', c: 'kraft', lv: 2, m: 1, pose: 'z19', t: 'kraft balance', x: 'knie schwindel fuss', d: 'Stuhlhaltung mit angehobenen Fersen, Arme nach oben – kräftigt Beine und schult das Gleichgewicht.', kat: {'pos':['stehen']} });
N({ id: 'kinnstand', n: 'Kinnstand', sa: 'Ganda Bherundasana', c: 'balance', lv: 3, m: 1, pose: 'z22', t: 'balance kraft', x: 'nacken ruecken schwindel blutdruck', man: true, d: 'In Bauchlage das Kinn auf den Boden stützen und die Beine senkrecht nach oben führen.', kat: {'pos':['stuetz','balance']} });
N({ id: 'fuss_hinter_kopf', n: 'Fuß hinter dem Kopf', sa: 'Eka Pada Sirsasana', c: 'boden', lv: 3, m: 1.5, pose: 'z24', t: 'huefte loslassen', x: 'huefte knie ruecken nacken', d: 'Im Sitz ein Bein hinter Schulter und Kopf legen – sehr tiefe Hüftöffnung.', kat: {'pos':['sitzen']} });
N({ id: 'totenstellung', n: 'Totenstellung', sa: 'Savasana', c: 'boden', lv: 1, m: 3, pose: 'z25', t: 'ruhe loslassen', d: 'Entspannte Rückenlage mit leicht geöffneten Armen und Beinen zum Nachspüren am Ende der Stunde.', kat: {'pos':['liegen']} });
N({ id: 'developpe', n: 'Développé', c: 'balance', lv: 2, m: 1, pose: 'z30', t: 'balance huefte', x: 'schwindel knie huefte', man: true, d: 'Einbeiniger Stand, das andere Knie hochziehen und das Bein nach vorn strecken (Tanzbewegung).', kat: {'pos':['stehen','balance']} });
N({ id: 'doppelte_zehenhaltung', n: 'Doppelte Große-Zehen-Haltung', sa: 'Ubhaya Padangusthasana', c: 'kraft', lv: 2, m: 1, pose: 'z32', t: 'kraft balance bauch', x: 'ruecken knie', d: 'Auf dem Gesäß balancieren, beide Beine gestreckt nach oben, Hände fassen die großen Zehen.', kat: {'pos':['sitzen']} });
N({ id: 'hund_knie_nase', n: 'Herabschauender Hund – Knie zur Nase', sa: 'Adho Mukha Svanasana Knee To Nose', c: 'kraft', lv: 2, m: 1, pose: 'z35', t: 'kraft bauch', x: 'handgelenk schulter blutdruck', d: 'Aus dem Herabschauenden Hund ein Bein anheben und das Knie unter dem Körper zur Nase führen.', kat: {'pos':['stuetz']} });
N({ id: 'drachenhocke', n: 'Drachenhocke', sa: 'Dragon Squat', c: 'stand', lv: 2, m: 1, pose: 'z36', t: 'huefte kraft', x: 'knie huefte', d: 'Tiefer Ausfallschritt mit einer Hand am Boden, der Arm der anderen Seite öffnet sich nach oben.', kat: {'pos':['stehen']} });
N({ id: 'astavakrasana', n: 'Acht-Winkel-Haltung', sa: 'Astavakrasana', c: 'balance', lv: 3, m: 1, pose: 'z41', t: 'balance kraft', x: 'handgelenk schulter huefte', d: 'Die Beine über einen Oberarm legen und seitlich nach vorn strecken, das Becken schwebt über dem Boden.', kat: {'pos':['stuetz','balance']} });
N({ id: 'elefantenruessel', n: 'Elefantenrüssel', sa: 'Eka Hasta Bhujasana', c: 'balance', lv: 3, m: 1, pose: 'z42', t: 'balance kraft', x: 'handgelenk schulter huefte', d: 'Ein Bein über den Oberarm legen, das Gewicht auf die Hände verlagern und das andere Bein nach vorn strecken.', kat: {'pos':['stuetz','balance']} });
N({ id: 'gefallenes_dreieck', n: 'Gefallenes Dreieck', sa: 'Patita Tarasana', c: 'kraft', lv: 3, m: 1, pose: 'z46', t: 'kraft herz', x: 'handgelenk schulter', man: true, d: 'Aus dem Seitstütz ein Bein nach hinten absenken und die Brust öffnen.', kat: {'pos':['stuetz'],'dir':['rueck']} });
N({ id: 'fliegende_streckung', n: 'Fliegende Streckung', sa: 'Flying Extended', c: 'kraft', lv: 3, m: 1, pose: 'z50', t: 'kraft balance', x: 'handgelenk schulter knie', man: true, d: 'Dynamischer Übergang im Stütz mit weit ausgestrecktem Bein.', kat: {'pos':['stuetz']} });
N({ id: 'fliegende_planke', n: 'Fliegende Planke', sa: 'Flying Plank', c: 'kraft', lv: 3, m: 1, pose: 'z52', t: 'kraft balance', x: 'handgelenk schulter', man: true, d: 'Planke mit angehobenem Bein und einem seitlich ausgestreckten Arm.', kat: {'pos':['stuetz']} });
N({ id: 'fliegender_spagat', n: 'Fliegender Spagat', sa: 'Eka Pada Koundinyasana', c: 'balance', lv: 3, m: 1, pose: 'z53', t: 'balance kraft huefte', x: 'handgelenk schulter huefte', d: 'Armbalance, ein Bein über den Oberarm, das andere gestreckt nach hinten.', kat: {'pos':['stuetz','balance']} });
N({ id: 'fliegender_krieger', n: 'Fliegender Krieger', sa: 'Flying Warrior', c: 'balance', lv: 3, m: 1, pose: 'z54', t: 'balance kraft', x: 'schwindel knie', man: true, d: 'Einbeiniger Stand mit nach hinten gestrecktem Bein und weit geöffneten Armen.', kat: {'pos':['stehen','balance']} });
N({ id: 'fliegendes_wild_thing', n: 'Fliegendes Wild Thing', sa: 'Flying Wild Thing', c: 'kraft', lv: 3, m: 1, pose: 'z55', t: 'kraft herz', x: 'handgelenk schulter', man: true, d: 'Dynamische Variante des Wild Thing mit angehobenem Bein.', kat: {'pos':['stuetz'],'dir':['rueck']} });
N({ id: 'unterarmplanke', n: 'Unterarmplanke', sa: 'Phalakasana Variation', c: 'kraft', lv: 2, m: 1, pose: 'z56', t: 'kraft bauch', x: 'schulter nacken', d: 'Planke auf den Unterarmen – kräftigt Rumpf und Schultern.', kat: {'pos':['stuetz']} });
N({ id: 'vorbeuge_haende_verschraenkt', n: 'Vorbeuge mit verschränkten Händen', sa: 'Uttanasana with interlocked hands', c: 'stand', lv: 1, m: 1, pose: 'z58', t: 'schulter ruecken loslassen', x: 'ruecken blutdruck schwindel', d: 'Vorbeuge im Stand, die Hände hinter dem Rücken verschränkt und nach oben geführt – öffnet Brust und Schultern.', kat: {'pos':['stehen'],'dir':['vor']} });
N({ id: 'frosch', n: 'Frosch', sa: 'Bhekasana', c: 'boden', lv: 2, m: 1.5, pose: 'z59', t: 'ruecken huefte', x: 'knie ruecken', d: 'Bauchlage, ein Fuß wird zum Gesäß gezogen und mit der Hand gehalten.', kat: {'pos':['liegen'],'dir':['rueck']} });
N({ id: 'halbes_boot', n: 'Halbes Boot', sa: 'Ardha Navasana', c: 'kraft', lv: 2, m: 1, pose: 'z65', t: 'kraft bauch', x: 'ruecken blutdruck', d: 'Beine und Oberkörper schräg angehoben, Arme nach vorn – Bauchkräftigung.', kat: {'pos':['sitzen']} });
N({ id: 'halblotus_vorbeuge_sitzend', n: 'Gebundener Halblotus – sitzende Vorbeuge', sa: 'Ardha Baddha Padma Paschimottanasana', c: 'boden', lv: 3, m: 1.5, pose: 'z66', t: 'huefte ruecken loslassen', x: 'knie huefte ruecken', d: 'Ein Fuß liegt im Halblotus, der Arm bindet den Fuß, Vorbeuge über das gestreckte Bein.', kat: {'pos':['sitzen'],'dir':['vor']} });
N({ id: 'halblotus_vorbeuge_stehend', n: 'Gebundener Halblotus – stehende Vorbeuge', sa: 'Ardha Baddha Padma Uttanasana', c: 'balance', lv: 3, m: 1.5, pose: 'z67', t: 'balance huefte', x: 'knie huefte schwindel ruecken', d: 'Einbeinig stehend, ein Fuß im Halblotus gebunden, Vorbeuge nach vorn.', kat: {'pos':['stehen','balance'],'dir':['vor']} });
N({ id: 'halber_bogen', n: 'Halber Bogen', sa: 'Ardha Dhanurasana', c: 'boden', lv: 2, m: 1, pose: 'z68', t: 'ruecken herz', x: 'ruecken nacken', d: 'Bauchlage, ein Bein wird nach hinten gegriffen, der andere Arm streckt sich nach vorn.', kat: {'pos':['liegen'],'dir':['rueck']} });
N({ id: 'reiher', n: 'Reiher', sa: 'Krounchasana', c: 'boden', lv: 3, m: 1.5, pose: 'z77', t: 'huefte ruecken loslassen', x: 'knie huefte ruecken', d: 'Ein Bein angewinkelt, das andere wird gestreckt nach oben zum Gesicht gezogen.', kat: {'pos':['sitzen'],'dir':['vor']} });
N({ id: 'pferdegesicht', n: 'Pferdegesicht', sa: 'Vatayanasana', c: 'balance', lv: 3, m: 1, pose: 'z79', t: 'balance huefte', x: 'knie huefte schwindel', man: true, d: 'Einbeinige Hockhaltung mit überkreuzten Beinen, Arme nach oben.', kat: {'pos':['stehen','balance']} });
N({ id: 'kniende_rueckbeuge', n: 'Kniende Rückbeuge', c: 'boden', lv: 2, m: 1, pose: 'z81', t: 'herz ruecken', x: 'ruecken nacken knie', d: 'Aus dem Kniestand die Arme nach oben führen und die Brust öffnen.', kat: {'pos':['knien'],'dir':['rueck']} });
N({ id: 'ausfallschritt_drehung', n: 'Tiefer Ausfallschritt mit Drehung', sa: 'Parivrtta Anjaneyasana', c: 'stand', lv: 2, m: 1.5, pose: 'z88', t: 'huefte ruecken kraft', x: 'knie ruecken schwindel', d: 'Tiefer Ausfallschritt, Gebetshände vor der Brust, der Oberkörper dreht sich zum vorderen Bein.', kat: {'pos':['stehen'],'dir':['dreh']} });
N({ id: 'sprinter_twist', n: 'Twist im Sprinter', sa: 'Parivrtta Ashwa Sanchalanasana', c: 'stand', lv: 2, m: 1, pose: 'lunge', t: 'ruecken huefte kraft loslassen', x: 'knie handgelenk ruecken schwindel osteoporose', e: 'ashwa', d: 'Aus dem Sprinter (tiefer Ausfallschritt, Hände am Boden) die Hand auf der Seite des hinteren Beins aufstützen, den anderen Arm zur Decke öffnen und den Oberkörper zum vorderen Bein drehen; Blick zur Hand oben. Rücken lang halten, vorderes Knie über dem Fuß, mit dem Atem ein- und ausdrehen. Dehnt Hüftbeuger und Brustkorb, mobilisiert die Brustwirbelsäule und kräftigt die Beine. Hinteres Knie darf zur Entlastung abgelegt werden.', w: 'Bei Knie-, Handgelenks- oder Rückenproblemen, Schwindel und Osteoporose die Drehung klein halten oder die Hand auf einem Block abstützen; nicht in die Drehung zwingen.', src: 'Eigene Ergänzung (Recherche: Yoga Journal, Inside Yoga zu gedrehten Ausfallschritt-Varianten)', st: 'hatha vinyasa', kat: {'pos':['stehen'],'dir':['dreh']} });
N({ id: 'supta_matsyendrasana', n: 'Liegender Drehsitz', sa: 'Supta Matsyendrasana', c: 'boden', lv: 1, m: 1.5, pose: 'twist_supine', t: 'ruecken loslassen ruhe', x: 'osteoporose ruecken', e: 'drehung_liegend', d: 'In Rückenlage mit seitlich ausgestreckten Armen ein Knie zur Brust ziehen und beim Ausatmen über die Körpermitte zur Gegenseite ablegen, das andere Bein bleibt lang. Schultern bleiben am Boden, Blick zur Gegenseite oder geradeaus. Löst Rücken, Hüfte und Schultern und regt die Verdauung an. Die Haltung ruhig halten und mit dem Ausatmen tiefer lassen; Kissen oder Block unter dem Knie machen sie weicher.', w: 'Bei Rückenbeschwerden und Osteoporose die Drehung klein halten und das Knie abstützen; nicht in die Drehung zwingen.', src: 'Eigene Ergänzung (Recherche: Art of Living, Yoga Matters)', st: 'hatha yin', g: 'supine', kat: {'pos':['liegen'],'dir':['dreh']} });
N({ id: 'matrix_krieger', n: 'Matrix-Krieger', c: 'kraft', lv: 2, m: 1, pose: 'z91', t: 'kraft energie', x: 'knie ruecken', man: true, d: 'Fließende Folge aus Ausfallschritt und weit geöffneten Armen.', kat: {'pos':['stehen']} });
N({ id: 'meerjungfrau', n: 'Meerjungfrau', sa: 'Naginyasana', c: 'boden', lv: 3, m: 1.5, pose: 'z93', t: 'huefte herz', x: 'knie huefte schulter', d: 'Sitz mit seitlich gebeugtem Bein, der hintere Fuß wird mit den Händen über dem Kopf gehalten.', kat: {'pos':['sitzen'],'dir':['rueck']} });
N({ id: 'mini_attitude', n: 'Mini-Attitude', c: 'balance', lv: 2, m: 1, pose: 'z94', t: 'balance huefte', x: 'knie schwindel', man: true, d: 'Tiefer Ausfallschritt mit einem Arm nach oben und dem anderen nach vorn.', kat: {'pos':['stehen','balance']} });
N({ id: 'mini_wild_thing', n: 'Mini Wild Thing', sa: 'Camatkarasana Variation', c: 'kraft', lv: 2, m: 1, pose: 'z95', t: 'herz kraft', x: 'handgelenk schulter', d: 'Vorstufe des Wild Thing: Seitstütz mit gebeugtem Knie und weit geöffnetem Arm.', kat: {'pos':['stuetz'],'dir':['rueck']} });
N({ id: 'pendel', n: 'Pendel', sa: 'Lolasana', c: 'balance', lv: 3, m: 1, pose: 'z104', t: 'balance kraft bauch', x: 'handgelenk schulter', d: 'Aus dem Fersensitz das Gesäß vom Boden heben und den Körper zwischen den Armen pendeln lassen.', kat: {'pos':['stuetz','balance']} });
N({ id: 'taube_rueckbeuge', n: 'Taube – tiefe Rückbeuge', sa: 'Kapotasana', c: 'boden', lv: 3, m: 1, pose: 'z105', t: 'herz ruecken', x: 'ruecken nacken knie schulter', man: true, d: 'Aus dem Kniestand tief nach hinten beugen und die Hände zu den Füßen führen.', kat: {'pos':['knien'],'dir':['rueck']} });
N({ id: 'pistol_roll', n: 'Pistol Roll', c: 'kraft', lv: 3, m: 1, pose: 'z106', t: 'kraft bauch', x: 'knie ruecken', man: true, d: 'Rollbewegung vom Sitz in die Einbeinhocke, die Arme schwingen mit.', kat: {'pos':['sitzen']} });
N({ id: 'pistole_fussgriff', n: 'Pistole mit Fußgriff', sa: 'Eka Pada Malasana Squat', c: 'balance', lv: 3, m: 1, pose: 'z107', t: 'balance kraft huefte', x: 'knie huefte schwindel', d: 'Einbeinige tiefe Hocke, das andere Bein gestreckt nach vorn, Hand am Fuß.', kat: {'pos':['stehen','balance']} });
N({ id: 'regenbogen_krieger', n: 'Regenbogen-Krieger', c: 'stand', lv: 2, m: 1, pose: 'z111', t: 'seit huefte kraft', x: 'knie ruecken', d: 'Ausfallschritt mit seitlicher Beuge, ein Arm bildet einen Bogen über dem Kopf.', kat: {'pos':['stehen'],'dir':['seit']} });
N({ id: 'liegende_zehe', n: 'Liegender Zeh-Griff', sa: 'Supta Padangusthasana', c: 'boden', lv: 1, m: 1.5, pose: 'z113', t: 'huefte loslassen', x: 'huefte', d: 'In Rückenlage ein Bein zur Decke strecken und die große Zehe oder einen Gurt halten.', kat: {'pos':['liegen']} });
N({ id: 'umgekehrter_krieger', n: 'Umgekehrter Krieger', sa: 'Viparita Virabhadrasana', c: 'stand', lv: 2, m: 1, pose: 'z117', t: 'seit huefte kraft', x: 'knie ruecken', d: 'Aus Krieger II den vorderen Arm nach oben führen, der hintere Arm gleitet am Bein entlang.', kat: {'pos':['stehen'],'dir':['seit']} });
N({ id: 'gedrehte_zehenhaltung', n: 'Gedrehte Hand-zum-Fuß-Haltung', sa: 'Parivrtta Utthita Hasta Padangusthasana', c: 'balance', lv: 3, m: 1.5, pose: 'z118', t: 'balance huefte ruecken', x: 'schwindel knie huefte ruecken', d: 'Einbeiniger Stand, das gestreckte Bein wird seitlich gegriffen, der Oberkörper dreht sich.', kat: {'pos':['stehen','balance'],'dir':['dreh']} });
N({ id: 'gedrehte_hocke', n: 'Gedrehte Hocke', sa: 'Parivrtta Malasana', c: 'stand', lv: 2, m: 1, pose: 'z123', t: 'huefte ruecken', x: 'knie huefte', d: 'Tiefe Hocke, ein Ellbogen am Knie, der andere Arm zeigt zur Decke.', kat: {'pos':['stehen'],'dir':['dreh']} });
N({ id: 'ronde', n: 'Ronde', c: 'balance', lv: 2, m: 1, pose: 'z125', t: 'balance huefte', x: 'schwindel knie', man: true, d: 'Tanzbewegung: Das Spielbein beschreibt einen Halbkreis über den Boden.', kat: {'pos':['stehen','balance']} });
N({ id: 'laeufer', n: 'Läufer', c: 'stand', lv: 2, m: 1, pose: 'z126', t: 'kraft huefte', x: 'knie ruecken', d: 'Stand mit gebeugtem Standbein, das andere Bein angewinkelt zurück, Oberkörper leicht vorgeneigt.', kat: {'pos':['stehen']} });
N({ id: 'visvamitrasana', n: 'Visvamitra-Haltung', sa: 'Visvamitrasana', c: 'balance', lv: 3, m: 1, pose: 'z128', t: 'balance huefte kraft', x: 'handgelenk schulter huefte', d: 'Armbalance, ein Bein über der Schulter, das andere gestreckt zur Seite, Blick zur Hand.', kat: {'pos':['stuetz','balance']} });
N({ id: 'schulterdruck', n: 'Schulterdruck-Haltung', sa: 'Bhujapidasana', c: 'balance', lv: 3, m: 1, pose: 'z132', t: 'balance kraft', x: 'handgelenk schulter huefte', d: 'Die Oberschenkel liegen auf den Oberarmen, die Füße heben sich vom Boden.', kat: {'pos':['stuetz','balance']} });
N({ id: 'skating', n: 'Skating', c: 'kraft', lv: 2, m: 1, pose: 'z136', t: 'kraft energie', x: 'knie huefte', man: true, d: 'Dynamischer seitlicher Ausfallschritt wie beim Schlittschuhlaufen.', kat: {'pos':['stehen']} });
N({ id: 'gleitende_planke', n: 'Gleitende Planke', sa: 'Slide Plank', c: 'kraft', lv: 3, m: 1, pose: 'z137', t: 'kraft', x: 'handgelenk schulter', man: true, d: 'Seitstütz, bei dem das obere Bein vor und zurück gleitet.', kat: {'pos':['stuetz']} });
N({ id: 'rueckbeuge_haende_verschraenkt', n: 'Stehende Rückbeuge mit verschränkten Händen', sa: 'Anuvittasana with interlocked hands', c: 'stand', lv: 2, m: 1, pose: 'z142', t: 'herz schulter', x: 'ruecken nacken schwindel', d: 'Hände hinter dem Rücken verschränken, Brust öffnen und den Oberkörper leicht nach hinten neigen.', kat: {'pos':['stehen'],'dir':['rueck']} });
N({ id: 'stehende_umarmung', n: 'Stehende Umarmung', c: 'stand', lv: 1, m: 1, pose: 'z144', t: 'ruhe herz', d: 'Im Stand die Arme über der Brust kreuzen und sich selbst umarmen.', kat: {'pos':['stehen']} });
N({ id: 'superwoman', n: 'Superwoman / Superman', c: 'kraft', lv: 1, m: 1, pose: 'z150', t: 'ruecken kraft', x: 'ruecken', d: 'Aus dem Vierfüßlerstand oder der Bauchlage Arm und gegenüberliegendes Bein strecken und heben.', kat: {'pos':['liegen'],'dir':['rueck']} });
N({ id: 'dreibeiniger_hund', n: 'Dreibeiniger Hund', sa: 'Tri Pada Adho Mukha Svanasana', c: 'kraft', lv: 2, m: 1, pose: 'z156', t: 'kraft huefte', x: 'handgelenk schulter blutdruck', d: 'Herabschauender Hund, ein Bein senkrecht nach oben gestreckt.', kat: {'pos':['stuetz']} });
N({ id: 'dreibeiniger_hund_gestapelt', n: 'Dreibeiniger Hund mit gestapelten Knien', sa: 'Tri Pada Adho Mukha Svanasana Variation', c: 'kraft', lv: 3, m: 1, pose: 'z157', t: 'kraft huefte', x: 'handgelenk schulter blutdruck', d: 'Dreibeiniger Hund, das angehobene Knie wird geöffnet und über das Standbein gelegt.', kat: {'pos':['stuetz'],'dir':['dreh']} });
N({ id: 'drei_schritte_spagat', n: 'Drei-Schritte-Spagat', sa: 'Utthita Trivikramasana', c: 'balance', lv: 3, m: 1.5, pose: 'z158', t: 'balance huefte', x: 'schwindel knie huefte', d: 'Einbeiniger Stand, das andere Bein senkrecht nach oben gestreckt, Hände nah am Standbein.', kat: {'pos':['stehen','balance']} });
N({ id: 'zehenbalance', n: 'Zehenbalance', sa: 'Prapadasana', c: 'balance', lv: 3, m: 1, pose: 'z159', t: 'balance wurzel', x: 'schwindel knie fuss', d: 'Tiefe Hocke auf den Zehenspitzen balancieren, Hände vor der Brust.', kat: {'pos':['stehen','balance']} });
N({ id: 'gedrehter_taenzer', n: 'Gedrehter Tänzer', sa: 'Parivrtta Natarajasana', c: 'balance', lv: 3, m: 1.5, pose: 'z163', t: 'balance herz', x: 'schwindel knie schulter ruecken', d: 'Tänzer mit Gegenarm: Das hintere Bein wird mit der gegenüberliegenden Hand gegriffen.', kat: {'pos':['stehen','balance'],'dir':['dreh']} });
N({ id: 'beine_oben', n: 'Beine nach oben gestreckt', sa: 'Urdhva Prasarita Padasana', c: 'kraft', lv: 1, m: 1, pose: 'z165', t: 'bauch kraft', x: 'ruecken', d: 'In Rückenlage beide Beine senkrecht nach oben strecken und langsam wieder senken.', kat: {'pos':['liegen']} });
N({ id: 'sitzende_vorbeuge_oben', n: 'Aufwärts gerichtete sitzende Vorbeuge', sa: 'Urdhva Mukha Paschimottanasana', c: 'kraft', lv: 2, m: 1, pose: 'z167', t: 'kraft ruecken bauch', x: 'ruecken knie', d: 'Im Sitz die Füße greifen und die gestreckten Beine nach oben ziehen (V-Haltung).', kat: {'pos':['sitzen'],'dir':['vor']} });
N({ id: 'weite_graetsche_oben', n: 'Aufwärts gerichtete weite Grätsche', sa: 'Urdhva Upavistha Konasana', c: 'kraft', lv: 2, m: 1, pose: 'z168', t: 'kraft huefte bauch', x: 'ruecken huefte', d: 'Im Sitz beide Beine weit gegrätscht anheben, die Hände fassen die Füße.', kat: {'pos':['sitzen']} });
N({ id: 'wild_thing_vorbereitung', n: 'Wild Thing Vorbereitung', c: 'boden', lv: 2, m: 1, pose: 'z181', t: 'herz huefte', x: 'handgelenk schulter', d: 'Aus dem Sitz mit aufgestelltem Bein den Oberkörper öffnen – Vorstufe zum Wild Thing.', kat: {'pos':['sitzen'],'dir':['rueck']} });

// ---------- Weitere Ergänzungen (Recherche Oktober 2026) ----------
N({ id: 'boot_voll', n: 'Boot', sa: 'Navasana', c: 'kraft', lv: 2, m: 1, pose: 'y225a', t: 'kraft bauch balance', x: 'ruecken blutdruck nacken', e: 'halbes_boot', st: 'hatha', d: 'Aus dem Sitz mit angewinkelten Knien die Füße vom Boden lösen, Schienbeine parallel zum Boden, Oberkörper leicht nach hinten neigen und die Arme parallel zum Boden nach vorn strecken; Brustbein bleibt offen, der Rücken lang. Danach lassen sich die Beine strecken. Kräftigt gerade und schräge Bauchmuskeln und Rücken und schult Gleichgewicht und Konzentration.', w: 'Bei Rückenproblemen, Bluthochdruck und Nackenbeschwerden die Beine gebeugt lassen oder mit den Händen hinter dem Rücken abstützen; nicht in die Haltung einsinken lassen.', src: 'Eigene Ergänzung (Recherche: Heidelberg24, Mobilesport Schweiz)', kat: {'pos':['sitzen']} });
N({ id: 'faden_nadeloehr', n: 'Faden durchs Nadelöhr (Schulterdrehung)', sa: 'Parsva Balasana', c: 'boden', lv: 1, m: 1, pose: 'quad_cat', t: 'ruecken schulter loslassen', x: 'schulter nacken knie ruecken', st: 'hatha yin', d: 'Aus dem Vierfüßlerstand einen Arm zur Decke öffnen, dann beim Ausatmen unter dem anderen Arm hindurchfädeln, Handfläche nach oben, Schulter und Wange ruhen auf der Matte. Hüften bleiben über den Knien, die andere Hand drückt in den Boden oder streckt sich nach vorn. 30 bis 60 Sekunden halten. Löst Spannung in Schultern, Nacken und oberem Rücken und dreht die Wirbelsäule sanft.', w: 'Bei Bandscheibenproblemen, Knieproblemen oder Verletzungen an Nacken und Schulter nur mit Unterstützung (Decke unter Knien oder Kopf) oder gar nicht üben.', src: 'Eigene Ergänzung (Recherche: Yoga Matters)', kat: {'pos':['knien'],'dir':['dreh']} });
N({ id: 'demuetiger_krieger', n: 'Demütiger Krieger', sa: 'Baddha Virabhadrasana', c: 'stand', lv: 2, m: 1, pose: 'warrior1', t: 'huefte schulter loslassen', x: 'blutdruck ruecken schwindel knie schulter', e: 'krieger1', st: 'hatha vinyasa', d: 'Aus Krieger I die Hände hinter dem Rücken verschränken, Brust öffnen und Schultern zurück und nach unten ziehen. Beim Ausatmen den Oberkörper innen am vorderen Bein nach unten falten, die Beine bleiben aktiv. Zum Aufrichten einatmen. Dehnt Hüften, Brust und Schultern und kräftigt die Beine.', w: 'Nicht bei Bluthochdruck, Rückenverletzung oder Bandscheibenvorfall und in der Schwangerschaft; bei engen Schultern die Hände nicht verschränken, sondern einen Gurt halten.', src: 'Eigene Ergänzung (Recherche: Yoga Matters, Brett Larkin)', kat: {'pos':['stehen'],'dir':['vor']} });
N({ id: 'loewe', n: 'Löwe', sa: 'Simhasana', c: 'boden', lv: 1, m: 1, pose: 'hero', t: 'atem energie loslassen', x: 'knie handgelenk', st: 'hatha', d: 'Im Fersensitz (alternativ auf einem Stuhl) die Hände mit gespreizten Fingern auf die Knie legen, Rücken gerade. Mund weit öffnen, Zunge zum Kinn herausstrecken und mit der Ausatmung kräftig „Haaa“ ausstoßen. Anfänger halten 10 bis 30 Sekunden mit 2 bis 3 Wiederholungen. Löst Spannung in Kiefer, Gesicht und Hals und unterstützt die Atmung.', w: 'Bei Knieproblemen auf dem Stuhl üben; bei schwachen Handgelenken die Hände auf die Oberschenkel legen.', src: 'Eigene Ergänzung (Recherche: MasterClass; weitere Quellen nur Gesundheitsblogs, Details bitte fachlich prüfen)', kat: {'pos':['sitzen']} });
N({ id: 'zehenhocke', n: 'Zehenhocke', sa: 'Toe Squat', c: 'boden', lv: 1, m: 2, pose: 'hero', t: 'wurzel loslassen', x: 'fuss knie', st: 'yin', d: 'Aus dem Vierfüßlerstand Knie und Füße zusammenbringen, alle zehn Zehen aufstellen und die Hände zurück zu den Knien laufen lassen, bis das Gesäß auf den Fersen ruht. Gewicht auf die Fußballen, nicht auf die Zehenspitzen. Anfangs etwa eine Minute, später bis zu drei Minuten halten. Dehnt die Fußsohlen und beginnt die Dehnung der gesamten Rückenfaszie.', w: 'Bei empfindlichen Zehen, Fuß- oder Kniebeschwerden früher lösen oder mit einer Decke unter dem Gesäß üben.', src: 'Eigene Ergänzung (Recherche: Ekhart Yoga, Byron Yoga)', kat: {'pos':['sitzen','knien']} });
N({ id: 'katze_schwanz', n: 'Katze zieht ihren Schwanz', sa: 'Cat Pulling Its Tail', c: 'boden', lv: 2, m: 3, pose: 'sit_twist', t: 'ruecken huefte loslassen', x: 'knie ruecken', st: 'yin', d: 'Aus dem Sitz mit gestreckten Beinen zur Seite drehen und auf den Ellbogen zurücklehnen. Das untere Bein bleibt gestreckt oder wird gebeugt, das obere Knie geht nach vorn; mit der freien Hand den Fuß des unteren Beins greifen und vom Körper wegziehen. Gegenhaltung zu starken Vorbeugen, dehnt Oberschenkelvorderseite und Hüftbeuger und belastet den unteren Rücken leicht. Etwa 3 Minuten je Seite.', w: 'Bei Knie- oder Rückenproblemen mit Unterstützung (Bolster, Decke) und kleinem Bewegungsradius üben.', src: 'Eigene Ergänzung (Recherche: Yin Yoga Insights)', kat: {'pos':['liegen'],'dir':['dreh']} });
N({ id: 'gedrehte_graetsche', n: 'Gedrehte weite Grätsche', sa: 'Parivrtta Upavistha Konasana', c: 'boden', lv: 2, m: 1.5, pose: 'y236h', t: 'huefte ruecken loslassen', x: 'ruecken huefte osteoporose', e: 'upavistha', st: 'hatha', d: 'Im weiten Grätschsitz mit angezogenen Fußspitzen den Oberkörper zu einem Fuß drehen, beim Einatmen die Wirbelsäule lang machen und beim Ausatmen in der Linie des Oberschenkels nach vorn falten; die Hände gehen auf Blöcke, den Boden oder zum Fuß. Seitenwechsel. Öffnet die Hüften, kräftigt die schrägen Bauchmuskeln und regt die Verdauung an.', w: 'Nicht bei Wirbelsäulenverletzung, Verdauungsbeschwerden oder in der Schwangerschaft; erhöht auf einer Decke sitzen und nur leicht falten ist die sanfte Variante.', src: 'Eigene Ergänzung (Recherche: Brett Larkin)', kat: {'pos':['sitzen'],'dir':['dreh','vor']} });
N({ id: 'supta_vajrasana', n: 'Schlafender Donnerkeil', sa: 'Supta Vajrasana', c: 'boden', lv: 3, m: 1.5, pose: 'supta_hero', t: 'ruecken huefte atem', x: 'knie fuss ruecken', man: true, st: 'hatha', d: 'Aus dem Fersensitz (Vajrasana) beim Einatmen auf die Unterarme zurücklehnen, den Kopf nach hinten sinken lassen und beim Ausatmen ganz auf den Rücken ablegen, Arme über dem Kopf. Dehnt Oberschenkel und Hüften, öffnet den Brustkorb und regt die Verdauung an. Eng verwandt mit dem Liegenden Helden (Supta Virasana).', w: 'Nicht bei schweren Knie- oder Sprunggelenksverletzungen, Ischias, Bandscheibenproblemen oder frischen Operationen; ein Kissen unter dem Gesäß macht die Haltung leichter.', src: 'Eigene Ergänzung (Recherche: Amala Ayurveda, Medkart; Gesundheitsblogs, bitte fachlich prüfen)', kat: {'pos':['liegen'],'dir':['rueck']} });
N({ id: 'superman', n: 'Heuschrecke gestreckt (Superman)', sa: 'Viparita Salabhasana', c: 'boden', lv: 2, m: 1, pose: 'y506b', t: 'ruecken kraft', x: 'ruecken nacken blutdruck', st: 'hatha', d: 'In Bauchlage die Arme nach vorn strecken und beim Einatmen Arme, Brust und Beine gleichzeitig anheben; der Körper balanciert auf dem Bauch. Gleichmäßig atmen, beim Ausatmen sanft ablegen. Kräftigt unteren Rücken, Bauch und Brust und dehnt Schultern und Brustkorb.', w: 'Nicht bei akuten Rückenschmerzen, Bandscheibenvorfall, Nackenverletzung, Ischias, Bluthochdruck, Herzproblemen, Bruch oder Magengeschwür und in der Schwangerschaft.', src: 'Eigene Ergänzung (Recherche: Dimensions, Stylecraze, Brett Larkin)', kat: {'pos':['liegen'],'dir':['rueck']} });
N({ id: 'halber_lotus', n: 'Halber Lotussitz', sa: 'Ardha Padmasana', c: 'boden', lv: 2, m: 1.5, pose: 'y228b', t: 'huefte ruhe', x: 'knie huefte fuss', e: 'sukhasana', st: 'hatha', d: 'Aus dem Langsitz ein Knie beugen und die Ferse nah zum Gesäß ziehen, damit die Drehung aus der Hüfte kommt; den Fuß auf die Leiste des gegenüberliegenden Oberschenkels legen, die Sohle zeigt nach oben. Das andere Bein liegt darunter. Öffnet die Hüften, dehnt Knie und Knöchel und dient als Alternative zum vollen Lotussitz für Meditation und Atemübungen. Seitenwechsel.', w: 'Bei Knieproblemen oder Ischias nicht üben; bei jedem Ziehen im Knie sofort lösen, nie mit Gewalt in die Haltung gehen.', src: 'Eigene Ergänzung (Recherche: Liforme, Pranayoga)', kat: {'pos':['sitzen']} });
N({ id: 'sitz_seitneigung', n: 'Seitneigung im Sitzen', sa: 'Parsva Sukhasana', c: 'mobi_sitz', lv: 1, m: 1, pose: 'sit_side', t: 'ruecken atem mobi loslassen', x: '', st: 'hatha', d: 'Im Leichten Sitz die Sitzhöcker gleichmäßig belasten, eine Hand neben dem Becken aufsetzen und den anderen Arm über den Kopf zur Seite neigen; Brustbein bleibt offen. Mit dem Atem in die Flanken atmen und die Seite wechseln. Öffnet Rippen und Flanken, unterstützt tiefere Atmung und bereitet auf Meditation vor.', src: 'Eigene Ergänzung (Recherche: Blooming Lotus Yoga, Yoga Journal; keine genaue Schritt-für-Schritt-Anleitung gefunden, Beschreibung bitte fachlich prüfen)', kat: {'pos':['sitzen'],'dir':['seit']} });
N({ id: 'scheibenwischer', n: 'Scheibenwischer in Rückenlage', sa: 'Windshield Wipers', c: 'boden', lv: 1, m: 1, pose: 'twist_supine', t: 'ruecken loslassen bauch', x: 'ruecken osteoporose', st: 'hatha', d: 'In Rückenlage die Füße hüftbreit aufstellen, Arme seitlich ablegen. Beide Knie langsam und kontrolliert zur einen Seite sinken lassen, Schultern bleiben am Boden, dann zur anderen Seite wechseln. Mobilisiert Lendenwirbelsäule und Hüften und kräftigt die seitlichen Bauchmuskeln; die Beine nicht schwungvoll fallen lassen. Fortgeschrittene führen die Übung mit angehobenen, gestreckten Beinen aus.', w: 'Bei Rückenbeschwerden und Osteoporose klein und langsam üben; wenn sich der Rücken vom Boden hebt, den Bewegungsradius verkleinern.', src: 'Eigene Ergänzung (Recherche: MasterClass, Strengthlog; Fitnessübung, kein klassisches Asana)', kat: {'pos':['liegen'],'dir':['dreh']} });
N({ id: 'pasasana', n: 'Schlinge', sa: 'Pasasana', c: 'stand', lv: 3, m: 1.5, pose: 'z123', t: 'huefte ruecken schulter loslassen', x: 'knie huefte fuss schulter ruecken', e: 'gedrehte_hocke', man: true, st: 'hatha', d: 'Tiefe Hocke mit Füßen und Knien zusammen, beim Ausatmen den Oberkörper zur Seite drehen, einen Arm außen um beide Knie schlingen und den anderen Arm hinter dem Rücken greifen; Blick über die Schulter. 20 bis 60 Sekunden halten, Seitenwechsel. Dehnt Wirbelsäule, Schultern und Brust, verbessert die Hockenbeweglichkeit und regt die Verdauung an. Bindung zur Gedrehten Hocke.', w: 'Nicht bei Knieverletzungen, Wirbelsäulenentzündung oder Bandscheibenvorfall, Schulterverletzung (dann ohne Bindung), Schwangerschaft und Menstruation; Decke unter die Fersen, Block unter das Gesäß oder Gurt zwischen den Händen sind möglich.', src: 'Eigene Ergänzung (Recherche: Yoga Journal, Lessons.com, David Garrigues)', kat: {'pos':['stehen'],'dir':['dreh']} });
N({ id: 'halber_sattel', n: 'Halber Sattel', sa: 'Ardha Supta Virasana', c: 'boden', lv: 2, m: 3, pose: 'supta_hero', t: 'huefte ruhe loslassen', x: 'knie fuss ruecken', e: 'sattel', st: 'yin', d: 'Aufrecht sitzen, ein Bein nach hinten beugen, den Fuß neben die Hüfte (Fußrücken am Boden, nicht die Seite), das andere Bein bleibt gestreckt oder aufgestellt. Zurücklehnen, das Becken leicht einrollen (Sitzhöcker zeigen zu den Knien), um den unteren Rücken zu entlasten; ein Bolster hinter dem Rücken und ein Block unter dem Kopf helfen. Etwa 3 Minuten je Seite. Dehnt Oberschenkelvorderseite und Hüftbeuger des gebeugten Beins; asymmetrische Variante des Sattels.', w: 'Knie-, Sprunggelenks- oder Rückenverletzungen verschlimmern sich in dieser Haltung; spürt man sie eher im Rücken als im Oberschenkel, das Becken einrollen und höher lagern.', src: 'Eigene Ergänzung (Recherche: Yogaeasy, With Yin Yoga, Byron Yoga)', kat: {'pos':['liegen'],'dir':['rueck']} });

// ---------- Yin-Yoga: Drache, Frosch, Raupe (Recherche Oktober 2026) ----------
N({ id: 'drache_yin', n: 'Drache (Yin)', sa: 'Dragon Pose', c: 'boden', lv: 2, m: 3, pose: 'y139w', t: 'huefte loslassen', x: 'knie huefte', e: 'ausfall_klein', st: 'yin', d: 'Yin-Haltung: aus dem Vierfüßlerstand einen Fuß zwischen die Hände setzen, das hintere Knie auf den Boden (knapp über der Kniescheibe, Richtung Oberschenkel) und das Bein nach hinten gleiten lassen, bis Hüftbeuger und Oberschenkelvorderseite gedehnt werden. Hände auf Boden oder Blöcken, Becken sinkt passiv ab. 3 bis 5 Minuten je Seite. Tiefe Öffnung von Hüftbeugern und Leiste, kann bei Ischiasbeschwerden entlasten.', w: 'Bei Knieverletzungen das hintere Knie polstern (Decke) und die Empfindungen im vorderen Knie beobachten; nicht in den Schmerz gehen.', src: 'Eigene Ergänzung (Recherche: Ekhart Yoga, Yogaeasy, With Yin Yoga)', kat: {'pos':['knien'],'dir':['vor']} });
N({ id: 'drache_gefluegelt', n: 'Geflügelter Drache', sa: 'Winged Dragon', c: 'boden', lv: 2, m: 3, pose: 'y139w', t: 'huefte loslassen', x: 'knie huefte', e: 'drache_yin', st: 'yin', d: 'Variante des Drachen: mit den Händen am Boden das vordere Knie ein paar Mal nach außen „flügeln“, auf die Außenkante des vorderen Fußes rollen und mit abgesenktem Knie in der Haltung bleiben. Verlagert die Dehnung auf die Innenseite des Oberschenkels (Adduktoren). 3 bis 5 Minuten je Seite.', w: 'Bei Knieverletzungen das hintere Knie polstern (Decke) und die Empfindungen im vorderen Knie beobachten; nicht in den Schmerz gehen.', src: 'Eigene Ergänzung (Recherche: Ekhart Yoga, With Yin Yoga)', kat: {'pos':['knien'],'dir':['vor']} });
N({ id: 'drache_gedreht', n: 'Gedrehter Drache', sa: 'Twisted Dragon', c: 'boden', lv: 2, m: 3, pose: 'y139w', t: 'huefte ruecken loslassen', x: 'knie huefte ruecken', e: 'drache_yin', st: 'yin', d: 'Variante des Drachen: vorderen Fuß fest anziehen, mit einer Hand das vordere Knie sanft nach außen drücken und den Brustkorb zur Decke aufdrehen. Kombiniert Hüftbeugerdehnung mit einer Drehung der Wirbelsäule. 3 bis 5 Minuten je Seite. Nicht zu verwechseln mit dem Verdrehten Drachen aus dem Budokon.', w: 'Bei Knieverletzungen das hintere Knie polstern (Decke) und die Empfindungen im vorderen Knie beobachten; nicht in den Schmerz gehen.', src: 'Eigene Ergänzung (Recherche: Ekhart Yoga, With Yin Yoga)', kat: {'pos':['knien'],'dir':['dreh']} });
N({ id: 'frosch_yin', n: 'Frosch (Yin)', sa: 'Mandukasana', c: 'boden', lv: 2, m: 2, pose: 'anahatasana', t: 'huefte loslassen', x: 'knie huefte ruecken blutdruck fuss', e: 'kind_breit', st: 'yin', d: 'Im Vierfüßlerstand die Knie so weit auseinander schieben, wie es angenehm ist, Knöchel in einer Linie mit den Knien, Füße gebeugt. Auf die Unterarme oder die Hände absenken, Hüften auf Kniehöhe halten und nicht ins Hohlkreuz fallen. 1 bis 3 Minuten im Yin. Tiefe Öffnung der Leiste und Oberschenkelinnenseite, leicht rückbeugend, kann Krämpfe lösen.', w: 'Polster unter die Knie; bei steifem Nacken die Stirn statt des Kinns ablegen; bei Knie-, Hüft-, Knöchel- oder Rückenproblemen, Bluthochdruck und Schwangerschaft nicht üben.', src: 'Eigene Ergänzung (Recherche: Yin Yoga Insights, Yoga Matters)', kat: {'pos':['knien']} });
N({ id: 'frosch_halb', n: 'Halber Frosch', sa: 'Ardha Bhekasana', c: 'boden', lv: 2, m: 2, pose: 'z59', t: 'huefte ruecken', x: 'knie ruecken blutdruck schulter', e: 'sphinx', st: 'yin', d: 'In Bauchlage auf die Unterarme in die Sphinx kommen, die Beine strecken, dann einen Arm strecken und mit der anderen Hand nach hinten den Fuß der gleichen Seite greifen und Richtung Gesäß ziehen. Dehnt Oberschenkelvorderseite und Hüftbeuger, leicht rückbeugend. Seitenwechsel.', w: 'Bei Knie-, Rücken- oder Schulterproblemen und Bluthochdruck nicht üben; ein Gurt um den Fuß hilft, wenn die Hand nicht greift; keine eigenen Hinweise zur Vorsicht in der Quelle, deshalb vom Frosch übernommen.', src: 'Eigene Ergänzung (Recherche: Yin Yoga Insights, Yoga Matters)', kat: {'pos':['liegen'],'dir':['rueck']} });
N({ id: 'raupe_yin', n: 'Raupe', sa: 'Caterpillar Pose', c: 'boden', lv: 1, m: 3, pose: 'seated_fold', t: 'ruecken loslassen ruhe', x: 'ruecken', e: 'paschimottanasana', st: 'yin', d: 'Yin-Vorbeuge im Langsitz: bewusst mit rundem Rücken aus der Hüfte nach vorn sinken, Kopf hängt, Knie dürfen gebeugt sein, Decke oder Bolster unter Knien oder Stirn. Der runde Rücken entlastet die Wirbelsäule und dehnt Beinrückseiten und Rückenfaszie. Mindestens 2 Minuten, meist um 5 Minuten halten. Halbe Raupe: ein Bein gestreckt, das andere wie im Schmetterling gebeugt.', w: 'Bei Bandscheibenvorfall oder vorgewölbter Bandscheibe nur mit Vorsicht, Knie beugen und hoch lagern.', src: 'Eigene Ergänzung (Recherche: With Yin Yoga, Bernie Clark über Yin Yoga Insights)', kat: {'pos':['sitzen'],'dir':['vor']} });

// ---------- Kundalini Yoga: Basic Spinal Energy Series und Sat Kriya Workout (Recherche Oktober 2026) ----------
N({ id: 'spinal_flex_sitz', n: 'Wirbelsäulenflex im Sitz (Kamelritt)', sa: 'Spinal Flex / Camel Ride', c: 'mobi_sitz', lv: 1, m: 2, pose: 'sit', t: 'ruecken mobi atem energie', x: '', st: 'kund', d: 'Im Leichten Sitz mit den Händen die Knöchel oder Schienbeine greifen. Beim Einatmen die Wirbelsäule strecken, das Brustbein nach vorn und oben schieben, beim Ausatmen den Rücken runden. Fließend mit dem Atem bewegen. Traditionell 108 Wiederholungen, danach 5 bis 10 Sekunden halten und ruhig atmen; Anfänger beginnen mit weniger. Bringt die Wirbelsäule in Bewegung und wärmt auf.', src: 'Eigene Ergänzung (Recherche: Shakta Kaur, International Yoga Conference; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['sitzen']} });
N({ id: 'spinal_flex_fersen', n: 'Wirbelsäulenflex auf den Fersen', sa: 'Spine Flex on the Heels', c: 'mobi_sitz', lv: 1, m: 2, pose: 'hero', t: 'ruecken mobi atem', x: 'knie fuss', st: 'kund', d: 'Wie der Wirbelsäulenflex im Sitz, aber im Fersensitz mit den Händen auf den Oberschenkeln. Beim Einatmen „Sat“ (Brustbein vor), beim Ausatmen „Nam“ (Rücken runden). Traditionell 108 Wiederholungen, danach 2 Minuten ruhen.', w: 'Bei Knie- oder Fußproblemen auf einer Decke oder im Leichten Sitz üben.', src: 'Eigene Ergänzung (Recherche: Shakta Kaur; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['sitzen','knien']} });
N({ id: 'spinal_flex_oben', n: 'Oberer Wirbelsäulenflex', sa: 'Upper Spinal Flex', c: 'mobi_sitz', lv: 1, m: 1.5, pose: 'sit', t: 'ruecken mobi schulter atem', x: '', st: 'kund', d: 'Im Leichten Sitz die Knie fest greifen. Beim Einatmen den oberen Rücken nach vorn strecken und das Brustbein heben, beim Ausatmen den oberen Rücken nach hinten runden. Der untere Rücken bleibt ruhig. Traditionell 108 Wiederholungen, danach 5 bis 10 Sekunden halten.', src: 'Eigene Ergänzung (Recherche: Shakta Kaur; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['sitzen']} });
N({ id: 'waschmaschine', n: 'Waschmaschine (sitzende Rumpfdrehung)', sa: 'Spinal Twist', c: 'mobi_sitz', lv: 1, m: 1.5, pose: 'sit_twist', t: 'ruecken mobi atem', x: 'osteoporose', st: 'kund', d: 'Im Leichten Sitz die Hände auf die Schultern legen (Daumen hinten, Finger vorn). Beim Einatmen nach links drehen, beim Ausatmen nach rechts, mit langem tiefem Atem. Etwa 26 Wiederholungen, danach 5 bis 10 Sekunden halten. Mobilisiert die Wirbelsäule und die Flanken.', w: 'Bei Osteoporose und Rückenbeschwerden die Drehung klein halten.', src: 'Eigene Ergänzung (Recherche: Shakta Kaur; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['sitzen'],'dir':['dreh']} });
N({ id: 'baerengriff_herz', n: 'Bärengriff am Herzzentrum', sa: 'Bear Grip at Heart Center', c: 'mobi_sitz', lv: 1, m: 1, pose: 'sit', t: 'schulter herz atem', x: 'schulter', st: 'kund', d: 'Im Leichten Sitz die Finger vor dem Herzen verhaken, Ellbogen auf Brusthöhe. Beim Einatmen den rechten Ellbogen heben, beim Ausatmen den linken, wie bei einer Wippe. Etwa 26 Mal, danach 5 bis 10 Sekunden halten. Öffnet Schultern und Brustkorb.', w: 'Bei Schulterproblemen langsam und klein üben.', src: 'Eigene Ergänzung (Recherche: Shakta Kaur; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['sitzen']} });
N({ id: 'baerengriff_hals', n: 'Bärengriff am Halszentrum', sa: 'Bear Grip at Throat Center', c: 'mobi_sitz', lv: 1, m: 1, pose: 'arms_up', t: 'schulter atem energie', x: 'schulter nacken', st: 'kund', d: 'Im Leichten Sitz die Hände auf Halshöhe verhaken, mit dem Atem die Hände über den Kopf heben und wieder senken; dabei den Wurzelverschluss (Mulbandh) bei Ein- und Ausatmung setzen. Dreimal wiederholen. Öffnet Schultern und Hals.', w: 'Bei Schulter- oder Nackenproblemen ohne Verschluss und mit tieferen Armen üben.', src: 'Eigene Ergänzung (Recherche: Shakta Kaur; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['sitzen']} });
N({ id: 'schulterzucken', n: 'Schulterzucken', sa: 'Shoulder Shrugs', c: 'mobi_sitz', lv: 1, m: 1, pose: 'sit', t: 'schulter nacken loslassen atem', x: '', st: 'kund', d: 'Im Leichten Sitz die Schultern beim Einatmen zu den Ohren ziehen und beim Ausatmen locker fallen lassen. Weniger als 2 Minuten; zum Schluss die Schultern oben etwa 15 Sekunden halten und dann lösen. Löst Spannung in Schultern und Nacken.', src: 'Eigene Ergänzung (Recherche: Shakta Kaur; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['sitzen']} });
N({ id: 'brustdehnung', n: 'Brustdehnung (Hände hinter dem Nacken)', sa: 'Chest Stretch', c: 'mobi_sitz', lv: 1, m: 3, pose: 'sit', t: 'herz schulter atem', x: 'schulter nacken', st: 'kund', d: 'Im Leichten Sitz mit langem Rücken die Finger hinter dem Nacken verschränken und die Ellbogen weit zur Seite öffnen. Lange, tiefe, vollständige Atemzüge, etwa 3 Minuten. Zum Schluss einatmen und kurz halten. Öffnet den Brustkorb.', w: 'Bei Schulter- oder Nackenproblemen die Hände höher legen oder kürzer üben.', src: 'Eigene Ergänzung (Recherche: Shakta Kaur; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['sitzen']} });
N({ id: 'sat_kriya', n: 'Sat Kriya', sa: 'Sat Kriya', c: 'boden', lv: 2, m: 3, pose: 'hero', t: 'energie kraft wurzel mantra bauch', x: 'knie fuss blutdruck schwindel osteoporose', man: true, st: 'kund', d: 'Auf den Fersen sitzen, Arme gestreckt über den Kopf, Handflächen zusammen, Finger verschränkt, Zeigefinger zeigen nach oben (Männer: rechter Daumen über linkem, Frauen umgekehrt). Mit „Sat“ den Nabelpunkt kräftig nach innen ziehen, mit „Nam“ loslassen, im Rhythmus des Mantras. Zum Schluss einatmen, ausatmen und den Wurzelverschluss setzen, dann ruhen. Traditionelle Ziele sind 3, 11 oder 31 Minuten; Anfänger sollen die Dauer deutlich kürzen und länger ruhen. Kinn leicht einziehen.', w: 'Nicht in Schwangerschaft und Menstruation; bei Knie-, Herz-, Kreislaufproblemen oder Schwindel vorher klären; Zeiten langsam aufbauen.', src: 'Eigene Ergänzung (Recherche: Shakta Kaur, International Yoga Conference; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['sitzen','knien']} });
N({ id: 'frosch_kundalini', n: 'Frosch (Kundalini)', sa: 'Frog Pose', c: 'kraft', lv: 2, m: 2, pose: 'squat', t: 'kraft energie wurzel', x: 'knie fuss huefte blutdruck schwindel osteoporose', man: true, st: 'kund', d: 'Hocke mit zusammen stehenden Fersen (Fersen gehoben), Fingerspitzen am Boden zwischen den Füßen. Beim Einatmen das Gesäß heben und den Kopf Richtung Knie, Beine strecken; beim Ausatmen zurück in die Hocke. Üblich sind 26 oder 54 Wiederholungen, Anfänger weniger. Blick im Absenken nach vorn.', w: 'Bei Knie-, Fuß- oder Hüftproblemen, Schwindel oder Bluthochdruck nicht oder nur ein paar langsame Wiederholungen.', src: 'Eigene Ergänzung (Recherche: Shakta Kaur, International Yoga Conference; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['stehen']} });
N({ id: 'stretch_pose', n: 'Stretch Pose', sa: 'Stretch Pose', c: 'kraft', lv: 2, m: 1, pose: 'supine_bent', t: 'bauch kraft energie atem', x: 'ruecken nacken blutdruck schwindel osteoporose', man: true, st: 'kund', d: 'In Rückenlage Kopf, Schultern und Fersen etwa 15 Zentimeter anheben, Arme gestreckt neben den Oberschenkeln, Blick auf die Zehen, dazu Feueratem. Anfänger beginnen mit etwa 30 Sekunden. Kräftigt Bauch und Körpermitte.', w: 'Bei Rückenproblemen die Knie beugen oder eine Ferse unten lassen; Feueratem: nicht in Schwangerschaft und Menstruation, bei Herz-, Kreislauf-, Atemwegsproblemen oder Schwindel vorher klären.', src: 'Eigene Ergänzung (Recherche: International Yoga Conference; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['liegen']} });
N({ id: 'kundalini_archer', n: 'Bogenschütze (Kundalini)', sa: 'Archer Pose', c: 'stand', lv: 2, m: 2, pose: 'lunge', t: 'kraft huefte energie', x: 'knie schulter', man: true, st: 'kund', d: 'Stehender Ausfallschritt: Das vordere Knie ist gebeugt und zeigt über den Fuß, das hintere Bein bleibt gestreckt. Die vordere Hand bildet eine Faust (Daumen oben) und zeigt nach vorn, die andere Hand zieht wie eine Bogensehne zur Schulter zurück, der Blick bleibt fest auf der vorderen Faust. Kräftigt Beine und Arme, fördert Ausdauer und Konzentration. Seitenwechsel.', w: 'Bei Knie- oder Schulterproblemen den Ausfallschritt klein halten.', src: 'Eigene Ergänzung (Recherche: International Yoga Conference; Handhaltung aus der Sicht von Quellen nur knapp beschrieben, bitte prüfen; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['stehen']} });
N({ id: 'ego_eradicator', n: 'Ego Eradicator', sa: 'Ego Eradicator', c: 'boden', lv: 2, m: 3, pose: 'sit', t: 'energie kraft atem', x: 'schulter blutdruck schwindel osteoporose', man: true, st: 'kund', d: 'Im Leichten Sitz die Arme in einem Winkel von etwa 60 Grad nach oben strecken, Fingerspitzen auf die Handballen (Fingerpads) eingerollt, Daumen zeigen nach oben. Dazu Feueratem. Dauer anfangs kurz halten (etwa 1 bis 3 Minuten), zum Schluss einatmen, Arme hoch, ausatmen und lösen.', w: 'Feueratem: nicht in Schwangerschaft und Menstruation; bei Herz-, Kreislauf-, Atemwegsproblemen oder Schwindel vorher ärztlich klären; bei Benommenheit sofort aufhören.', src: 'Eigene Ergänzung (Recherche: International Yoga Conference; Originalquelle: Kundalini-Yoga-Handbücher nach Yogi Bhajan, nicht eingesehen)', kat: {'pos':['sitzen']} });
