/* Ergänzende Übungen für den Katalog (Haltungen, die bisher weder als Übung noch als Strichmännchen vorhanden waren).
   Die Beschreibungen sind eigene, knappe Zusammenfassungen. Sanskrit-Namen sind Standardbezeichnungen (im Skript nicht belegt).
   man = nur manuell wählbar (wird vom Generator nicht automatisch vorgeschlagen).
   FIG_KAT = Haltung/Bewegungsrichtung je Übung (wird in kategorien.js als Feinkorrektur übernommen). */
const FIG_KAT = {};
function N(o) {
  const kat = o.kat; delete o.kat;
  const e = Object.assign({
    s: 0, m: 1.5, e: '', h: '', sv: false, man: false, script: false, st: ['hatha'], d: '', w: '', sa: '', src: 'Eigene Ergänzung'
  }, o);
  e.t = typeof o.t === 'string' ? o.t.split(' ') : (o.t || []);
  e.x = typeof o.x === 'string' ? (o.x ? o.x.split(' ') : []) : (o.x || []);
  e.st = typeof o.st === 'string' ? o.st.split(' ') : e.st;
  e.o = EX.length;
  EX.push(e);
  if (kat) FIG_KAT[e.id] = kat;
}

// ---------- Stand ----------
N({ id: 'arme_ruecken', n: 'Arme auf dem Rücken (Gebetshände hinten)', sa: 'Paschima Namaskarasana', c: 'stand', lv: 2, m: 1, pose: 'y130a', t: 'schulter herz', x: 'schulter handgelenk', d: 'Im Stand die Handflächen hinter dem Rücken zusammenführen, Brustbein heben; auch als Vorbeuge mit den Armen auf dem Rücken möglich – öffnet Schultern und Brust.', kat: { pos: ['stehen'] } });
N({ id: 'stern', n: 'Fünfzackiger Stern', c: 'stand', lv: 1, m: 1, pose: 'y154', t: 'energie wurzel', d: 'Weiter Stand, Arme diagonal nach oben gestreckt: der Körper bildet einen Stern; weitet Brust und Flanken.', kat: { pos: ['stehen'] } });
N({ id: 'pada_hastasana', n: 'Hände unter die Füße', sa: 'Pada Hastasana', c: 'stand', lv: 1, m: 1, pose: 'y105c', t: 'ruecken loslassen', x: 'ruecken blutdruck schwindel', e: 'vorbeuge', d: 'Vorbeuge im Stand, die Hände unter die Fußsohlen schieben; Knie dürfen gebeugt bleiben – dehnt Rückseite der Beine und Rücken.', kat: { pos: ['stehen'], dir: ['vor'] } });
N({ id: 'leonardo', n: 'Leonardo (weiter Stand, Arme seitlich)', c: 'stand', lv: 1, m: 1, pose: 'y171', t: 'wurzel energie', d: 'Beine weit gegrätscht, Arme seitlich auf Schulterhöhe – stabiler, offener Stand.', kat: { pos: ['stehen'] } });
N({ id: 'uddiyana', n: 'Aufwärts-Bauchverschluss', sa: 'Uddiyana Bandha', c: 'stand', lv: 2, m: 1, pose: 'y153', t: 'atem energie', x: 'blutdruck schwindel', d: 'Nach vollständiger Ausatmung den Bauch nach innen und oben ziehen, Hände auf den Oberschenkeln.', w: 'Nur mit leerem Magen und nach der Ausatmung üben; nicht bei Bluthochdruck, Herzproblemen oder in der Schwangerschaft.', kat: { pos: ['stehen'] } });
N({ id: 'ellenbogen_knie', n: 'Ellenbogen–Knie', c: 'balance', lv: 2, m: 1, pose: 'y175', t: 'balance kraft', x: 'schwindel', d: 'Im Stand Knie und Ellenbogen vor dem Körper zusammenführen: aktiviert den Rumpf und schult das Gleichgewicht.', kat: { pos: ['stehen', 'balance'] } });
N({ id: 'natarajasana', n: 'Tänzer', sa: 'Natarajasana', c: 'balance', lv: 3, m: 1.5, pose: 'y138', t: 'balance herz kraft', x: 'schwindel knie schulter blutdruck ruecken', e: 'baum', d: 'Einbeiniger Stand, das andere Bein nach hinten greifen und gegen die Hand drücken, Brustbein öffnet sich.', kat: { pos: ['stehen', 'balance'], dir: ['rueck'] } });
N({ id: 'standspagat', n: 'Standspagat', sa: 'Urdhva Prasarita Eka Padasana', c: 'balance', lv: 3, m: 1.5, pose: 'y193', t: 'balance huefte', x: 'schwindel ruecken huefte blutdruck knie', d: 'Aus der Vorbeuge ein Bein senkrecht nach oben führen, Hände am Boden oder am Standbein.', kat: { pos: ['stehen', 'balance'], dir: ['vor'] } });
N({ id: 'sprung_vorbereiten', n: 'Sprung vorbereiten', c: 'kraft', lv: 2, m: 1, pose: 'y119', t: 'kraft energie', x: 'knie handgelenk ruecken', man: true, d: 'Tiefe Vorbereitungshaltung mit Händen am Boden, aus der ein Sprung oder Übergang gestartet wird.', kat: { pos: ['stuetz'] } });
N({ id: 'drache', n: 'Verdrehter Drache (Budokon)', c: 'stand', lv: 3, m: 1.5, pose: 'y143', t: 'kraft huefte', x: 'knie huefte ruecken schwindel', man: true, d: 'Dynamischer Übergang aus der Budokon-Praxis mit Drehung und weit geöffneten Armen.', kat: { pos: ['stehen'], dir: ['dreh'] } });
N({ id: 'doppelblock', n: 'Doppelblock (Budokon)', c: 'stand', lv: 2, m: 1, pose: 'y191', t: 'kraft', x: 'knie huefte', man: true, d: 'Tiefer Ausfallschritt mit abwehrenden Armen aus der Budokon-Praxis.', kat: { pos: ['stehen'] } });
N({ id: 'bogenschuetze', n: 'Gedrehter Bogenschütze (Budokon)', sa: 'Parivrtta Akarna Dhanurasana', c: 'stand', lv: 3, m: 1.5, pose: 'y192', t: 'kraft huefte', x: 'knie huefte ruecken schulter', man: true, d: 'Tiefer Ausfallschritt mit Drehung des Oberkörpers, die Arme spannen einen imaginären Bogen.', kat: { pos: ['stehen'], dir: ['dreh'] } });
N({ id: 'kriegerbasis', n: 'Kriegerbasis (Budokon)', c: 'stand', lv: 2, m: 1, pose: 'y251', t: 'kraft wurzel', x: 'knie huefte', man: true, d: 'Tiefe, stabile Ausgangsstellung der Budokon-Folgen.', kat: { pos: ['stehen'] } });

// ---------- Sitzen ----------
N({ id: 'sukhasana', n: 'Leichter Sitz', sa: 'Sukhasana', c: 'boden', lv: 1, m: 1, pose: 'y226a', t: 'ruhe wurzel', x: 'knie huefte', d: 'Bequemer Schneidersitz mit aufrechter Wirbelsäule; Grundhaltung für Atem und Meditation, bei Bedarf auf einem Kissen.', kat: { pos: ['sitzen'] } });
N({ id: 'anjali_mudra', n: 'Añjali Mudra (Gebetshaltung)', sa: 'Anjali Mudra', c: 'boden', lv: 1, m: 1, pose: 'y226b', t: 'herz ruhe', d: 'Im Sitz die Handflächen vor dem Herzen zusammenführen; sammelt und beruhigt.', kat: { pos: ['sitzen'] } });
N({ id: 'dhyana', n: 'Meditationssitz', sa: 'Dhyana', c: 'boden', lv: 1, m: 2, pose: 'y228g', t: 'ruhe', x: 'knie huefte', d: 'Aufrechter Sitz in der Meditationshaltung, Hände ruhen auf den Knien.', kat: { pos: ['sitzen'] } });
N({ id: 'padmasana', n: 'Lotussitz', sa: 'Padmasana', c: 'boden', lv: 3, m: 1.5, pose: 'y228a', t: 'ruhe wurzel huefte', x: 'knie huefte fuss', e: 'sukhasana', d: 'Beide Füße auf den gegenüberliegenden Oberschenkeln, Wirbelsäule aufrecht.', w: 'Nur bei beweglichen Hüften; nie das Knie erzwingen.', kat: { pos: ['sitzen'] } });
N({ id: 'dandasana', n: 'Stock', sa: 'Dandasana', c: 'boden', lv: 1, m: 1, pose: 'y219a', t: 'ruecken wurzel', d: 'Aufrechter Sitz mit gestreckten Beinen, Füße gebeugt, Hände neben dem Becken; richtet die Wirbelsäule auf.', kat: { pos: ['sitzen'] } });
N({ id: 'mahamudra', n: 'Großes Siegel', sa: 'Mahamudra', c: 'boden', lv: 2, m: 1.5, pose: 'y223', t: 'ruecken loslassen', x: 'ruecken blutdruck', d: 'Ein Bein gestreckt, das andere angewinkelt, Vorbeuge zum gestreckten Bein und Fuß greifen.', kat: { pos: ['sitzen'], dir: ['vor'] } });
N({ id: 'marichyasana_1', n: 'Marichi I', sa: 'Marichyasana I', c: 'boden', lv: 2, m: 1.5, pose: 'y242a', t: 'ruecken huefte loslassen', x: 'ruecken huefte', d: 'Ein Bein gestreckt, das andere aufgestellt; Vorbeuge über das gestreckte Bein.', kat: { pos: ['sitzen'], dir: ['vor'] } });
N({ id: 'marichyasana_3', n: 'Marichi III (Drehsitz)', sa: 'Marichyasana III', c: 'boden', lv: 2, m: 1.5, pose: 'y242b', t: 'ruecken huefte loslassen', x: 'ruecken osteoporose', d: 'Ein Bein gestreckt, das andere aufgestellt; Oberkörper zum aufgestellten Bein hindrehen.', kat: { pos: ['sitzen'], dir: ['dreh'] } });
N({ id: 'parivrtta_janu', n: 'Gedrehter Kopf-zum-Knie', sa: 'Parivrtta Janu Sirsasana', c: 'boden', lv: 2, m: 1.5, pose: 'y212b', t: 'ruecken seit loslassen', x: 'ruecken knie osteoporose', e: 'janu', d: 'Sitzende Seitbeuge über das gestreckte Bein mit leichter Drehung in der Brustwirbelsäule.', kat: { pos: ['sitzen'], dir: ['seit', 'dreh'] } });
N({ id: 'kompass', n: 'Kompass', sa: 'Parivrtta Surya Yantrasana', c: 'boden', lv: 3, m: 1.5, pose: 'y229', t: 'huefte schulter', x: 'huefte ruecken schulter knie', d: 'Ein Bein über die Schulter legen und den Oberkörper in die Gegenrichtung strecken.', kat: { pos: ['sitzen'], dir: ['seit'] } });
N({ id: 'supta_kurmasana', n: 'Liegende Schildkröte', sa: 'Supta Kurmasana', c: 'boden', lv: 3, m: 1.5, pose: 'y202b', t: 'huefte ruecken loslassen', x: 'ruecken huefte knie nacken', d: 'Tiefe Vorbeuge, die Beine liegen über den Schultern, die Hände verschränken sich hinter dem Rücken.', kat: { pos: ['sitzen'], dir: ['vor'] } });
N({ id: 'drop_stance', n: 'Drop Stance (Budokon)', c: 'boden', lv: 2, m: 1, pose: 'y250', t: 'kraft huefte', x: 'knie huefte', man: true, d: 'Tiefes Absenken ins Gleichgewicht zwischen Sitz und Ausfallschritt aus der Budokon-Praxis.', kat: { pos: ['sitzen'] } });
N({ id: 'einbeiniger_durchsitz', n: 'Einbeiniger Durchsitz (Budokon)', c: 'boden', lv: 2, m: 1, pose: 'y212', t: 'huefte loslassen', x: 'huefte knie', man: true, d: 'Aus dem Sitz ein Bein unter dem anderen durchführen und die Hüfte öffnen.', kat: { pos: ['sitzen'] } });

// ---------- Knien / Vierfüßler ----------
N({ id: 'vierfuessler', n: 'Vierfüßlerstand', sa: 'Bharmanasana', c: 'boden', lv: 1, m: 1, pose: 'y314', t: 'ruecken wurzel', x: 'handgelenk knie', d: 'Hände unter den Schultern, Knie unter den Hüften; neutrale Wirbelsäule als Ausgangsposition vieler Übungen.', kat: { pos: ['knien'] } });
N({ id: 'akarna_dhanu', n: 'Bogen und Pfeil', sa: 'Akarna Dhanurasana', c: 'boden', lv: 2, m: 1.5, pose: 'y329', t: 'huefte schulter', x: 'huefte knie', d: 'Im Sitz ein Fuß wie eine Bogensehne zum Ohr führen, das andere Bein bleibt gestreckt.', kat: { pos: ['sitzen'] } });
N({ id: 'agni_sara', n: 'Feuerreinigung (Atemübung)', sa: 'Agni Sara', c: 'boden', lv: 1, m: 1.5, pose: 'y327', t: 'atem energie', x: 'blutdruck', d: 'Nach der Ausatmung den Bauch rhythmisch nach innen ziehen und loslassen; belebt den Bauchraum.', w: 'Nur mit leerem Magen; nicht in der Schwangerschaft oder bei Bluthochdruck.', kat: { pos: ['knien'] } });
N({ id: 'parighasana', n: 'Querbalken', sa: 'Parighasana', c: 'boden', lv: 1, m: 1.5, pose: 'y309a', t: 'seit huefte', x: 'knie', d: 'Aus dem Kniestand ein Bein seitlich strecken und mit dem Oberkörper zur Seite beugen – dehnt Flanke und Oberschenkel.', kat: { pos: ['knien'], dir: ['seit'] } });
N({ id: 'sasangasana', n: 'Hase', sa: 'Sasangasana', c: 'boden', lv: 2, m: 1.5, pose: 'y332', t: 'ruecken nacken loslassen', x: 'nacken knie blutdruck osteoporose', d: 'Aus der Kindhaltung die Hüfte anheben und den Scheitel Richtung Boden führen; dehnt den ganzen Rücken.', w: 'Gewicht nicht auf den Kopf legen; bei Nackenproblemen weglassen.', kat: { pos: ['knien'], dir: ['vor'] } });

// ---------- Rückenlage ----------
N({ id: 'karnapidasana', n: 'Ohrdruck-Haltung', sa: 'Karnapidasana', c: 'boden', lv: 3, m: 1.5, pose: 'y407', t: 'ruecken loslassen ruhe', x: 'nacken ruecken blutdruck osteoporose', d: 'Aus dem Pflug die Knie neben die Ohren sinken lassen; tiefe, beruhigende Dehnung des Rückens.', kat: { pos: ['umkehr'], dir: ['vor'] } });
N({ id: 'supta_konasana', n: 'Liegende Grätsche', sa: 'Supta Konasana', c: 'boden', lv: 3, m: 1.5, pose: 'y433', t: 'huefte ruecken', x: 'ruecken nacken blutdruck', d: 'Aus der Rückenlage die gestreckten Beine über den Kopf führen und seitlich spreizen.', kat: { pos: ['liegen'] } });
N({ id: 'anantasana', n: 'Ruhender Vishnu', sa: 'Anantasana', c: 'boden', lv: 2, m: 1.5, pose: 'y402', t: 'huefte balance', x: 'schulter huefte', d: 'Seitlage, der obere Fuß wird mit der Hand gegriffen und das Bein senkrecht gestreckt.', kat: { pos: ['liegen'], dir: ['seit'] } });
N({ id: 'tisch_vier', n: 'Umgekehrter Tisch', sa: 'Chatus Pada Pitham', c: 'kraft', lv: 2, m: 1, pose: 'y424', t: 'kraft herz schulter', x: 'handgelenk schulter nacken', d: 'Auf dem Rücken die Hüfte anheben, Hände und Füße am Boden: Rumpf und Oberschenkel bilden eine waagerechte Tischplatte.', kat: { pos: ['stuetz'], dir: ['rueck'] } });
N({ id: 'purvottanasana', n: 'Umgekehrte Planke', sa: 'Purvottanasana', c: 'kraft', lv: 2, m: 1, pose: 'y607a', t: 'kraft herz schulter', x: 'handgelenk schulter nacken', e: 'tisch_vier', d: 'Im Sitz die Hüfte anheben, Körper bildet eine schräge Linie, Brust öffnet sich.', kat: { pos: ['stuetz'], dir: ['rueck'] } });
N({ id: 'kancho_drehung', n: 'Kanchos Drehung (Budokon)', c: 'boden', lv: 2, m: 1, pose: 'y425c', t: 'ruecken loslassen', x: 'osteoporose', man: true, d: 'Liegende Drehung aus der Budokon-Praxis.', kat: { pos: ['liegen'], dir: ['dreh'] } });

// ---------- Bauchlage ----------
N({ id: 'ashtanga_namaskara', n: 'Gruß mit acht Gliedern', sa: 'Ashtanga Namaskara', c: 'kraft', lv: 2, m: 1, pose: 'y529', t: 'kraft', x: 'handgelenk schulter', d: 'Knie, Brust und Kinn sowie beide Hände und Füße berühren den Boden, die Hüfte bleibt oben; Übergang im Sonnengruß.', kat: { pos: ['stuetz'] } });
N({ id: 'sarpasana', n: 'Klapperschlange', sa: 'Sarpasana', c: 'boden', lv: 3, m: 1.5, pose: 'y528', t: 'ruecken kraft', x: 'ruecken nacken schulter', d: 'Bauchlage, Hände hinter dem Rücken verschränkt, Brust und Beine heben sich vom Boden.', kat: { pos: ['liegen'], dir: ['rueck'] } });
N({ id: 'bauchlage', n: 'Bauchlage', c: 'boden', lv: 1, m: 1, pose: 'y515a', t: 'ruhe loslassen', d: 'Entspannte Bauchlage, Kopf zur Seite oder auf den Händen; Ausgleich nach Rückbeugen.', kat: { pos: ['liegen'] } });
N({ id: 'vogel', n: 'Vogel', c: 'boden', lv: 1, m: 1, pose: 'y524', t: 'ruecken kraft', x: 'ruecken', d: 'In Bauchlage gegenüberliegenden Arm und Bein anheben; kräftigt den Rücken.', kat: { pos: ['liegen'], dir: ['rueck'] } });

// ---------- Stütz- und Armbalancen ----------
N({ id: 'bakasana', n: 'Kranich', sa: 'Bakasana', c: 'balance', lv: 3, m: 1, pose: 'y605e', t: 'balance kraft', x: 'handgelenk schulter schwindel', d: 'Aus der Hocke die Knie hoch an die Oberarme führen und das Gewicht auf die Hände verlagern.', kat: { pos: ['stuetz', 'balance'] } });
N({ id: 'delfin', n: 'Delfin', sa: 'Ardha Pincha Mayurasana', c: 'kraft', lv: 2, m: 1, pose: 'y619f', t: 'kraft schulter', x: 'schulter nacken blutdruck', d: 'Wie der Herabschauende Hund, aber auf den Unterarmen; kräftigt Schultern und dehnt die Rückseite der Beine.', kat: { pos: ['umkehr'], dir: ['vor'] } });
N({ id: 'tittibhasana', n: 'Glühwürmchen', sa: 'Tittibhasana', c: 'balance', lv: 3, m: 1, pose: 'y637', t: 'balance kraft huefte', x: 'handgelenk schulter huefte schwindel', d: 'Die Beine liegen über den Oberarmen und werden nach vorn gestreckt, das Becken schwebt über dem Boden.', kat: { pos: ['stuetz', 'balance'] } });
N({ id: 'mayurasana', n: 'Pfau', sa: 'Mayurasana', c: 'balance', lv: 3, m: 1, pose: 'y620', t: 'balance kraft bauch', x: 'handgelenk blutdruck schulter', d: 'Ellbogen im Bauch gestützt, der Körper wird waagerecht vom Boden gehoben.', kat: { pos: ['stuetz', 'balance'] } });
N({ id: 'tolasana', n: 'Waage', sa: 'Tolasana', c: 'balance', lv: 2, m: 1, pose: 'y610a', t: 'kraft balance', x: 'handgelenk schulter', d: 'Im Sitz die Hände neben die Hüften stützen und den Körper vom Boden anheben.', kat: { pos: ['stuetz', 'balance'] } });
N({ id: 'parsva_kakasana', n: 'Seitliche Krähe', sa: 'Parsva Kakasana', c: 'balance', lv: 3, m: 1, pose: 'y605b', t: 'balance kraft dreh', x: 'handgelenk schulter schwindel', d: 'Aus einer Drehung beide Knie seitlich auf einen Oberarm legen und auf den Händen balancieren.', kat: { pos: ['stuetz', 'balance'], dir: ['dreh'] } });
N({ id: 'schimpanse', n: 'Schimpanse (Budokon)', c: 'kraft', lv: 2, m: 1, pose: 'y646b', t: 'kraft', x: 'handgelenk knie', man: true, d: 'Tiefe Hocke mit Stütz auf den Händen aus der Budokon-Praxis.', kat: { pos: ['stuetz'] } });
N({ id: 'gorilla', n: 'Gorilla (Budokon)', c: 'kraft', lv: 2, m: 1, pose: 'y646c', t: 'kraft huefte', x: 'knie huefte', man: true, d: 'Weite, tiefe Hocke mit hängenden Armen aus der Budokon-Praxis.', kat: { pos: ['stehen'] } });
N({ id: 'affe_budokon', n: 'Affe (Budokon)', c: 'kraft', lv: 2, m: 1, pose: 'y646a', t: 'kraft', x: 'handgelenk knie', man: true, d: 'Gehen auf Händen und Füßen mit hoher Hüfte aus der Budokon-Praxis.', kat: { pos: ['stuetz'] } });
N({ id: 'sprung_budokon', n: 'Sprung (Budokon)', c: 'kraft', lv: 3, m: 1, pose: 'y606', t: 'kraft energie', x: 'knie handgelenk schulter schwindel', man: true, d: 'Sprung über die Hände in den Stütz aus der Budokon-Praxis.', kat: { pos: ['stuetz'] } });
N({ id: 'fallender_krieger', n: 'Fallender Krieger (Budokon)', c: 'kraft', lv: 3, m: 1, pose: 'y615j', t: 'kraft balance', x: 'knie handgelenk schulter', man: true, d: 'Aus dem Stütz ein Bein nach hinten anheben und seitlich absenken (Budokon).', kat: { pos: ['stuetz'] } });
N({ id: 'kriegerbruecke', n: 'Kriegerbrücke (Budokon)', c: 'kraft', lv: 3, m: 1, pose: 'y607c', t: 'kraft herz', x: 'handgelenk schulter nacken', man: true, d: 'Umgekehrter Stütz mit angehobener Hüfte aus der Budokon-Praxis.', kat: { pos: ['stuetz'], dir: ['rueck'] } });

// ---- weitere Haltungen ----
N({ id: 'siddhasana', n: 'Vollendeter Sitz', sa: 'Siddhasana', c: 'boden', lv: 1, m: 1.5, pose: 'z1', t: 'ruhe wurzel', x: 'knie huefte', d: 'Aufrechter Meditationssitz, eine Ferse am Damm, die andere davor; Hände ruhen auf den Knien.', kat: {'pos':['sitzen']} });
N({ id: 'attitude', n: 'Attitude', c: 'balance', lv: 2, m: 1, pose: 'z3', t: 'balance huefte', x: 'schwindel knie', man: true, d: 'Einbeiniger Stand, das andere Bein angewinkelt nach hinten angehoben, ein Arm streckt sich nach oben (Tanzhaltung).', kat: {'pos':['stehen','balance']} });
N({ id: 'swastikasana', n: 'Glückssitz', sa: 'Swastikasana', c: 'boden', lv: 1, m: 1.5, pose: 'z4', t: 'ruhe wurzel', x: 'knie huefte', d: 'Sitz mit überkreuzten Beinen, die Füße liegen zwischen Oberschenkel und Wade; aufrechter Rücken.', kat: {'pos':['sitzen']} });
N({ id: 'tisch_knie_nase', n: 'Balancierender Tisch – Knie zur Nase', sa: 'Dandayamana Bharmanasana Knee To Nose', c: 'kraft', lv: 1, m: 1, pose: 'z6', t: 'kraft balance bauch', x: 'handgelenk knie', d: 'Aus dem Vierfüßlerstand ein Bein nach hinten strecken, dann Knie und Stirn unter dem Körper zusammenführen.', kat: {'pos':['knien']} });
N({ id: 'bananasana', n: 'Banane', sa: 'Bananasana', c: 'boden', lv: 1, m: 1.5, pose: 'z7', t: 'seit loslassen ruhe', x: 'nacken', d: 'Rückenlage, Arme und Beine wandern in einem Bogen zur Seite – dehnt die ganze Flanke.', kat: {'pos':['liegen'],'dir':['seit']} });
N({ id: 'bharadvajasana', n: 'Bharadvaja-Drehsitz', sa: 'Bharadvajasana', c: 'boden', lv: 2, m: 1.5, pose: 'z8', t: 'ruecken loslassen', x: 'ruecken knie osteoporose', d: 'Sitz mit den Füßen seitlich neben dem Gesäß, Oberkörper dreht sich aufrecht zur Seite.', kat: {'pos':['sitzen'],'dir':['dreh']} });
N({ id: 'padangusthasana', n: 'Große-Zehen-Vorbeuge', sa: 'Padangusthasana', c: 'stand', lv: 1, m: 1, pose: 'z9', t: 'ruecken loslassen', x: 'ruecken blutdruck schwindel', d: 'Vorbeuge im Stand, die Finger umgreifen die großen Zehen; Knie dürfen gebeugt bleiben.', kat: {'pos':['stehen'],'dir':['vor']} });
N({ id: 'stuhl_zehenspitzen', n: 'Stuhl auf Zehenspitzen', sa: 'Utkatasana on Tiptoes', c: 'kraft', lv: 2, m: 1, pose: 'z19', t: 'kraft balance', x: 'knie schwindel fuss', d: 'Stuhlhaltung mit angehobenen Fersen, Arme nach oben – kräftigt Beine und schult das Gleichgewicht.', kat: {'pos':['stehen']} });
N({ id: 'kinnstand', n: 'Kinnstand', sa: 'Ganda Bherundasana', c: 'balance', lv: 3, m: 1, pose: 'z22', t: 'balance kraft', x: 'nacken ruecken schwindel blutdruck', man: true, d: 'In Bauchlage das Kinn auf den Boden stützen und die Beine senkrecht nach oben führen.', kat: {'pos':['stuetz','balance']} });
N({ id: 'fuss_hinter_kopf', n: 'Fuß hinter dem Kopf', sa: 'Eka Pada Sirsasana', c: 'boden', lv: 3, m: 1.5, pose: 'z24', t: 'huefte loslassen', x: 'huefte knie ruecken nacken', d: 'Im Sitz ein Bein hinter Schulter und Kopf legen – sehr tiefe Hüftöffnung.', kat: {'pos':['sitzen']} });
N({ id: 'totenstellung', n: 'Totenstellung', sa: 'Savasana', c: 'boden', lv: 1, m: 3, pose: 'z25', t: 'ruhe loslassen', d: 'Entspannte Rückenlage mit leicht geöffneten Armen und Beinen zum Nachspüren am Ende der Stunde.', kat: {'pos':['liegen']} });
N({ id: 'developpe', n: 'Développé', c: 'balance', lv: 2, m: 1, pose: 'z30', t: 'balance huefte', x: 'schwindel knie huefte', man: true, d: 'Einbeiniger Stand, das andere Knie hochziehen und das Bein nach vorn strecken (Tanzbewegung).', kat: {'pos':['stehen','balance']} });
N({ id: 'doppelte_zehenhaltung', n: 'Doppelte Große-Zehen-Haltung', sa: 'Ubhaya Padangusthasana', c: 'kraft', lv: 2, m: 1, pose: 'z32', t: 'kraft balance bauch', x: 'ruecken knie', d: 'Auf dem Gesäß balancieren, beide Beine gestreckt nach oben, Hände fassen die großen Zehen.', kat: {'pos':['sitzen']} });
N({ id: 'hund_knie_nase', n: 'Herabschauender Hund – Knie zur Nase', sa: 'Adho Mukha Svanasana Knee To Nose', c: 'kraft', lv: 2, m: 1, pose: 'z35', t: 'kraft bauch', x: 'handgelenk schulter blutdruck', d: 'Aus dem Herabschauenden Hund ein Bein anheben und das Knie unter dem Körper zur Nase führen.', kat: {'pos':['stuetz']} });
N({ id: 'drachenhocke', n: 'Drachenhocke', sa: 'Dragon Squat', c: 'stand', lv: 2, m: 1, pose: 'z36', t: 'huefte kraft', x: 'knie huefte', d: 'Tiefer Ausfallschritt mit einer Hand am Boden, der Arm der anderen Seite öffnet sich nach oben.', kat: {'pos':['stehen']} });
N({ id: 'astavakrasana', n: 'Acht-Winkel-Haltung', sa: 'Astavakrasana', c: 'balance', lv: 3, m: 1, pose: 'z41', t: 'balance kraft', x: 'handgelenk schulter huefte', d: 'Die Beine über einen Oberarm legen und seitlich nach vorn strecken, das Becken schwebt über dem Boden.', kat: {'pos':['stuetz','balance']} });
N({ id: 'elefantenruessel', n: 'Elefantenrüssel', sa: 'Eka Hasta Bhujasana', c: 'balance', lv: 3, m: 1, pose: 'z42', t: 'balance kraft', x: 'handgelenk schulter huefte', d: 'Ein Bein über den Oberarm legen, das Gewicht auf die Hände verlagern und das andere Bein nach vorn strecken.', kat: {'pos':['stuetz','balance']} });
N({ id: 'gefallenes_dreieck', n: 'Gefallenes Dreieck', sa: 'Patita Tarasana', c: 'kraft', lv: 3, m: 1, pose: 'z46', t: 'kraft herz', x: 'handgelenk schulter', man: true, d: 'Aus dem Seitstütz ein Bein nach hinten absenken und die Brust öffnen.', kat: {'pos':['stuetz'],'dir':['rueck']} });
N({ id: 'fliegende_streckung', n: 'Fliegende Streckung', sa: 'Flying Extended', c: 'kraft', lv: 3, m: 1, pose: 'z50', t: 'kraft balance', x: 'handgelenk schulter knie', man: true, d: 'Dynamischer Übergang im Stütz mit weit ausgestrecktem Bein.', kat: {'pos':['stuetz']} });
N({ id: 'fliegende_planke', n: 'Fliegende Planke', sa: 'Flying Plank', c: 'kraft', lv: 3, m: 1, pose: 'z52', t: 'kraft balance', x: 'handgelenk schulter', man: true, d: 'Planke mit angehobenem Bein und einem seitlich ausgestreckten Arm.', kat: {'pos':['stuetz']} });
N({ id: 'fliegender_spagat', n: 'Fliegender Spagat', sa: 'Eka Pada Koundinyasana', c: 'balance', lv: 3, m: 1, pose: 'z53', t: 'balance kraft huefte', x: 'handgelenk schulter huefte', d: 'Armbalance, ein Bein über den Oberarm, das andere gestreckt nach hinten.', kat: {'pos':['stuetz','balance']} });
N({ id: 'fliegender_krieger', n: 'Fliegender Krieger', sa: 'Flying Warrior', c: 'balance', lv: 3, m: 1, pose: 'z54', t: 'balance kraft', x: 'schwindel knie', man: true, d: 'Einbeiniger Stand mit nach hinten gestrecktem Bein und weit geöffneten Armen.', kat: {'pos':['stehen','balance']} });
N({ id: 'fliegendes_wild_thing', n: 'Fliegendes Wild Thing', sa: 'Flying Wild Thing', c: 'kraft', lv: 3, m: 1, pose: 'z55', t: 'kraft herz', x: 'handgelenk schulter', man: true, d: 'Dynamische Variante des Wild Thing mit angehobenem Bein.', kat: {'pos':['stuetz'],'dir':['rueck']} });
N({ id: 'unterarmplanke', n: 'Unterarmplanke', sa: 'Phalakasana Variation', c: 'kraft', lv: 2, m: 1, pose: 'z56', t: 'kraft bauch', x: 'schulter nacken', d: 'Planke auf den Unterarmen – kräftigt Rumpf und Schultern.', kat: {'pos':['stuetz']} });
N({ id: 'vorbeuge_haende_verschraenkt', n: 'Vorbeuge mit verschränkten Händen', sa: 'Uttanasana with interlocked hands', c: 'stand', lv: 1, m: 1, pose: 'z58', t: 'schulter ruecken loslassen', x: 'ruecken blutdruck schwindel', d: 'Vorbeuge im Stand, die Hände hinter dem Rücken verschränkt und nach oben geführt – öffnet Brust und Schultern.', kat: {'pos':['stehen'],'dir':['vor']} });
N({ id: 'frosch', n: 'Frosch', sa: 'Bhekasana', c: 'boden', lv: 2, m: 1.5, pose: 'z59', t: 'ruecken huefte', x: 'knie ruecken', d: 'Bauchlage, ein Fuß wird zum Gesäß gezogen und mit der Hand gehalten.', kat: {'pos':['liegen'],'dir':['rueck']} });
N({ id: 'halbes_boot', n: 'Halbes Boot', sa: 'Ardha Navasana', c: 'kraft', lv: 2, m: 1, pose: 'z65', t: 'kraft bauch', x: 'ruecken blutdruck', d: 'Beine und Oberkörper schräg angehoben, Arme nach vorn – Bauchkräftigung.', kat: {'pos':['sitzen']} });
N({ id: 'halblotus_vorbeuge_sitzend', n: 'Gebundener Halblotus – sitzende Vorbeuge', sa: 'Ardha Baddha Padma Paschimottanasana', c: 'boden', lv: 3, m: 1.5, pose: 'z66', t: 'huefte ruecken loslassen', x: 'knie huefte ruecken', d: 'Ein Fuß liegt im Halblotus, der Arm bindet den Fuß, Vorbeuge über das gestreckte Bein.', kat: {'pos':['sitzen'],'dir':['vor']} });
N({ id: 'halblotus_vorbeuge_stehend', n: 'Gebundener Halblotus – stehende Vorbeuge', sa: 'Ardha Baddha Padma Uttanasana', c: 'balance', lv: 3, m: 1.5, pose: 'z67', t: 'balance huefte', x: 'knie huefte schwindel ruecken', d: 'Einbeinig stehend, ein Fuß im Halblotus gebunden, Vorbeuge nach vorn.', kat: {'pos':['stehen','balance'],'dir':['vor']} });
N({ id: 'halber_bogen', n: 'Halber Bogen', sa: 'Ardha Dhanurasana', c: 'boden', lv: 2, m: 1, pose: 'z68', t: 'ruecken herz', x: 'ruecken nacken', d: 'Bauchlage, ein Bein wird nach hinten gegriffen, der andere Arm streckt sich nach vorn.', kat: {'pos':['liegen'],'dir':['rueck']} });
N({ id: 'reiher', n: 'Reiher', sa: 'Krounchasana', c: 'boden', lv: 3, m: 1.5, pose: 'z77', t: 'huefte ruecken loslassen', x: 'knie huefte ruecken', d: 'Ein Bein angewinkelt, das andere wird gestreckt nach oben zum Gesicht gezogen.', kat: {'pos':['sitzen'],'dir':['vor']} });
N({ id: 'pferdegesicht', n: 'Pferdegesicht', sa: 'Vatayanasana', c: 'balance', lv: 3, m: 1, pose: 'z79', t: 'balance huefte', x: 'knie huefte schwindel', man: true, d: 'Einbeinige Hockhaltung mit überkreuzten Beinen, Arme nach oben.', kat: {'pos':['stehen','balance']} });
N({ id: 'kniende_rueckbeuge', n: 'Kniende Rückbeuge', c: 'boden', lv: 2, m: 1, pose: 'z81', t: 'herz ruecken', x: 'ruecken nacken knie', d: 'Aus dem Kniestand die Arme nach oben führen und die Brust öffnen.', kat: {'pos':['knien'],'dir':['rueck']} });
N({ id: 'ausfallschritt_drehung', n: 'Tiefer Ausfallschritt mit Drehung', sa: 'Parivrtta Anjaneyasana', c: 'stand', lv: 2, m: 1.5, pose: 'z88', t: 'huefte ruecken kraft', x: 'knie ruecken schwindel', d: 'Tiefer Ausfallschritt, Gebetshände vor der Brust, der Oberkörper dreht sich zum vorderen Bein.', kat: {'pos':['stehen'],'dir':['dreh']} });
N({ id: 'matrix_krieger', n: 'Matrix-Krieger', c: 'kraft', lv: 2, m: 1, pose: 'z91', t: 'kraft energie', x: 'knie ruecken', man: true, d: 'Fließende Folge aus Ausfallschritt und weit geöffneten Armen.', kat: {'pos':['stehen']} });
N({ id: 'meerjungfrau', n: 'Meerjungfrau', sa: 'Naginyasana', c: 'boden', lv: 3, m: 1.5, pose: 'z93', t: 'huefte herz', x: 'knie huefte schulter', d: 'Sitz mit seitlich gebeugtem Bein, der hintere Fuß wird mit den Händen über dem Kopf gehalten.', kat: {'pos':['sitzen'],'dir':['rueck']} });
N({ id: 'mini_attitude', n: 'Mini-Attitude', c: 'balance', lv: 2, m: 1, pose: 'z94', t: 'balance huefte', x: 'knie schwindel', man: true, d: 'Tiefer Ausfallschritt mit einem Arm nach oben und dem anderen nach vorn.', kat: {'pos':['stehen','balance']} });
N({ id: 'mini_wild_thing', n: 'Mini Wild Thing', sa: 'Camatkarasana Variation', c: 'kraft', lv: 2, m: 1, pose: 'z95', t: 'herz kraft', x: 'handgelenk schulter', d: 'Vorstufe des Wild Thing: Seitstütz mit gebeugtem Knie und weit geöffnetem Arm.', kat: {'pos':['stuetz'],'dir':['rueck']} });
N({ id: 'pendel', n: 'Pendel', sa: 'Lolasana', c: 'balance', lv: 3, m: 1, pose: 'z104', t: 'balance kraft bauch', x: 'handgelenk schulter', d: 'Aus dem Fersensitz das Gesäß vom Boden heben und den Körper zwischen den Armen pendeln lassen.', kat: {'pos':['stuetz','balance']} });
N({ id: 'taube_rueckbeuge', n: 'Taube – tiefe Rückbeuge', sa: 'Kapotasana', c: 'boden', lv: 3, m: 1, pose: 'z105', t: 'herz ruecken', x: 'ruecken nacken knie schulter', man: true, d: 'Aus dem Kniestand tief nach hinten beugen und die Hände zu den Füßen führen.', kat: {'pos':['knien'],'dir':['rueck']} });
N({ id: 'pistol_roll', n: 'Pistol Roll', c: 'kraft', lv: 3, m: 1, pose: 'z106', t: 'kraft bauch', x: 'knie ruecken', man: true, d: 'Rollbewegung vom Sitz in die Einbeinhocke, die Arme schwingen mit.', kat: {'pos':['sitzen']} });
N({ id: 'pistole_fussgriff', n: 'Pistole mit Fußgriff', sa: 'Eka Pada Malasana Squat', c: 'balance', lv: 3, m: 1, pose: 'z107', t: 'balance kraft huefte', x: 'knie huefte schwindel', d: 'Einbeinige tiefe Hocke, das andere Bein gestreckt nach vorn, Hand am Fuß.', kat: {'pos':['stehen','balance']} });
N({ id: 'regenbogen_krieger', n: 'Regenbogen-Krieger', c: 'stand', lv: 2, m: 1, pose: 'z111', t: 'seit huefte kraft', x: 'knie ruecken', d: 'Ausfallschritt mit seitlicher Beuge, ein Arm bildet einen Bogen über dem Kopf.', kat: {'pos':['stehen'],'dir':['seit']} });
N({ id: 'liegende_zehe', n: 'Liegender Zeh-Griff', sa: 'Supta Padangusthasana', c: 'boden', lv: 1, m: 1.5, pose: 'z113', t: 'huefte loslassen', x: 'huefte', d: 'In Rückenlage ein Bein zur Decke strecken und die große Zehe oder einen Gurt halten.', kat: {'pos':['liegen']} });
N({ id: 'umgekehrter_krieger', n: 'Umgekehrter Krieger', sa: 'Viparita Virabhadrasana', c: 'stand', lv: 2, m: 1, pose: 'z117', t: 'seit huefte kraft', x: 'knie ruecken', d: 'Aus Krieger II den vorderen Arm nach oben führen, der hintere Arm gleitet am Bein entlang.', kat: {'pos':['stehen'],'dir':['seit']} });
N({ id: 'gedrehte_zehenhaltung', n: 'Gedrehte Hand-zum-Fuß-Haltung', sa: 'Parivrtta Utthita Hasta Padangusthasana', c: 'balance', lv: 3, m: 1.5, pose: 'z118', t: 'balance huefte ruecken', x: 'schwindel knie huefte ruecken', d: 'Einbeiniger Stand, das gestreckte Bein wird seitlich gegriffen, der Oberkörper dreht sich.', kat: {'pos':['stehen','balance'],'dir':['dreh']} });
N({ id: 'gedrehte_hocke', n: 'Gedrehte Hocke', sa: 'Parivrtta Malasana', c: 'stand', lv: 2, m: 1, pose: 'z123', t: 'huefte ruecken', x: 'knie huefte', d: 'Tiefe Hocke, ein Ellbogen am Knie, der andere Arm zeigt zur Decke.', kat: {'pos':['stehen'],'dir':['dreh']} });
N({ id: 'ronde', n: 'Ronde', c: 'balance', lv: 2, m: 1, pose: 'z125', t: 'balance huefte', x: 'schwindel knie', man: true, d: 'Tanzbewegung: Das Spielbein beschreibt einen Halbkreis über den Boden.', kat: {'pos':['stehen','balance']} });
N({ id: 'laeufer', n: 'Läufer', c: 'stand', lv: 2, m: 1, pose: 'z126', t: 'kraft huefte', x: 'knie ruecken', d: 'Stand mit gebeugtem Standbein, das andere Bein angewinkelt zurück, Oberkörper leicht vorgeneigt.', kat: {'pos':['stehen']} });
N({ id: 'visvamitrasana', n: 'Visvamitra-Haltung', sa: 'Visvamitrasana', c: 'balance', lv: 3, m: 1, pose: 'z128', t: 'balance huefte kraft', x: 'handgelenk schulter huefte', d: 'Armbalance, ein Bein über der Schulter, das andere gestreckt zur Seite, Blick zur Hand.', kat: {'pos':['stuetz','balance']} });
N({ id: 'schulterdruck', n: 'Schulterdruck-Haltung', sa: 'Bhujapidasana', c: 'balance', lv: 3, m: 1, pose: 'z132', t: 'balance kraft', x: 'handgelenk schulter huefte', d: 'Die Oberschenkel liegen auf den Oberarmen, die Füße heben sich vom Boden.', kat: {'pos':['stuetz','balance']} });
N({ id: 'skating', n: 'Skating', c: 'kraft', lv: 2, m: 1, pose: 'z136', t: 'kraft energie', x: 'knie huefte', man: true, d: 'Dynamischer seitlicher Ausfallschritt wie beim Schlittschuhlaufen.', kat: {'pos':['stehen']} });
N({ id: 'gleitende_planke', n: 'Gleitende Planke', sa: 'Slide Plank', c: 'kraft', lv: 3, m: 1, pose: 'z137', t: 'kraft', x: 'handgelenk schulter', man: true, d: 'Seitstütz, bei dem das obere Bein vor und zurück gleitet.', kat: {'pos':['stuetz']} });
N({ id: 'rueckbeuge_haende_verschraenkt', n: 'Stehende Rückbeuge mit verschränkten Händen', sa: 'Anuvittasana with interlocked hands', c: 'stand', lv: 2, m: 1, pose: 'z142', t: 'herz schulter', x: 'ruecken nacken schwindel', d: 'Hände hinter dem Rücken verschränken, Brust öffnen und den Oberkörper leicht nach hinten neigen.', kat: {'pos':['stehen'],'dir':['rueck']} });
N({ id: 'stehende_umarmung', n: 'Stehende Umarmung', c: 'stand', lv: 1, m: 1, pose: 'z144', t: 'ruhe herz', d: 'Im Stand die Arme über der Brust kreuzen und sich selbst umarmen.', kat: {'pos':['stehen']} });
N({ id: 'superwoman', n: 'Superwoman / Superman', c: 'kraft', lv: 1, m: 1, pose: 'z150', t: 'ruecken kraft', x: 'ruecken', d: 'Aus dem Vierfüßlerstand oder der Bauchlage Arm und gegenüberliegendes Bein strecken und heben.', kat: {'pos':['liegen'],'dir':['rueck']} });
N({ id: 'dreibeiniger_hund', n: 'Dreibeiniger Hund', sa: 'Tri Pada Adho Mukha Svanasana', c: 'kraft', lv: 2, m: 1, pose: 'z156', t: 'kraft huefte', x: 'handgelenk schulter blutdruck', d: 'Herabschauender Hund, ein Bein senkrecht nach oben gestreckt.', kat: {'pos':['stuetz']} });
N({ id: 'dreibeiniger_hund_gestapelt', n: 'Dreibeiniger Hund mit gestapelten Knien', sa: 'Tri Pada Adho Mukha Svanasana Variation', c: 'kraft', lv: 3, m: 1, pose: 'z157', t: 'kraft huefte', x: 'handgelenk schulter blutdruck', d: 'Dreibeiniger Hund, das angehobene Knie wird geöffnet und über das Standbein gelegt.', kat: {'pos':['stuetz'],'dir':['dreh']} });
N({ id: 'drei_schritte_spagat', n: 'Drei-Schritte-Spagat', sa: 'Utthita Trivikramasana', c: 'balance', lv: 3, m: 1.5, pose: 'z158', t: 'balance huefte', x: 'schwindel knie huefte', d: 'Einbeiniger Stand, das andere Bein senkrecht nach oben gestreckt, Hände nah am Standbein.', kat: {'pos':['stehen','balance']} });
N({ id: 'zehenbalance', n: 'Zehenbalance', sa: 'Prapadasana', c: 'balance', lv: 3, m: 1, pose: 'z159', t: 'balance wurzel', x: 'schwindel knie fuss', d: 'Tiefe Hocke auf den Zehenspitzen balancieren, Hände vor der Brust.', kat: {'pos':['stehen','balance']} });
N({ id: 'gedrehter_taenzer', n: 'Gedrehter Tänzer', sa: 'Parivrtta Natarajasana', c: 'balance', lv: 3, m: 1.5, pose: 'z163', t: 'balance herz', x: 'schwindel knie schulter ruecken', d: 'Tänzer mit Gegenarm: Das hintere Bein wird mit der gegenüberliegenden Hand gegriffen.', kat: {'pos':['stehen','balance'],'dir':['dreh']} });
N({ id: 'beine_oben', n: 'Beine nach oben gestreckt', sa: 'Urdhva Prasarita Padasana', c: 'kraft', lv: 1, m: 1, pose: 'z165', t: 'bauch kraft', x: 'ruecken', d: 'In Rückenlage beide Beine senkrecht nach oben strecken und langsam wieder senken.', kat: {'pos':['liegen']} });
N({ id: 'sitzende_vorbeuge_oben', n: 'Aufwärts gerichtete sitzende Vorbeuge', sa: 'Urdhva Mukha Paschimottanasana', c: 'kraft', lv: 2, m: 1, pose: 'z167', t: 'kraft ruecken bauch', x: 'ruecken knie', d: 'Im Sitz die Füße greifen und die gestreckten Beine nach oben ziehen (V-Haltung).', kat: {'pos':['sitzen'],'dir':['vor']} });
N({ id: 'weite_graetsche_oben', n: 'Aufwärts gerichtete weite Grätsche', sa: 'Urdhva Upavistha Konasana', c: 'kraft', lv: 2, m: 1, pose: 'z168', t: 'kraft huefte bauch', x: 'ruecken huefte', d: 'Im Sitz beide Beine weit gegrätscht anheben, die Hände fassen die Füße.', kat: {'pos':['sitzen']} });
N({ id: 'wild_thing_vorbereitung', n: 'Wild Thing Vorbereitung', c: 'boden', lv: 2, m: 1, pose: 'z181', t: 'herz huefte', x: 'handgelenk schulter', d: 'Aus dem Sitz mit aufgestelltem Bein den Oberkörper öffnen – Vorstufe zum Wild Thing.', kat: {'pos':['sitzen'],'dir':['rueck']} });
