/* Mantra-Katalog – ausschließlich aus den Lehrgangsskripten (Modul 1, 2, 3, 6, 8) übernommen und gekürzt.
   Felder: n Name · typ · kat (Anlass) · text (Zeilen) · dev (Devanagari) · bed (Bedeutung) · fuer (Zweck laut Skript) · wi (Wirkung/Beschreibung) · an (Anleitung)
           cd (Lied/CD) · mu (Mudra-Hinweis) · mehr ([Überschrift, Text]) · m (Modul) · q (Quelle) */
const MAN_TYP = { Mantra: 'Mantra', 'Bija-Mantra': 'Bija-Mantra (Samenklang)', Gebet: 'Gebet', Meditation: 'Mantra-Meditation', Formel: 'Formel / Sprechsatz' };
const MAN_KAT = { einstimmung: 'Einstimmung / Beginn der Stunde', heilung: 'Heilung', schutz: 'Schutz', frieden: 'Liebe, Frieden & Licht', erfolg: 'Erfolg & Wohlstand', chakra: 'Chakren', pranayama: 'Pranayama / Bewegung', mudra: 'Zu Mudras empfohlen', meditation: 'Meditation', wahrheit: 'Wahrheit & Identität' };

const MANTRA_INTRO = [
  ['Was ist ein Mantra?', 'Ein Mantra ist eine Schwingung, welche die Kraft des Sonnenlichts enthält und den Geist für die unendliche Kraft der Schöpfung öffnet. Es ist eine Klangfolge, die so gestaltet ist, dass sie das Bewusstsein durch Wiederholung bestimmter Schwingungsrhythmen erhebt und verändert. Mantren sind verschlüsselte Klänge, vergleichbar mit einer Telefonnummer; jedes besitzt eine einzigartige Wirkung. Mantren sind mystische Worte und weit wertvoller als die Worte der Alltagssprache. Sie stammen aus drei Quellen: der Intuition, der Wissenschaft und den Planeten.', 'Modul 1, S. 105 · Modul 2, S. 66'],
  ['Wie funktioniert das?', 'Die Wirkung des Mantras hängt mit den Reflexpunkten der Zunge und des Mundes zusammen: Am Gaumen gibt es 84 Druckpunkte. Beim Chanten bewegen sich Mund und Zunge, deutlich artikuliert, und beeinflussen so 84 Meridiane und Druckpunkte. Das regt den Hypothalamus an, sodass Hirnanhangdrüse und Zirbeldrüse einen Nektar (Amrit) ausscheiden. Beim Chanten machen wir „Yoga mit dem Mund“.', 'Modul 2, S. 67'],
  ['Klangarten', 'Bakti: Klang auf der Zungenspitze (hörbare oder gesprochene Töne). Khanth: Klang im Hals, der gedachte Klang (wie beim stillen Lesen). Hardej: Klang im Herzzentrum, die Botschaft aus dem Herzen. Nabhi: Klang am Nabelzentrum, der kraftvollste Klang. Anhatha: der unendliche, nicht angeschlagene Klang, der in der Meditation hörbar wird.', 'Modul 2, S. 68'],
  ['Japa – Wiederholung', 'Alle Mantren sind Japa (Wiederholung): „Ja“ bedeutet Ton, „Pa“ Echo oder Widerhall. Das Mantra wird ins Universum projiziert und kommt als Widerhall zurück. Das erzeugt Tapa, die innerliche spirituelle Hitze des Prana, welche Nerven und Aura erneuert und stärkt.', 'Modul 2, S. 68'],
  ['Wirkung', 'Klang, Resonanz und Rhythmus erschaffen ein verändertes Bewusstsein und neue Gedankenmuster. Ein Mantra umgibt uns mit einer spirituellen Rüstung, die negative Projektionen abhält, und erschafft einen Raum voll positiver göttlicher Gedanken. Mantren spiritualisieren die Gedanken und machen empfänglich für Heilung; das Anhören von Mantren oder heiliger Musik wirkt harmonisierend und inspirierend.', 'Modul 2, S. 68–69'],
  ['Die 8 Gesetze des Klangs', '1. Der Atem ist die Grundlage des Klangs. 2. Schenke jeder Silbe und jedem Vokal dieselbe Aufmerksamkeit und Bedeutung. 3. Achte auf den Rhythmus deines Klangs – Rhythmus bedeutet Ordnung und sorgt für Gesundheit. 4. Bereite dich mental und emotional vor; sei neutral, öffne Herz und Geist und verbinde dich mit dem Kosmos. 5. Erwarte, dass dich die Klänge auf ein weit höheres Bewusstsein einstimmen – diese Arbeit ist heilig, vertraue darauf, dass sie funktioniert. 6. Sei dankbar, dass du diese Heilige Weisheit zur rechten Zeit am rechten Ort empfängst. 7. Empfinde liebevolle und höchste Dankbarkeit gegenüber dem Schöpfer. 8. Durch die Arbeit mit den 8 Gesetzen des Klangs öffnet sich die Tür zum kosmischen Bewusstsein und zu Gott.', 'Modul 2, S. 70'],
  ['Warum 108?', 'Ein Mantra soll 108 Mal wiederholt werden. Erklärungsmodelle: 12 (heilige Zahl) mal 9 (heilige Zahl); 12 Tierkreiszeichen mal 9 Planeten; der Sonnendurchmesser ist 108 Mal so groß wie der Erddurchmesser; der Abstand Sonne–Erde ist ca. 108 Mal der Sonnendurchmesser. Nach der Tantralehre atmen wir täglich rund 21.600 Mal; die Hälfte (10.800) durch 100 geteilt ergibt 108 – die Kraft des Mantras wird hundertfach.', 'Modul 3 (Teil 1), S. 7']
];

const MANTRAS = [
  { id: 'om', n: 'OM (AUM)', typ: 'Bija-Mantra', kat: ['einstimmung', 'chakra', 'meditation'], text: ['Om'], dev: 'ॐ', fuer: 'Basismantra im Yoga',
    wi: ['Om ist das Basismantra im Yoga. Es ist sehr eng mit der Atmung verbunden und soll die Seele vibrieren lassen. In den Upanishaden wurde es zum ersten Mal beschrieben, man sagt ihm mystische Kräfte nach. Es soll Körper, Geist und Seele harmonisieren. Es ist der Urklang der Laute, aus dem laut hinduistischem Glauben das Universum entstanden ist.', 'Es ist ein Ritual, mit dem alle Yogaschüler aus dem stressigen Alltag in das Hier und Jetzt gebracht werden und der Geist klar wird, dass es nun ausschließlich um sie selbst geht. Auf das OM folgt 3 Mal Shanti.'],
    an: 'Gesungen wird es, indem du zuerst tief einatmest, ein O formst und es ausgehend vom Steißbein nach oben singst. Wenn es auf Herzhöhe ist, wechselst du zum M und spürst, wie sich die Vibration weiter nach oben zieht bis zu den Lippen. Atme bis zum Steißbein ein. Es bietet sich an, mit OM eine Yogastunde einzuleiten.',
    mehr: [['Die drei Granthis (A – U – M)', 'Wir haben 6 Chakren und 3 Granthis (Knoten), die jeweils zwei Chakren zusammenfügen und die psychischen Barrieren darstellen: Brahma Granthi (die unteren zwei Chakren) steht für das A – Wissen vs. Kommunikation; Vishnu Granthi (die mittleren) steht für das U – Liebe vs. Wut; Rudra Granthi (die oberen) steht für das M – Begierde/Verlangen vs. Angst. Beim Singen mit dem O oder A im Steißbein starten, das Rückenmark hochziehen und in der Herzregion mit dem M beginnen, bis zum Mund hochvibrieren.'],
      ['Die Bedeutung des Symbols', 'Wachstadium (jagrat): Die Basis des Symbols steht für das nach außen gewandte Bewusstsein, das wir mit den 5 Sinnen wahrnehmen. Traumstadium (svapna): zwischen Tiefschlaf und Wachstadium, das Bewusstsein ist nach innen gerichtet, während die Augen geschlossen sind. Unbewusstsein (taijasa): die Kurve symbolisiert den Tiefschlaf, das Unterbewusstsein ruht komplett. Maya (Illusion): die Illusion der Wirklichkeit steht der höheren spirituellen Erkenntnis im Weg. Turiya – die höchste Erkenntnis: der Punkt an der Spitze symbolisiert das höchste Stadium des Bewusstseins; ein absolut stiller, friedvoller und glückseliger Ort, das Ziel aller spirituellen Aktivität. „Das Mantra und Klangsymbol OM steht für die allumfassende Vibration des Universums.“']],
    m: 'Modul 3', q: 'Modul 3 (Teil 1), S. 5–6, 9' },
  { id: 'shanti', n: 'Shanti, Shanti, Shanti', typ: 'Mantra', kat: ['einstimmung', 'frieden'], text: ['Shanti, Shanti, Shanti'], bed: [['Shanti', 'Frieden']], fuer: 'Abschluss nach einem Mantra oder OM',
    wi: ['Shanti wird nach einem Mantra oder nach einem OM 3 Mal gesungen. Mit dem ersten Shanti sagst du: gib mir die Kraft, keine Probleme zu erschaffen. Mit dem zweiten wendest du dich jemand anderem zu: wenn dein Gegenüber ein Problem hat, soll er die Kraft haben, es nicht zu deinem Problem werden zu lassen. Mit dem dritten drückst du aus, dass auch keine höhere Gewalt bzw. die Natur dir ein Problem verschaffen wird.'],
    m: 'Modul 3', q: 'Modul 3 (Teil 1), S. 9' },
  { id: 'ganesha', n: 'Om Gam Ganapataye Namaha (Ganesha-Mantra)', typ: 'Mantra', kat: ['einstimmung'], text: ['Om Gam Ganapataye Namaha'], dev: 'ॐ गम गणपतये नम',
    bed: [['Om', 'Bija-Mantra, stellt den Urlaut des Kosmos dar'], ['Gam', 'Samenklang für Ganesha bzw. seine Energien'], ['Ganapataye', 'Synonym für Ganesha: Gana = „Scharen“ oder „Diener“, Pati = „Herr“ bzw. „Gebieter“ – Ganesha beherrscht alle guten Kräfte'], ['Namaha', 'so viel wie „so sei es“']], fuer: 'Hindernisse lösen, guter Anfang',
    wi: ['Das Ganesha-Mantra trägt die Bedeutung der Ehrerbietung des Unendlichen und Ewigen. Mit dessen Verehrung besteht die Gelegenheit, mit allen guten Kräften in Kontakt zu kommen und sie durch sich wirken zu lassen; gute Kräfte werden am Werk sein, um Neues mit vollem Herzen anzugehen.', 'Hindernisse (bei Neuanfängen, Projekten, Lebensphasen usw.) können durch das Rezitieren aus dem Weg geräumt, Blockaden gelöst werden. Zum Beginn von Vorträgen, (Verehrungs-)Zeremonien, Rezitationen usw. wird das Ganesha-Mantra gern genutzt, um die guten Kräfte Ganeshas anzurufen.', 'Ein Mantra schwingt in einer bestimmten Art und Weise, sodass es der Urschwingung gleicht. Erfolgt die Konzentration in der Meditation bzw. in der Rezitation auf die einzelnen Mantrasilben, kann es seine Kraft und Wirkung entfalten.'],
    mehr: [['Ganesha', 'Ganesha ist der elefantenköpfige Gott im Hinduismus, Sohn von Shiva und Parvati. Er symbolisiert die Beseitigung aller Hindernisse und steht für einen guten Anfang (Herr über die Hindernisse); vor Beginn einer Reise, eines Rituals oder eines wichtigen Unternehmens wird zuerst Ganesha angerufen.']],
    m: 'Modul 3', q: 'Modul 3 (Teil 1), S. 11–12' },
  { id: 'om108', n: '108 OM (Mala-Meditation)', typ: 'Meditation', kat: ['meditation'], text: ['Om (108 Mal)'], fuer: 'OM-Meditation mit der Mala',
    wi: ['Die 108 begegnet dir im Yoga immer wieder: ein Mantra soll 108 Mal wiederholt werden, damit die Kraft hundertfach wird und der Tag mit der mystischen Kraft gefüllt wird (Erklärungen siehe „Warum 108?“ oben).'],
    an: 'Setze dich aufrecht in den Meditationssitz, beruhige zunächst den Atem mit 10 tiefen, bewussten Atemzügen aus dem Bauch heraus und bringe die Aufmerksamkeit ins Hier und Jetzt. Drei Möglichkeiten: (1) Der Lehrer singt laut OM, die Schüler folgen; abwechselnd insgesamt 107 Wiederholungen, der Lehrer zählt mit einer Mala bis zum 108. OM. (2) Für dich selbst: laut OM singen und mit der Mala die gesungenen OM zählen. (3) Nur vor dem Inneren singen und ebenfalls 108 mit der Mala zählen.',
    m: 'Modul 3', q: 'Modul 3 (Teil 1), S. 7–8' },
  { id: 'lam', n: 'LAM – Bija-Mantra Muladhara (Wurzelchakra)', typ: 'Bija-Mantra', kat: ['chakra'], text: ['Lam'], fuer: 'Wurzelchakra (Muladhara)',
    wi: ['Das Bija-Mantra des Wurzelchakras ist „Lam“ (im Kundalini-Yoga „Lang“).', 'Eigenschaften laut Skript: 4 Lotusblätter, Chakra-Farbe Gelb, Aura-Farbe Rot, Sinnesorgan Nase, Element Erde, Yantra Quadrat, Gott Brahma, Tier Elefant.'],
    an: 'Hausaufgabe im Skript: die Bija-Mantren der Chakren von unten nach oben aufschreiben und zu Beginn der Yogapraxis chanten.', m: 'Modul 3', q: 'Modul 3 (Teil 1), S. 33; Teil 2, Hausaufgaben' },
  { id: 'vam', n: 'VAM – Bija-Mantra Svadhisthana (Sakralchakra)', typ: 'Bija-Mantra', kat: ['chakra'], text: ['Vam'], fuer: 'Sakralchakra (Svadhisthana)',
    wi: ['Svadhisthana wird als Lotus mit sechs Blütenblättern dargestellt und durch einen weißen Halbmond symbolisiert; das zugeordnete Bija-Mantra ist VAM.', 'Eigenschaften laut Skript: Chakra-Farbe Weiß, Aura-Farbe Orange, Yantra Mondsichel, Gott Vishnu; Themen: Intuition, Fließen, Vertrauen.'],
    m: 'Modul 3', q: 'Modul 3 (Teil 1), S. 42, 45' },
  { id: 'ram', n: 'RAM – Bija-Mantra Manipura (Solarplexuschakra)', typ: 'Bija-Mantra', kat: ['chakra'], text: ['Ram'], fuer: 'Solarplexuschakra (Manipura)',
    wi: ['Das Mantra RAM kann in der Meditation bei der Öffnung des Manipura Chakras helfen.', 'Eigenschaften laut Skript: Sinneswahrnehmung Sehen, Element Feuer, Yantra Dreieck, Gott Vishnu, Tier Widder.'],
    m: 'Modul 3', q: 'Modul 3 (Teil 1), S. 69–70' },
  { id: 'yam', n: 'YAM – Bija-Mantra Anahata (Herzchakra)', typ: 'Bija-Mantra', kat: ['chakra'], text: ['Yam'], fuer: 'Herzchakra (Anahata)',
    wi: ['Mit Mantras resoniert das Herzchakra besonders gut – es lässt sich mit dem Bija-Mantra YAM ansprechen. Im Bhakti Yoga, dem Yogaweg der Hingabe, klingt das Herz von ganz allein.', 'Eigenschaften laut Skript: 12 Lotusblätter, Sinn Tastsinn, Element Luft, Yantra sechszackiger Stern, Energieknoten Vishnu Granthi.'],
    m: 'Modul 3', q: 'Modul 3 (Teil 2), S. 91' },
  { id: 'ham', n: 'HAM – Bija-Mantra Vishuddha (Halschakra)', typ: 'Bija-Mantra', kat: ['chakra', 'pranayama'], text: ['Ham'], fuer: 'Halschakra (Vishuddha)',
    wi: ['Das dem Halschakra zugeordnete Bija-Mantra ist HAM. Besonders Vishuddha spricht auf das Singen von Mantras an (Schulter, Nacken, Kiefer, Atmung und Stimme sind mit diesem Chakra verbunden).', 'Mantrasingen ist im weitesten Sinne ein Pranayama; besonders wirkungsvoll ist dabei das Bija-Mantra für Vishuddha, die Silbe „HAM“.', 'Eigenschaften laut Skript: 16 Blütenblätter, Element Äther und Raum, Yantra Dreieck mit weißem Kreis.'],
    m: 'Modul 3', q: 'Modul 3 (Teil 2), S. 110, 114' },
  { id: 'ajna', n: 'OM / AUM – Bija-Mantra Ajna (Stirnchakra)', typ: 'Bija-Mantra', kat: ['chakra', 'meditation'], text: ['Aum / Om'], dev: 'ॐ', fuer: 'Stirnchakra (Ajna)',
    wi: ['Das Bija-Mantra des Ajna Chakras ist OM (AUM). Ajna springt besonders gut auf das Chanten von Mantras und Meditation an: In einem bequemen Sitz das Mantra AUM bzw. OM chanten.', 'Eigenschaften laut Skript: zweiblättriger Lotus (ein Blatt für die Sonne, eines für den Mond), Farbe tiefes Indigoblau bzw. Violett, Element Geist, Symbol Dreieck im Kreis.'],
    m: 'Modul 3', q: 'Modul 3 (Teil 2), S. 124, 127' },
  { id: 'satnamwahe', n: 'Sat Nam Wahe Guru', typ: 'Mantra', kat: ['wahrheit', 'schutz', 'meditation'], text: ['Sat Nam', 'Wahe Guru'], dev: '', bed: [['Sat Nam', 'Wahrheit ist mein Name'], ['Wahe Guru', 'unbeschreibliche Weisheit (3.-Auge-Mantra)']], fuer: 'Gnade, Anmut, Immunsystem, Schutz',
    wi: ['Das Mantra hilft, die Gnade und den Anmut im Inneren zu finden und über die limitierenden Konzepte hinauszusehen, sodass das für dich vorgesehene gesegnete Leben gelebt werden kann. Durch das Chanten von SAT NAM rufen wir den Geist Gottes, unser Inneres Selbst, vom Himmel herab, um unsere Shakti-Kraft (Lebensenergie) zu erwecken.', 'Das Mantra durchdringt das Unterbewusstsein, sodass du dich in den universellen Klangstrom einschwingen kannst. WAHE GURU lädt Hypophyse und Zirbeldrüse mit Licht auf; wenn diese zwei Drüsen ihr aurisches Licht miteinander verbinden, können wir hellsichtig werden und höhere Welten wahrnehmen – deshalb wird es auch 3.-Auge-Mantra genannt. Es erinnert an die Verbindung mit der göttlichen Liebe und Heilenergie und schenkt das Bewusstsein über die Verbindung zwischen innerer Göttlichkeit und der großen unendlichen Göttlichkeit.', 'Wirkungen laut Skript: stimuliert alle Drüsen, die das verjüngende Sekret mit dem Blut vermischen · hilft, Prana leichter in die Zellen aufzunehmen · gegen Allergien · exzellent beim Wechsel der Jahreszeiten · wer 7× pro Atem Sat Nam Wahe Guru chantet, wird selten krank · stärkt Immunsystem und Nervensystem · hilfreiches Mittel für das Gehirn, großartig für Studenten oder Menschen, die unter Stress geistig anspruchsvolle Leistungen erbringen · baut ein spirituelles Schutzschild für die Nerven auf, um hohen Stress-Umgebungen standzuhalten.'],
    m: 'Modul 3', q: 'Modul 3 (Teil 2), S. 148' },
  { id: 'omnamo', n: 'Om Namo Bhagavate Vasudevaya Namah', typ: 'Mantra', kat: ['einstimmung'], text: ['Om Namo Bhagavate', 'Vasudevaya Namah'], fuer: 'Mantra zur Einstimmung in die Meditation / Yogastunde',
    bed: [['Gesamt', 'Ich verneige mich vor dem Herrn, dem innewohnenden Christus-Bewusstsein, dem höheren Bewusstsein der Liebe, das allgegenwärtig, allmächtig, unsterblich und göttlich ist und in jedem Herzen wohnt. Auf diese Weise verbeugt man sich vor dem eigenen höheren Selbst und vor dem inneren Lehrer in uns.']],
    wi: ['Dieses Mantra erhöht die Konzentration und beseitigt alle Disharmonien im Körper. Es hilft, sich in Geduld zu üben; man wird von allen Sünden befreit. Durch das Chanten begibt man sich in Gottes Hände und erweckt die höheren spirituellen Zentren. Der physische und psychische Körper wird harmonisiert und bringt ins Gleichgewicht.'],
    an: 'Sitze in der einfachen Haltung und richte die Wirbelsäule gerade auf. Die Hände befinden sich in Gebetshaltung vor der Brust, die Daumen berühren das Brustbein. Die Augen sind geschlossen, die Konzentration liegt auf dem Punkt zwischen den Augenbrauen, dem Dritten Auge. Chante täglich 3–11 Minuten lang mit der Musik; nimm dir zum Abschluss einige Minuten Zeit, um vollkommen still zu sitzen und nachzuspüren.',
    m: 'Modul 1', q: 'Modul 1, S. 106' },
  { id: 'ramadasa8', n: 'Ra Ma Da Sa Sa Se So Hung (Heilmantra)', typ: 'Mantra', kat: ['heilung', 'mudra'], text: ['Ra Ma Da Sa', 'Sa Se So Hung'], fuer: 'Mantra für Heilung (Sushumna Mantra)',
    bed: [['Ra', 'das Prinzip des Feuers – symbolisiert die Sonne und schenkt Reinheit und Energie'], ['Ma', 'das Prinzip des Wassers – symbolisiert den Mond und wirkt kühlend und nährend'], ['Da', 'das Prinzip der Erde – bildet die Grundlage des Handelns'], ['Sa', 'das Prinzip der Luft – steht für die neutrale Unendlichkeit, Manifestation und Totalität'], ['Sa', 'das Prinzip der Luft – steht für die neutrale Unendlichkeit, Manifestation und Totalität'], ['Se', 'der Geist, die Gesamtheit der Erfahrung'], ['So', 'die eigene Unendlichkeit oder Identität'], ['Hung', 'die Erfahrung des „Du“']],
    wi: ['Dieses Mantra wird Sushumna-Mantra genannt und stellt eine Verbindung zur Heilenergie des Universums her. Das regelmäßige Chanten hat die Wirkung eines Gebetes.', 'Es besteht aus acht Klängen, welche die Lebensenergie zum Fließen bringen, die beiden Gehirnhälften ausgleichen und den Geist neutralisieren. Seine kraftvollen und heilenden Schwingungen unterstützen die Selbstheilung und erhalten, verbessern und stärken die Gesundheit. Durch leises Abspielen der Ra-Ma-Da-Sa-CD entfaltet das Mantra seine wohltuende Wirkung auch in Krankenzimmern und wirkt harmonisierend in jedem Zuhause, besonders auf Kinder und Haustiere.'],
    an: 'Sitze in der einfachen Haltung mit gerader Wirbelsäule. Halte die Hände in Nabelhöhe etwa 15 cm auseinander, die Handflächen zeigen zueinander. Schließe die Augen und visualisiere einen heilenden Raum zwischen den Handflächen. Die Konzentration liegt auf dem Dritten Auge. Chante täglich 11 Minuten lang mit der Musik; nimm dir zum Abschluss einige Minuten Zeit, um vollkommen still zu sitzen und nachzuspüren.',
    mu: 'Zu Mudras empfohlen (Modul 6): Herzmudra (Herzinfarkt, emotionale- und Beziehungsprobleme), Mudra „Verdauungssystem, schöne Haut“ (oder 3-Punkte-Atem; 3, 11 oder 31 Min.), Mittleres Säulenmudra „Zur Heilung von einer Person / Situation“ (3, 11 oder 31 Min.).',
    m: 'Modul 1', q: 'Modul 1, S. 107 · Modul 6, S. 90, 93' },
  { id: 'ganputi', n: 'Sa Ta Na Ma – Ra Ma Da Sa – Sa Say So Hung (Shakti Ganputi)', typ: 'Mantra', kat: ['heilung'], text: ['Sa Ta Na Ma', 'Ra Ma Da Sa', 'Sa Say So Hung'], fuer: 'Shakti Ganputi',
    bed: [['Sa Ta Na Ma', '(1) Unendlichkeit, repräsentiert den Kosmos, (2) Leben, (3) Tod oder Transformation, (4) Wiedergeburt']],
    wi: ['Dieses Mantra bringt dich in die Mitte und verleiht dir Klarheit durch das Loslassen deiner Anhaftungen. Es ist verbunden mit Samskaras, Karma und Dharma.', 'Es befreit von negativem Karma aus Vorleben und von den Auswirkungen in diesem Leben sowie vom Karma, das im täglichen Leben kreiert wird. Das Leiden oder Glücklichsein, das wir aktuell erfahren, hängt von vergangenen Taten bzw. Schulden ab.', 'Dieses Mantra macht den Weg frei für Dharma – das Gute, das du heute tust, kommt dir morgen zugute.'],
    m: 'Modul 6', q: 'Modul 6, S. 69' },
  { id: 'rama', n: 'Ra Ma', typ: 'Mantra', kat: ['heilung'], text: ['Ra Ma'], fuer: 'Heilung, Transformation, Verbindung mit dem Göttlichen',
    bed: [['Ra', 'Energie der Sonne – Feuer, Wärme, Licht; die aktive, männliche Energie, Kraft des Handelns und der Transformation; Verbindung zum Sonnengeflecht (Solarplexuschakra), dem Zentrum der persönlichen Kraft und des Willens'], ['Ma', 'Energie des Mondes – Wasser, Kühle, Sanftheit; die passive, weibliche Energie, Kraft der Intuition und der Heilung; Verbindung zum Herzchakra, dem Zentrum der Liebe und des Mitgefühls']],
    wi: ['Das Mantra „RA MA“ ist ein Mantra aus der Kundalini-Yoga-Tradition, das auch im Naam Yoga von Dr. Joseph Michael Levry verwendet wird. Es vereint die Energien von Sonne und Mond, von Aktivität und Passivität, von männlich und weiblich.', 'Es dient dazu, diese Energien in Balance zu bringen und die innere Harmonie wiederherzustellen; es wird oft für Heilungsprozesse eingesetzt, da es die Selbstheilungskräfte des Körpers aktivieren kann. Es kann helfen, emotionale Blockaden zu lösen und die Verbindung zum Göttlichen zu stärken. Im Naam Yoga wird es oft mit anderen Mantren und Mudras kombiniert, um die Wirkung zu verstärken.'],
    m: 'Modul 6', q: 'Modul 6, S. 70' },
  { id: 'gurubrahma', n: 'Guru Brahma Mantra', typ: 'Mantra', kat: ['einstimmung'], text: ['Guru Brahma', 'Guru Vishnu', 'Guru Devo', 'Mahesh Varah(a)', 'Guru Shakshat', 'Para Brahma (2x)', 'Tasmai Shri Guruve', 'Namah(a) 3x'], fuer: 'Einstimmung auf Shakti Naam',
    bed: [['Shakti', 'göttliche, weibliche Natur; alles Manifestierte'], ['Naam', 'Urklang, Schwingung'], ['Vishnu', 'Erhalter & Bewahrer'], ['Mahesh Varaha', 'Zerstörer'], ['Guru Shakshat Para Brahma', 'Allmächtiger höchster Gott']],
    wi: ['Aus dem Text Skanparama (5./6. Jahrhundert). Telefonleitung zu allen Meistern und Lehrern, auch zu unserem eigenen inneren Lehrer; weibliche, schöpfende, nährende Kraft. Wir stimmen uns mit dem Mantra auf Shakti Naam ein.'],
    m: 'Modul 6', q: 'Modul 6, S. 67' },
  { id: 'lovepeace', n: 'Love to all – Peace to all – Light to all (Mantra für Liebe, Frieden & Licht)', typ: 'Mantra', kat: ['frieden'], text: ['Love to all', 'Peace to all', 'Light to all', 'I am I am', 'HAR HAR Power', 'HAR HAR Life', 'HAR HAR Health'], fuer: 'Mantra für Liebe, Frieden & Licht',
    bed: [['Love / Peace / Light to all', 'universeller Wunsch nach Liebe, Frieden und Licht für alle Lebewesen – eine Einladung, positive Energien in die Welt zu senden'], ['I am I am', 'Anlehnung an „Ich bin, der ich bin“ (Exodus 3:14): Anerkennung des eigenen göttlichen Kerns, der unendlichen und zeitlosen Natur des Selbst; Affirmation der eigenen Existenz und Präsenz'], ['HAR HAR', 'Mantra der Kundalini-Yoga-Tradition: die schöpferische Kraft Gottes, die transformative Energie'], ['Power / Life / Health', 'Kraft, Leben, Gesundheit']],
    wi: ['Dieses Mantra, das von Dr. Joseph Michael Levry, dem Gründer von Naam Yoga, verwendet wird, ist eine kraftvolle Kombination aus universellen Wünschen und persönlichen Affirmationen. Es dient dazu, positive Energien zu verstärken und ein Gefühl von Einheit und Wohlbefinden zu fördern. Die Wiederholung von „HAR HAR“ verstärkt die Wirkung; es ist eine Bitte um göttliche Unterstützung in den Bereichen Kraft, Leben und Gesundheit.'],
    m: 'Modul 6', q: 'Modul 6, S. 68' },
  { id: 'lumen', n: 'Lumen de Lumine', typ: 'Mantra', kat: ['frieden', 'schutz'], text: ['Lumen de Lumine', 'Deum de Deo', 'Lumen de Lumine', 'Deum Verum de Deo Vero', 'Lumen de Lumine'], fuer: 'Mantra für Licht',
    bed: [['Gesamt', 'Licht vom Licht – Gott von Gott – Licht vom Licht – Wahrer Gott vom wahren Gott – Licht vom Licht']],
    wi: ['Dieses Mantra stellt durch die Schwingung seiner Klänge eine Verbindung zu den höheren Welten her und ist ein Gebet von größter Kraft. Es hält Unglück fern und bringt Frieden, Liebe und Gnade ins Leben derjenigen, die es regelmäßig singen oder die CD hören.', 'Lumen de Lumine öffnet das Herz, schenkt Heiterkeit, klärt und stärkt die Aura des Menschen und reinigt Räume von Negativität. Es umgibt alle Menschen, die es chanten oder anhören, mit einem Schutzmantel aus Licht und entfernt die Dunkelheit aus ihrem Leben.'],
    m: 'Modul 6', q: 'Modul 6, S. 71' },
  { id: 'triple', n: 'Triple Mantra (Mantra für Schutz & Licht)', typ: 'Mantra', kat: ['schutz'], text: ['Ad Gureh Nameh', 'Tschugad Gureh Nameh', 'Sat Gureh Nameh', 'Siri Guru Deveh Nameh', 'Ad Satsch', 'Tschugad Satsch', 'Hebih Satsch', 'Nanak (o) Si Bih Satsch', '(Ad Satsch … wird wiederholt)'], fuer: 'Mantra für Schutz',
    bed: [['Ad Gureh Nameh', 'Ich rufe das Licht an, das am Anfang war'], ['Tschugad Gureh Nameh', 'Ich rufe das Licht an, das alle Zeitalter hindurch existiert hat'], ['Sat Gureh Nameh', 'Ich rufe das wahre Licht an'], ['Siri Guru Deveh Nameh', 'Ich rufe das erhabene göttliche Licht an'], ['Ad Satsch', 'Das war die Wahrheit seit Anbeginn'], ['Tschugad Satsch', 'Wahr durch alle Zeit'], ['Hebih Satsch', 'Und ist auch heute wahr'], ['Nanak (o) Si Bih Satsch', 'Nanak (ein Name, der Licht repräsentiert) wird immer wahr sein']],
    wi: ['Das Triple Mantra dient dem Schutz und hält seelische und körperliche Hindernisse fern. Das regelmäßige Chanten oder Anhören der CD stärkt das elektromagnetische Feld und neutralisiert negative Schwingungen, Gedanken, Worte und Handlungen. Es wird als Schutz vor Unfällen empfohlen, insbesondere bei Autofahrten und Flügen. Selbst in scheinbar ausweglosen Situationen bringt es Licht in die Dunkelheit.'],
    an: 'Sitze in der einfachen Haltung und richte die Wirbelsäule gerade auf. Die Hände befinden sich in Gebetshaltung vor der Brust, die Daumen berühren das Brustbein. Die Augen sind geschlossen, die Konzentration liegt auf dem Punkt zwischen den Augenbrauen, dem Dritten Auge. Chante täglich 11 Minuten lang mit der Musik; nimm dir zum Abschluss einige Minuten Zeit, um vollkommen still zu sitzen und nachzuspüren.',
    mu: 'Zu einem Mudra „Für das Herz“ empfohlen (Modul 6, S. 90).', m: 'Modul 2', q: 'Modul 2, S. 71' },
  { id: 'japman', n: 'Jap Man – Sat Nam – Sada Sada Sat Nam', typ: 'Mantra', kat: ['wahrheit', 'meditation'], text: ['Jap Man', 'Sat Nam (5x)', 'Sada Sada Sat Nam'], fuer: 'Konzentration auf die Wahrheit',
    bed: [['Gesamt', '„Oh mein Geist, meditiere auf die höchste Wahrheit; Gott ist Wahrheit.“'], ['Jap Man', 'Ausdruck aus dem Gurmukhi (Sprache des Sikhismus): „Meditiere“ oder „Wiederhole im Geist“ – Aufforderung zur inneren Konzentration und zur Wiederholung des Mantras'], ['Sat Nam', 'wörtlich „Wahrheit ist meine Identität“ / „Ich bin die Wahrheit“; eines der grundlegendsten und am häufigsten verwendeten Mantras im Kundalini Yoga und Shakti Naam Yoga; ein Samen-Mantra (Bij Mantra), das das Bewusstsein auf die eigene wahre Natur ausrichtet'], ['Sada Sada Sat Nam', '„Sada“ = immer/ewig: „Immer, immer, Wahrheit ist meine Identität“ – vertieft die Verankerung in dieser Erkenntnis']],
    cd: 'Lied: Jap Man · CD: Life Pulse (Spotify)', m: 'Modul 8', q: 'Modul 8, S. 12' },
  { id: 'satnarayan', n: 'Sat Narayan – Wahe Guru – Hari Narayan – Sat(a) Nam', typ: 'Mantra', kat: ['frieden', 'wahrheit', 'mudra'], text: ['Sat Narayan', 'Wahe Guru', 'Hari Narayan', 'Sat(a) Nam'], fuer: 'Mantra für inneren & äußeren Frieden',
    bed: [['Sat Narayan', 'Name Gottes; „Wahrer“ Erhalter & Erretter'], ['Wahe Guru', 'unbeschreibliche Weisheit'], ['Hari Narayan', 'Gott in Aktion / Kreative Nahrung'], ['Sat Nam', 'Wahrheit ist mein Name, die Wahrheit liegt im Naam']],
    wi: ['Reinigt Unterbewusstsein, Geist und Körper · hilft, die Wahrheit wahrzunehmen · klärt die Emotionen · schenkt Wohlstand und Schutz · zerstört negative Schwingungen · bei Suchtverhalten, Drogenabhängigkeit · Räume und Wasser lassen sich reinigen, indem man das Mantra singt oder spielt (sehr reinigende Schwingung) · bei Erdbeben empfohlen.'],
    cd: 'Lied: Sat Narayan · CD: The Touch of Naam', mu: 'Mudra für Glauben (Modul 8, S. 13).', m: 'Modul 8', q: 'Modul 8, S. 13' },
  { id: 'gaitri', n: 'Har Gobinday – Guru Gaitri Mantra', typ: 'Mantra', kat: ['erfolg', 'schutz', 'mudra', 'pranayama'], text: ['Har', 'Gobinday', 'Mukanday', 'Udaray', 'Aparay', 'Hariang', 'Kariang', 'Nirnamay', 'Akamay'], fuer: 'Mantra für Erfolg, Zufriedenheit und zum Schutz vor Unglück',
    bed: [['Har (4×)', 'das Göttliche'], ['Gobinday', 'die erhaltende Kraft der Welt'], ['Mukanday', 'die befreiende Energie'], ['Udaray', 'das erleuchtende Element'], ['Aparay', 'die Unendlichkeit'], ['Hariang', 'das Zerstörende, die Transformation'], ['Kariang', 'das Schöpferische'], ['Nirnamay', 'ist „ohne Namen“, im Sinne von still – frei jeder Identifikation'], ['Akamay', 'das wunschlose Prinzip']],
    wi: ['„Dieses Mantra schenkt Wohlstand, glückliche Umstände und führt uns aus Zwangssituationen heraus. Es ist der Klangstrom, der einen Schutzschild aufbaut, glückliche Umstände anzieht, Unannehmlichkeiten und Krankheiten fernhält. Es ist der Schlüssel zur Erhebung des Selbst.“ (Yogi Bhajan, „81 Facets of the Mind“; zitiert nach „Mantras im Kundalini Yoga“ von Sat Hari Singh)'],
    an: 'In der Nabelarbeit (Brettposition) als Variation 3: „Gobinde, Mukande, Udare, Apare, Hariang, Kariang, Nirmane, Akame“ – der Lehrer spricht vor, die Schüler wiederholen (Modul 8, S. 63).',
    cd: 'Lied: Guru Gaitri Mantra · CD: The Flow of Naam (3. Lied)', mu: 'Zu einem Mudra „Heilt gebrochene Herzen und emotionalen Schmerz“ empfohlen (Modul 6, S. 90).', m: 'Modul 8', q: 'Modul 8, S. 14, 63 · Modul 6, S. 90' },
  { id: 'eckonkar', n: 'Eck On Kar Sat Nam', typ: 'Mantra', kat: ['pranayama'], text: ['Eck on Kar Sat Nam'], fuer: 'Pranayama „Pranischer Atem im Stehen“',
    wi: ['Wird in den Positionen 1–4 des „Pranischen Atems im Stehen“ gesprochen (je 30–60 Sekunden). Position 1: um einen hypnotischen Blick zu entwickeln – rhythmisch in den oberen Brustbereich atmen, je 1 Sekunde aus und ein; Wirkung: mehr Prana (Chi) aufnehmen, den Körper in eine Quelle des Prana verwandeln und das Feld ausdehnen. Positionen 2–4: Wirkung siehe Position 1.'],
    m: 'Modul 6', q: 'Modul 6, S. 54–57' },
  { id: 'harharhari', n: 'Har Har Hari / Har Har Har Hari', typ: 'Mantra', kat: ['pranayama'], text: ['Har Har Hari', 'Har Har Har Hari (Hari Har Trance)'], fuer: 'Naam-Cardio: „Mit den Beinen nach vorne kicken“',
    wi: ['Chante mit dem Mantra und kicke dabei abwechselnd mit je einem Bein nach vorne, die Hände auf den Hüften. Bei „Har Har Hari“: in der Pause zwischen den Mantras jeweils einen Extra-Kick machen.'],
    cd: '„Har Har Hari“ – Naam Infinitum CD (Spotify Shakti Naam Yoga Playlist) · „Har Har Har Hari / Hari Har Trance“', m: 'Modul 6', q: 'Modul 6, S. 22' },
  { id: 'wahnabel', n: 'Wah! / Wahe Guru! (Nabelarbeit)', typ: 'Formel', kat: ['pranayama'], text: ['Wah!', 'Wah! Wah! Wahe Guru!'], fuer: 'Nabelarbeit: Brettposition',
    wi: ['Variation 2 der Brettposition: Wah! mit positiven Affirmationen oder Wah! Wah! Wahe Guru! Variation 1: langer tiefer Atem. Bei den Variationen 2 und 3 spricht der Lehrer vor und die Schüler wiederholen.'],
    m: 'Modul 8', q: 'Modul 8, S. 63' },
  { id: 'wahejio', n: 'Wahe Guru, Wahe Jio', typ: 'Mantra', kat: ['mudra'], text: ['Wa He Guru / Wahe Jio'], fuer: 'Im Skript nur als Empfehlung genannt',
    wi: ['Zu Mudras empfohlen (Modul 6, S. 90–91): Herzmudra (Herzinfarkt, emotionale- und Beziehungsprobleme) und Mudra „Für Liebe und Selbstliebe“ (Liebe heilt den Kopf und das Immunsystem).'],
    cd: 'Soul Trance, 1. Lied', m: 'Modul 6', q: 'Modul 6, S. 90–91' },
  { id: 'guruRamDas', n: 'Guru Ram Das', typ: 'Mantra', kat: ['mudra'], text: ['Guru Ram Das'], fuer: 'Im Skript nur als Empfehlung genannt',
    wi: ['Zum Herzmudra empfohlen (Modul 6, S. 90).'], m: 'Modul 6', q: 'Modul 6, S. 90' },
  { id: 'guruRam', n: 'Guru Ram', typ: 'Mantra', kat: ['mudra'], text: ['Guru Ram'], fuer: 'Im Skript nur als Empfehlung genannt',
    wi: ['Zu einem Mudra „Für das Herz“ empfohlen (hält den Tod fern, für strahlende Energie, lässt die Energie für dich arbeiten) – gemeinsam mit dem Triple Mantra (Modul 6, S. 90).'], m: 'Modul 6', q: 'Modul 6, S. 90' },
  { id: 'mul', n: 'Mul Mantra', typ: 'Mantra', kat: ['mudra'], text: ['Mul Mantra'], fuer: 'Im Skript nur als Empfehlung genannt',
    wi: ['Zum Mudra „Für Hoffnung“ empfohlen (Hoffnung heilt den Bauch und reguliert die Verdauung; Modul 6, S. 91).'], cd: 'The Flow of Naam, 1. Lied', m: 'Modul 6', q: 'Modul 6, S. 91' },
  { id: 'hargobinde', n: 'Har Har Har Har Gobinde', typ: 'Mantra', kat: ['mudra'], text: ['Har Har Har Har Gobinde'], fuer: 'Im Skript nur als Empfehlung genannt',
    wi: ['Zum Mudra „Für Glauben“ empfohlen (Glaube heilt Herz, Brust und das elektromagnetische Feld, die Aura; Modul 6, S. 91).'], cd: 'Green House, 1. Lied', m: 'Modul 6', q: 'Modul 6, S. 91' },
  { id: 'lichtgebet', n: 'Lichtgebet – Das Gebet der Liebe, des Friedens & Lichts', typ: 'Gebet', kat: ['frieden', 'schutz', 'heilung'], text: ['Liebe vor mir, Liebe hinter mir,', 'Liebe links von mir, Liebe rechts von mir,', 'Liebe über mir, Liebe unter mir, Liebe in mir.', 'Liebe in meiner Umgebung', 'Liebe für alle, Liebe für das Universum', '(ebenso mit Frieden und mit Licht)'], fuer: 'Heilung, Segnen, Schutz vor Negativität',
    wi: ['Das Gebet der Liebe, des Friedens und des Lichts ist kraftvoll und äußerst wirksam. Seine genaue Ordnung und Struktur erzeugt eine vollkommene Heilwirkung. Damit kann man Menschen, die einem nahestehen, anderen Menschen und Orten, der Erde selbst und dem Universum heilende Energie senden und die Entwicklung der Menschheit unterstützen.', 'Mit den Worten wird die Energie der Liebe, des Friedens und des Lichts angerufen, um zu heilen und sich vor unerwünschten Einflüssen zu schützen. Liebe ist die höchste heilende Schwingung; aus der Liebe entwickelt sich Frieden; Licht ist das Prinzip der Vollkommenheit und bringt Gnade und Segen.'],
    an: 'Mudra: Anjali Mudra (Darbringung und Gruß, Geste der Demut) – die Hände vor der Brust zusammen (Namaskar), dann öffnen und darbringen; zum Abschluss den Kopf neigen. Anwendung laut Skript: um das Zuhause zu segnen, Krankheit zu heilen, schützt vor Negativität, gut vor Gesprächen, zur Vorbereitung.',
    mehr: [['Farben', 'Liebe: Rosa (Wärme, Geborgenheit, Trost; Freude, Liebe, Mitgefühl) · Frieden: Himmelblau (Gelassenheit, Ruhe, Frieden; Klarheit in der Kommunikation; mehr Harmonie in Beziehungen) · Licht: Weiß (Reinheit; reinigt das Magnetfeld; klärt den Geist vor Negativität; aktiviert intuitives, kreatives Potenzial; spirituelles Wachstum).'], ['Aufbau', 'Der Aufbau basiert auf den Regeln der Universellen Kabbalah (vollkommene Heilwirkung; bedingungslose Liebe hat die Kraft, Wunder und Verwandlungen zu bewirken).']],
    m: 'Modul 6', q: 'Modul 6, S. 73–75' },
  { id: 'kabbalah', n: 'Kabbalah-Kreuz (Atah – Malchut – Vegevurah – Vegedullah – Le’ohlam – Amen)', typ: 'Formel', kat: ['einstimmung'], text: ['Atah', 'Malchut', 'Vegevurah', 'Vegedullah', 'Le’ohlam', 'Amen'], fuer: 'Ausrichtung des Herzens vor der Meditation',
    bed: [['Atah', 'dein'], ['Malchut', 'das Reich (Königreich)'], ['Vegevurah', 'die Macht'], ['Vegedullah', 'und die Herrlichkeit'], ['Le’ohlam', 'in Ewigkeit'], ['Amen', 'so sei es']],
    wi: ['Die Ausrichtung des Herzens ist Teil einer meditativen Praxis, um sich auf das Höhere einzustimmen; man bekommt Führung und Stabilität.'],
    an: 'Atah: rechte Hand im Goldenen Dreieck an die Stirn · Malchut: Goldenes Dreieck zum Herzen · Vegevurah: zur rechten Schulter · Vegedullah: zur linken Schulter · dann alle Fingerspitzen beider Hände zusammenführen (Tattwa Mudra) und zur Stirn führen, die Daumen berühren die Stirn: „Le’“ vibrieren · Fingerspitzen nach vorn nahe dem Herzen: „O“ vibrieren · Fingerspitzen zeigen zur Erde auf Höhe des Solarplexus: „Lam“ vibrieren · die Goldenen Dreiecke beider Hände am Herz zusammenführen, die Arme nach außen öffnen: „Amen“ vibrieren. Sieh, wie eine duftende Rose aus deinem Herzen blüht.',
    m: 'Modul 8', q: 'Modul 8, S. 47–48' },
  { id: 'metta', n: 'Metta-Sätze (Meditation der liebenden Güte)', typ: 'Formel', kat: ['meditation', 'frieden'], text: ['Möge ich glücklich sein.', 'Möge ich gesund sein.', 'Möge ich in Frieden leben.', 'Möge ich frei von Leid sein.', 'Möge ich in Leichtigkeit leben.'], fuer: 'Metta-Meditation (innerlich gesprochen)',
    wi: ['Die Metta-Meditation ist eine buddhistische Praxis, die Gefühle von Wohlwollen, Freundlichkeit und Mitgefühl kultivieren soll – zuerst sich selbst gegenüber, dann gegenüber anderen. Die Sätze werden innerlich gesprochen; die Bedeutung der Worte spüren und tief wirken lassen.', 'Wirkungen laut Skript: reduziert Stress und Angst, fördert emotionale Heilung, verbessert Beziehungen, steigert das Selbstwertgefühl, fördert positive Emotionen wie Freude, Dankbarkeit und Liebe.'],
    an: 'Bequem sitzen, einige tiefe Atemzüge zur Zentrierung. Erst sich selbst liebende Güte senden, dann den Kreis erweitern: eine geliebte Person, eine neutrale Person, eine schwierige Person, alle Lebewesen. Einige Minuten im Gefühl der allumfassenden liebenden Güte verweilen; bei Abschweifen sanft zum Atem zurückkehren; zum Schluss langsam die Augen öffnen.',
    m: 'Modul 2', q: 'Modul 2, S. 63–64' },
  // ---------- Ergänzungen aus dem Internet (nicht aus den Lehrgangsskripten) ----------
  { id: 'adi', n: 'Ong Namo Guru Dev Namo (Adi Mantra)', typ: 'Mantra', kat: ['einstimmung', 'schutz'], text: ['Ong Namo Guru Dev Namo'], fuer: 'Einstimmung zu Beginn der Praxis (Kundalini Yoga)',
    bed: [['Ong', 'schöpferische Energie des unendlichen Kosmos'], ['Namo', 'ich verneige mich, ich rufe an'], ['Guru', 'Lehrer, Weisheit'], ['Dev', 'göttlich']],
    wi: ['Ich rufe das schöpferische, unendliche Bewusstsein des Universums an. Ich rufe die göttliche Weisheit in mir an. Im Kundalini Yoga ist es das Mantra zur Einstimmung, mit dem jede Praxis beginnt; es verbindet mit der „goldenen Kette“ der Lehrerinnen und Lehrer.'],
    an: 'Im Leichten Sitz mit geradem Rücken, die Handflächen vor der Brust zusammengelegt (Gebetshaltung), die Aufmerksamkeit am Stirnpunkt zwischen den Augenbrauen. Drei- bis fünfmal auf einem Ausatem singen; „Dev“ wird eine kleine Terz höher gesungen. Nach „Ong Namo“ darf kurz eingeatmet werden.',
    m: 'Internet', q: '3HO International – Complete Adi Mantra (3ho.org); Bedeutung: manusarona.de, turiya.de' },
  { id: 'mangala', n: 'Aad Guray Nameh (Mangala Charan Mantra)', typ: 'Mantra', kat: ['schutz', 'einstimmung'], text: ['Aad Guray Nameh', 'Jugaad Guray Nameh', 'Sat Guray Nameh', 'Siri Guroo Dayvay Nameh'], fuer: 'Schutz-Mantra (Kundalini Yoga)',
    bed: [['Aad Guray Nameh', 'ich verneige mich vor der ursprünglichen Weisheit (dem Ur-Guru)'], ['Jugaad Guray Nameh', 'ich verneige mich vor der Weisheit der Zeitalter'], ['Sat Guray Nameh', 'ich verneige mich vor der wahren Weisheit'], ['Siri Guroo Dayvay Nameh', 'ich verneige mich vor der großen, göttlichen Weisheit in mir']],
    wi: ['Mangala Charan bedeutet „etwas, das wir dem Guru zu Füßen legen“. Das Mantra wird als Schutz-Mantra beschrieben: Es soll Zweifel klären, für Führung und Schutz öffnen und das Energiefeld mit schützendem Licht umgeben.'],
    m: 'Internet', q: 'kundaliniyogaschool.org, spiritrisingyoga.org, sacredsoundyoga.org' },
  { id: 'lokah', n: 'Lokah Samastah Sukhino Bhavantu', typ: 'Mantra', kat: ['frieden'], text: ['Lokah Samastah Sukhino Bhavantu'], fuer: 'Wunsch für das Glück aller Wesen (Abschluss / Frieden)',
    bed: [['Lokah', 'die Welt, jedes Reich'], ['Samastah', 'das Ganze, alle'], ['Sukhino', 'glücklich, Freude (sukha)'], ['Bhavantu', 'mögen sie sein']],
    wi: ['„Mögen alle Wesen überall glücklich und frei sein.“ Eine häufige Fassung: „Möge das ganze Universum von Frieden, Freude, Liebe und Licht erfüllt sein.“ Im Jivamukti Yoga wird ergänzt: Mögen die Gedanken, Worte und Taten unseres Lebens zu diesem Glück und dieser Freiheit für alle beitragen. Der ursprüngliche Quelltext ist unbekannt.'],
    m: 'Internet', q: 'Yogapedia, Gaia, Project Bhakti, Liforme' },
  { id: 'asato', n: 'Asato Ma Sadgamaya', typ: 'Mantra', kat: ['einstimmung', 'meditation'], text: ['Asato mā sadgamaya', 'Tamaso mā jyotirgamaya', 'Mṛtyormā’mṛtaṃ gamaya'], fuer: 'Gebet um Wahrheit, Licht und Unsterblichkeit',
    bed: [['Asato mā sadgamaya', 'vom Unwirklichen führe mich zum Wirklichen'], ['Tamaso mā jyotirgamaya', 'von der Dunkelheit führe mich zum Licht'], ['Mṛtyormā’mṛtaṃ gamaya', 'vom Tod führe mich zur Unsterblichkeit']],
    wi: ['Aus der Brihadaranyaka-Upanishad (1.3.28). Die drei Zeilen werden bei den Pavamana-Hymnen gesprochen. Übersetzung (Olivelle): „Vom Unwirklichen führe mich zum Wirklichen! Von der Dunkelheit führe mich zum Licht! Vom Tod führe mich zur Unsterblichkeit!“'],
    m: 'Internet', q: 'Brihadaranyaka Upanishad 1.3.28 (vivekavani.com, Wikipedia „Pavamana Mantra“)' },
  { id: 'gayatri', n: 'Gayatri Mantra', typ: 'Mantra', kat: ['einstimmung', 'meditation'], text: ['Om bhūr bhuvaḥ svaḥ', 'Tat savitur vareṇyaṃ', 'Bhargo devasya dhīmahi', 'Dhiyo yo naḥ pracodayāt'], fuer: 'Meditation auf das göttliche Licht',
    wi: ['Aus dem Rigveda (3.62.10), dem Seher Vishvamitra zugeschrieben und der Gottheit Savitr (Sonne) gewidmet. Sinngemäß: „Wir meditieren über das göttliche Licht jener anbetungswürdigen Sonne, die alle drei Welten erleuchtet. Möge sie unseren Geist erleuchten und unser Verstehen wecken, damit es uns auf dem rechten Weg führt.“ Nach dem Om gilt es als eines der bedeutendsten Mantras Indiens.'],
    m: 'Internet', q: 'Wikipedia „Gayatri Mantra“, sathyasai.org, shlokam.org' },
  { id: 'mahamrit', n: 'Mahamrityunjaya Mantra', typ: 'Mantra', kat: ['heilung', 'schutz'], text: ['Tryambakaṃ yajāmahe', 'Sugandhiṃ puṣṭivardhanam', 'Urvārukam iva bandhanān', 'Mṛtyor mukṣīya mām̐mṛtāt'], fuer: 'Heilung und Schutz',
    bed: [['Tryambaka', 'der Dreiäugige (Beiname von Rudra/Shiva)'], ['Yajāmahe', 'wir verehren / opfern'], ['Sugandhi', 'der Wohlduftende'], ['Puṣṭivardhana', 'Mehrer des Gedeihens'], ['Urvāruka', 'Gurke'], ['Bandhana', 'Stiel, Fessel'], ['Mṛtyor mukṣīya', 'möge ich vom Tod befreit werden'], ['mā amṛtāt', 'nicht von der Unsterblichkeit']],
    wi: ['Aus dem Rigveda (7.59.12), auch im Yajurveda überliefert. Übersetzung: „Wir verehren den Dreiäugigen, den Wohlduftenden, den Mehrer des Gedeihens. Wie die Gurke von ihrem Stiel, möge ich vom Tod befreit werden, nicht von der Unsterblichkeit.“'],
    m: 'Internet', q: 'Wikipedia „Mahamrityunjaya Mantra“' },
  { id: 'sahanav', n: 'Om Saha Navavatu (Frieden-Mantra)', typ: 'Mantra', kat: ['frieden', 'einstimmung'], text: ['Om Saha nāv avatu', 'Saha nau bhunaktu', 'Saha vīryaṃ karavāvahai', 'Tejasvi nāv adhītam astu', 'Mā vidviṣāvahai', 'Om Śāntiḥ, Śāntiḥ, Śāntiḥ'], fuer: 'Miteinander lernen und üben (Beginn der Stunde)',
    bed: [['Saha', 'zusammen'], ['nau', 'uns beide'], ['avatu', 'möge er schützen']],
    wi: ['Aus der Taittiriya-Upanishad (Yajurveda); wird traditionell von Lehrer und Schüler vor dem gemeinsamen Studium gesprochen. Sinngemäß: „Möge er uns beide schützen. Möge er uns beide nähren. Mögen wir gemeinsam mit großer Kraft wirken. Möge unser Lernen erleuchtend sein. Möge keine Feindschaft zwischen uns sein. Om, Friede, Friede, Friede.“'],
    m: 'Internet', q: 'Taittiriya Upanishad (shlokam.org), Wikipedia „Shanti Mantras“, Awakening State' },
  { id: 'omnamahshivaya', n: 'Om Namah Shivaya', typ: 'Mantra', kat: ['einstimmung', 'meditation'], text: ['Om Namah Shivaya'], fuer: 'Verehrung Shivas (fünf-/sechssilbiges Mantra)',
    wi: ['Namah Shivaya (Panchakshara, „fünfsilbig“) bedeutet „Ehre dem Shiva“ bzw. „Ich verbeuge mich vor Shiva“; mit vorangestelltem Om heißt es Shadakshara („sechssilbig“). Die fünf Silben Na–mah–shi–va–ya werden oft den fünf Elementen (Erde, Wasser, Feuer, Luft, Raum) zugeordnet. Eines der zentralen Mantras des Shaivismus.'],
    m: 'Internet', q: 'de.wikipedia.org „Panchaksharamantra“, en.wikipedia „Om Namah Shivaya“, yoga-welten.de' },
  { id: 'ommani', n: 'Om Mani Padme Hum', typ: 'Mantra', kat: ['meditation', 'frieden'], text: ['Om Mani Padme Hum'], dev: 'ॐ मणि पद्मे हूँ', fuer: 'Mitgefühl (tibetischer Buddhismus)',
    bed: [['Om', 'unreiner Körper, Rede und Geist – und zugleich der reine Körper, die reine Rede und der reine Geist eines Buddha'], ['Mani', 'Juwel: altruistische Absicht, Mitgefühl, Liebe'], ['Padme', 'Lotus: Weisheit'], ['Hum', 'Unteilbarkeit; vereint Methode und Weisheit']],
    wi: ['Wörtlich „Preis dem Juwel im Lotus“. Sechssilbiges Mantra, besonders verbunden mit Avalokiteshvara, dem Bodhisattva des Mitgefühls; im tibetischen Buddhismus das am weitesten verbreitete Mantra. Nach der Deutung des 14. Dalai Lama steht es für die Verwandlung von unreinem Körper, unreiner Rede und unreinem Geist in die eines Buddha. Erstmals im Karandavyuha-Sutra erwähnt.'],
    m: 'Internet', q: 'Wikipedia „Om mani padme hum“' }
];

// ---------- Kachel-Symbole (Strichzeichnungen im Stil der Übungs- und Atem-Kacheln) ----------
const MANICONS = {
  om: '<text x="50" y="70" font-size="62" text-anchor="middle" fill="currentColor" stroke="none" font-family="Nirmala UI, Noto Sans Devanagari, Mangal, serif">ॐ</text>',
  lotus: '<g transform="translate(18 28)"><path d="M32 5c6 7 8 15 0 27c-8-12-6-20 0-27z"/><path d="M32 33C20 31 12 23 10 12c10 0 18 7 22 21z"/><path d="M32 33c12-2 20-10 22-21c-10 0-18 7-22 21z"/><path d="M32 35C18 37 8 33 2 25c10-2 20 0 30 10z"/><path d="M32 35c14 2 24-2 30-10c-10-2-20 0-30 10z"/></g>',
  sun: '<circle cx="50" cy="50" r="15"/><path d="M50 14v10M50 76v10M14 50h10M76 50h10M25 25l7 7M68 68l7 7M75 25l-7 7M32 68l-7 7"/>',
  sunmoon: '<circle cx="34" cy="40" r="11"/><path d="M34 14v7M34 59v7M8 40h7M53 40h-7M15 21l5 5M53 21l-5 5M15 59l5-5"/><path d="M80 52a20 20 0 1 0 0 40a15 15 0 1 1 0-40z" transform="translate(-6 -10)"/>',
  light: '<circle cx="50" cy="30" r="9"/><path d="M50 46v40M36 52l-14 30M64 52l14 30M26 34h-10M84 34H74M30 18l-6-6M70 18l6-6"/>',
  shield: '<path d="M50 14l30 10v22c0 20-14 32-30 40c-16-8-30-20-30-40V24z"/><path d="M36 48l10 10 18-20"/>',
  hands: '<path d="M50 18c-14 14-20 30-20 50l20 14 20-14c0-20-6-36-20-50z"/><path d="M50 18v64"/>',
  heart: '<path d="M50 84C20 64 14 46 22 33c8-12 24-8 28 4c4-12 20-16 28-4c8 13 2 31-28 51z"/>',
  eye: '<path d="M10 52c12-18 26-26 40-26s28 8 40 26c-12 18-26 26-40 26S22 70 10 52z"/><circle cx="50" cy="52" r="10"/><path d="M50 12v8M28 20l4 6M72 20l-4 6"/>',
  ganesha: '<circle cx="28" cy="46" r="15"/><circle cx="72" cy="46" r="15"/><circle cx="50" cy="46" r="17"/><path d="M50 62c0 14-4 22 6 26c9 3 13-5 8-9"/><path d="M42 28l8-12 8 12"/><circle cx="44" cy="42" r="1.5"/><circle cx="56" cy="42" r="1.5"/>',
  mala: '<circle cx="80" cy="50" r="4"/><circle cx="76" cy="65" r="4"/><circle cx="65" cy="76" r="4"/><circle cx="50" cy="80" r="4"/><circle cx="35" cy="76" r="4"/><circle cx="24" cy="65" r="4"/><circle cx="20" cy="50" r="4"/><circle cx="24" cy="35" r="4"/><circle cx="35" cy="24" r="4"/><circle cx="50" cy="20" r="4"/><circle cx="65" cy="24" r="4"/><circle cx="76" cy="35" r="4"/><path d="M50 84v10"/>',
  wave: '<path d="M12 50h4M24 38v24M36 26v48M48 16v68M60 26v48M72 38v24M84 50h4"/>',
  flame: '<path d="M50 12c10 16 22 26 22 42a22 22 0 0 1-44 0c0-10 6-16 10-22 2 8 6 10 8 10-2-12 0-20 4-30z"/>',
  infinity: '<path d="M50 50c-8-14-32-14-32 0s24 14 32 0c8-14 32-14 32 0s-24 14-32 0z"/>',
  star: '<path d="M50 12l10 26 26 10-26 10-10 26-10-26-26-10 26-10z"/>',
  cross: '<path d="M50 14v72M24 38h52"/><circle cx="50" cy="14" r="4"/><circle cx="50" cy="86" r="4"/><circle cx="24" cy="38" r="4"/><circle cx="76" cy="38" r="4"/>',
  lam: '<circle cx="50" cy="50" r="38"/><path d="M34 34h32v32H34z"/>',
  vam: '<circle cx="50" cy="50" r="38"/><path d="M58 32a20 20 0 1 0 0 36a15 15 0 1 1 0-36z"/>',
  ram: '<circle cx="50" cy="50" r="38"/><path d="M50 74L28 34h44z"/>',
  yam: '<circle cx="50" cy="50" r="38"/><path d="M50 28l20 34H30zM50 72L30 38h40z"/>',
  ham: '<circle cx="50" cy="50" r="38"/><path d="M50 26l22 38H28z"/><circle cx="50" cy="54" r="7"/>',
  trident: '<path d="M50 88V30M28 20v24c0 12 10 16 22 16s22-4 22-16V20M50 12v20M28 20l-5-6M72 20l5-6"/>',
  ajna: '<circle cx="50" cy="50" r="38"/><path d="M50 30c-14 8-14 32 0 40c14-8 14-32 0-40z"/><circle cx="50" cy="50" r="4"/>'
};
const MAN_ICON = { om: 'om', shanti: 'lotus', ganesha: 'ganesha', om108: 'mala', lam: 'lam', vam: 'vam', ram: 'ram', yam: 'yam', ham: 'ham', ajna: 'ajna', satnamwahe: 'eye', omnamo: 'hands', ramadasa8: 'sunmoon', ganputi: 'infinity', rama: 'sunmoon', gurubrahma: 'flame', lovepeace: 'heart', lumen: 'light', triple: 'shield', japman: 'wave', satnarayan: 'sun', gaitri: 'star', eckonkar: 'wave', harharhari: 'wave', wahnabel: 'wave', wahejio: 'wave', guruRamDas: 'wave', guruRam: 'wave', mul: 'wave', hargobinde: 'wave', lichtgebet: 'light', kabbalah: 'cross', metta: 'heart', adi: 'hands', mangala: 'shield', lokah: 'heart', asato: 'light', gayatri: 'sun', mahamrit: 'eye', sahanav: 'wave', omnamahshivaya: 'trident', ommani: 'lotus' };
const manById = id => MANTRAS.find(m => m.id === id) || null;
function manIconSVG(id) {
  const g = MANICONS[MAN_ICON[id] || 'wave'];
  return `<svg class="fig" viewBox="0 0 100 100" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">${g}</g></svg>`;
}

// ---------- Oberfläche (Seite Mantras) ----------
const manDefault = () => ({ q: '', t: '', k: '', m: '', open: new Set(), intro: false });
function manFiltered() {
  const f = ui.man, q = norm(f.q || '');
  return MANTRAS.filter(x => (!f.t || x.typ === f.t) && (!f.k || x.kat.includes(f.k)) && (!f.m || x.m === f.m)
    && (!q || norm([x.n, (x.text || []).join(' '), (x.bed || []).map(b => b[0] + ' ' + b[1]).join(' '), (x.wi || []).join(' '), x.fuer || '', x.an || '', x.cd || ''].join(' ')).includes(q)));
}
function manCard(x) {
  const open = ui.man.open.has(x.id);
  const chips = `<span class="chip mt-${x.typ.replace(/[^A-Za-z]/g, '')}">${esc(MAN_TYP[x.typ])}</span>${x.kat.map(k => `<span class="chip kc">${esc(MAN_KAT[k])}</span>`).join('')}`;
  const bed = x.bed ? `<table class="mbed">${x.bed.map(b => `<tr><td class="ml">${esc(b[0])}</td><td>${esc(b[1])}</td></tr>`).join('')}</table>` : '';
  const sec = (t, h) => h ? `<div class="msec"><h5>${t}</h5>${h}</div>` : '';
  const detail = open ? `<div class="mdet">${sec('Bedeutung', bed)}${sec('Wirkung & Beschreibung', (x.wi || []).map(p => `<p>${esc(p)}</p>`).join(''))}${sec('Anleitung', x.an ? `<p>${esc(x.an)}</p>` : '')}${sec('Lied / CD', x.cd ? `<p>${esc(x.cd)}</p>` : '')}${sec('Mudra', x.mu ? `<p>${esc(x.mu)}</p>` : '')}${(x.mehr || []).map(m => sec(esc(m[0]), `<p>${esc(m[1])}</p>`)).join('')}<p class="muted msrc">Quelle: ${esc(x.q)}</p></div>` : '';
  return `<div class="mcard${open ? ' open' : ''}" id="man-${x.id}"><div class="mhead" data-a="manTog" data-id="${x.id}"><div class="mleft"><div class="xtile cat-mantra_t" title="${esc(x.n)}">${manIconSVG(x.id)}</div></div><div class="mtext">${x.dev ? `<div class="mdev">${esc(x.dev)}</div>` : ''}${x.text.map(l => `<div>${esc(l)}</div>`).join('')}</div>
<div class="minfo"><h4>${esc(x.n)}</h4><div class="mfuer">${esc(x.fuer || '')}</div><div class="mchips">${chips}</div>${open ? '' : `<p class="msum">${esc(((x.wi || [''])[0]).slice(0, 190))}${((x.wi || [''])[0]).length > 190 ? ' …' : ''}</p>`}<span class="mtogl">${open ? '▾ weniger' : '▸ Details'} · ${esc(x.m)}</span></div></div>${detail}</div>`;
}
function viewMantras() {
  ui.man = ui.man || manDefault(); const f = ui.man, list = manFiltered();
  const mods = [...new Set(MANTRAS.map(x => x.m))].sort();
  const intro = f.intro ? `<div class="panel minfop"><h3>Grundlagen aus dem Skript</h3>${MANTRA_INTRO.map(s => `<div class="msec"><h5>${esc(s[0])}</h5><p>${esc(s[1])}</p><p class="muted msrc">Quelle: ${esc(s[2])}</p></div>`).join('')}</div>` : '';
  return `<div class="hero">${LOTUS}<div><h1>Mantras</h1><p>${MANTRAS.length} Mantras, Gebete und Formeln – ausschließlich aus den Lehrgangsskripten.</p></div><span class="grow"></span><button class="ghost" data-a="manIntro">${f.intro ? 'Grundlagen ausblenden' : 'ⓘ Grundlagen: Was ist ein Mantra?'}</button></div>
${intro}<div class="panel mfilt"><div class="grid">${fld('Suche', inp('u:man.q', 'search', f.q, 'placeholder="Name, Text, Bedeutung …" data-live="1"'))}
${fld('Art', sel('u:man.t', [['', 'Alle']].concat(Object.keys(MAN_TYP).map(k => [k, MAN_TYP[k]])), f.t))}
${fld('Anlass / Wirkung', sel('u:man.k', [['', 'Alle']].concat(Object.keys(MAN_KAT).map(k => [k, MAN_KAT[k]])), f.k))}
${fld('Modul', sel('u:man.m', [['', 'Alle']].concat(mods.map(m => [m, m])), f.m))}</div>
<div class="bar"><span class="muted">${list.length} von ${MANTRAS.length} angezeigt</span><span class="grow"></span><button class="ghost sm" data-a="manAll" data-v="1">alle aufklappen</button><button class="ghost sm" data-a="manAll" data-v="0">alle zuklappen</button><button class="ghost sm" data-a="manReset">Filter zurücksetzen</button></div></div>
${list.length ? list.map(manCard).join('') : '<p class="muted">Keine Treffer.</p>'}`;
}
const MANTRA_ACTIONS = {
  pkman(d, el) { openMantraPicker(el, d); },
  pkmanpick(d) {
    const p = ui.pk; if (!p || p.kind !== 'man') return; const { c, s } = sessionOf(p.sid); closePicker();
    s.mantra = { id: d.id }; regenIfNotEdited(c, s, 'mantra'); save(); render();
  },
  manTog(d) { const o = ui.man.open; o.has(d.id) ? o.delete(d.id) : o.add(d.id); render(); },
  manAll(d) { ui.man.open = d.v === '1' ? new Set(manFiltered().map(x => x.id)) : new Set(); render(); },
  manReset() { const o = ui.man.open, i = ui.man.intro; ui.man = manDefault(); ui.man.open = o; ui.man.intro = i; render(); },
  manIntro() { ui.man.intro = !ui.man.intro; render(); }
};
