/* Shakti Naam Übungen (Modul 6 des Ausbildungsskripts): Heilserie, Cardio im Stehen, Cardio Atemarbeit im Sitzen.
   Nur Übungen, die im Skript vorkommen. Beschreibungen sind eigene, knappe Zusammenfassungen (keine Textübernahme); Quelle = Modul + Seite.
   Kategorie c: 'shakti' (eigener Block „Shakti Naam“ zwischen Mobilisation und Flow). Vorsichtshinweise (x) bei den Cardio-Übungen im Stehen sind vorsorglich gesetzt. */
(function () {
  const SN = (id, n, pose, lv, m, t, x, src, d, o) => K(Object.assign({ id, n, c: 'shakti', lv, m, pose, t, x: x || '', st: 'kund', src, d, sv: true, s: 0 }, o || {}));
  const KONTRA = 'Kontraindikationen laut Skript (Pranayama): Schwindel, Schwangerschaft, Bluthochdruck, Glaukom, Osteoporose.';
  const STEH = 'knie fuss schwindel blutdruck osteoporose';

  // --- Shakti Naam Heilserie (für Vitalität, Jugend & Schönheit) ---
  SN('sn_armswing', 'Arm Swings (Heilserie)', 'arm_swing', 2, 2, 'herz kreislauf energie', STEH, 'Modul 6, S. 15–16', 'Erste Übung der Shakti Naam Heilserie: schwungvolles Armschwingen im Stehen (im Skript nur als Titel abgebildet). Die Heilserie ist ein Herz-Kreislauf-Training, das das elektromagnetische Feld stärkt; dabei immer die Körpermitte (Hara) aktivieren.');
  SN('sn_magnet', 'Shakti Naam Magnetfeld-Übung', 'arms_up', 2, 5, 'herz kreislauf energie', STEH, 'Modul 6, S. 16', 'Zweite Übung der Heilserie. Dauer laut Skript 5–10 Minuten, begleitet von Musik („Rise“, CD „Life Pulse“). Stärkt das elektromagnetische Feld.');
  SN('sn_clapwalk', 'Clap Walk / Kreuzweises Laufen', 'knee_lift', 2, 6, 'herz kreislauf energie koordination', STEH, 'Modul 6, S. 17', 'Dritte Übung der Heilserie: kreuzweises Laufen. Dauer laut Skript 6–10 Minuten, Musik „God is My Life“. Abschluss: tief einatmen, die Arme nach oben strecken, ausatmen und entspannen.');
  SN('sn_heartsaver', 'Heart Saver – Herzretter', 'arms_up', 2, 3, 'herz kreislauf energie', STEH, 'Modul 6, S. 17', 'Vierte Übung der Heilserie, etwa 3 Minuten, Musik „Rise“. Abschluss: die Arme gerade über den Kopf heben und beim Ausatmen Arme und ganzen Körper ausschütteln.');
  SN('sn_walking', 'Shakti Naam Walking', 'knee_lift', 2, 3, 'herz kreislauf energie', STEH, 'Modul 6, S. 18', 'Fünfte Übung der Heilserie, 3–6 Minuten, Musik „God is My Life“. Ende: einatmen, Arme über den Kopf, ausatmen und die Arme seitlich sinken lassen; dann vorsichtig zum Boden in die Kindhaltung (Stirn am Boden, mindestens 1 Minute) – frisches Blut erreicht das Gehirn. Danach warmes Wasser trinken.', { w: 'Laut Skript nach der Übung warmes Wasser trinken.' });
  SN('sn_shaking', 'Schütteln auf dem Rücken', 'supine_bent', 1, 2, 'loslassen energie', 'ruecken', 'Modul 6, S. 19', 'Siebte Übung der Heilserie, 1–3 Minuten, Musik „The Great Spirit“. In Rückenlage den unteren Rücken in den Boden drücken, Bauch anspannen (Decke unter das Gesäß, falls der Rücken nicht aufliegt); Arme und Beine gerade nach oben strecken, Handflächen zum Himmel, Handgelenke drehen wie beim Eindrehen einer Glühbirne und kräftig schütteln. Ende: einatmen, Schütteln anhalten; beim Ausatmen die Knie zur Brust umarmen und sanft auf der Wirbelsäule vor- und zurückrollen.', { s: 1 });

  // --- Shakti Naam Cardio im Stehen ---
  SN('sn_kick1', 'Kicken nach vorn, Hände auf den Hüften (Har Har Hari)', 'knee_lift', 2, 2, 'herz kreislauf energie mantra', STEH, 'Modul 6, S. 22', 'Mit dem Mantra „Har Har Hari“ abwechselnd mit je einem Bein nach vorn kicken, die Hände auf den Hüften; in der Pause zwischen den Mantras jeweils ein Extra-Kick. Beckenboden anspannen und „bracen“, um den unteren Rücken zu unterstützen.');
  SN('sn_kick2', 'Kicken nach vorn, Hände auf den Hüften (Har Har Har Hari)', 'knee_lift', 2, 2, 'herz kreislauf energie mantra', STEH, 'Modul 6, S. 22', 'Wie zuvor, mit dem Mantra „Har Har Har Hari / Hari Har Trance“: zum Mantra abwechselnd mit je einem Bein nach vorn kicken.');
  SN('sn_cross', 'Kreuzweises Laufen, entgegengesetzter Ellbogen', 'knee_lift', 2, 2, 'herz kreislauf energie koordination', STEH, 'Modul 6, S. 23', 'Auf der Stelle laufen, abwechselnd ein Knie heben und den Nabel nach innen oben ziehen (Breath of Glow). Knie und gegenüberliegender Ellbogen berühren sich; bei jeder Berührung durch die Nase ausatmen, zügiges Tempo.');
  SN('sn_march', 'Auf der Stelle marschieren mit HAR auf jeden 4. Schlag', 'knee_lift', 2, 2, 'herz kreislauf energie mantra', STEH, 'Modul 6, S. 23', 'Auf der Stelle laufen, abwechselnd ein Knie heben, den Nabel nach innen oben ziehen; die Arme sind gebeugt, die Ellbogen schwingen nach hinten mit. „HAR“ auf jeden vierten Schlag. Laufen ist laut Skript sehr gut für das Gehirn; Körpermitte „bracen“.');
  SN('sn_fan', 'Marschieren mit Herz-Fächeln', 'knee_lift', 2, 2, 'herz kreislauf energie', STEH, 'Modul 6, S. 24', 'Auf der Stelle laufen, abwechselnd ein Knie heben. Mit dem gegenüberliegenden Arm zum Herzen fächeln (Handfläche zeigt zum Herzen, ohne zu berühren), der andere Arm hängt seitlich gestreckt nach unten. Bei jedem Knieheben durch die Nase ausatmen.');
  SN('sn_run', 'Auf der Stelle rennen, Arme auf Schulterhöhe (Suriya Mudra)', 'knee_lift', 3, 2, 'herz kreislauf energie', STEH, 'Modul 6, S. 24', 'Hände im Suriya Mudra auf Schulterhöhe halten, zügig auf der Stelle laufen, die Knie anheben und dabei Feueratem durch die Nase machen.');
  SN('sn_dance', 'Tanzen mit Breath of Glow und Shakti Mudra', 'arms_up', 2, 2, 'herz kreislauf energie freude', STEH, 'Modul 6, S. 24', 'Im Stehen die Knie im Rhythmus der Musik beugen und strecken, dabei mit beiden Armen im Rhythmus nach oben boxen (Schulterhöhe oder darüber), Shakti Mudra, Breath of Glow; Bewegung in alle Richtungen.');
  SN('sn_squat', 'Kniebeugen mit Har (36x)', 'squat', 2, 3, 'kraft beine', 'knie huefte schwindel blutdruck osteoporose', 'Modul 6, S. 26', 'Schulterbreit stehen, Füße parallel, Arme nach vorn gestreckt (Handflächen nach unten). Knie beugen bis in die Hocke und wieder hochkommen, beim Beugen „HAR“ chanten und beim Hochkommen laut mitzählen (36 Wiederholungen). Wirkung laut Skript: stärkt die Beine und schenkt Wohlstand. Wirbelsäule gerade halten, Knie über den Zehen, nicht nach innen kippen, Körpermitte „bracen“.', { w: 'Wirbelsäule stets gerade halten; Knie nicht nach innen kippen lassen.' });

  // --- Shakti Naam Cardio Atemarbeit im Sitzen (je 3 Minuten) ---
  const SIT = (id, n, pose, wi, d) => SN(id, n, pose, 1, 3, 'atem herz energie', 'schwindel blutdruck osteoporose', 'Modul 6, S. 61–65', d + ' Abschluss jeweils mit angehaltenem Atem und kräftigem Ausschütteln der Arme beim Ausatmen. Wirkung laut Skript: ' + wi, { s: 1, w: KONTRA });
  SIT('sn_s_twist', 'Twisten mit Shakti Mudra vor dem Herzen', 'sit_twist', 'öffnet den Solarplexus, revitalisiert das Gehirn, reinigt den Körper, hilft gegen Depressionen und klärt Emotionen.', 'Arme angewinkelt, Hände im Shakti Mudra auf Herzhöhe; den Oberkörper abwechselnd zu jeder Seite drehen und dabei ausatmen, Blick auf die Nase, rhythmisch im eigenen Tempo.');
  SIT('sn_s_gyan', 'Bewegtes Gyan Guru Shakti Mudra', 'sit_arms', 'befreit die Aura von schlechter Energie, schenkt Disziplin und Wohlstand.', 'Finger ineinander verschränken, Jupiter- und Saturnfinger ausstrecken; das Mudra zügig zwischen Kopf und Herz auf und ab bewegen, einatmen beim Heben, ausatmen beim Senken.');
  SIT('sn_s_chest', 'Öffnen des Brustkorbes', 'sit_arms', 'öffnet den Brustkorb, harmonisiert und erneuert das Gehirn.', 'Hände im Shakti Mudra, Arme angewinkelt; einatmen und die Ellbogen nach hinten ziehen, ausatmen und die Arme vor der Brust kreuzen (abwechselnd ein anderer Arm oben); durch die Nase ein-, durch den Mund ausatmen.');
  SIT('sn_s_prana_down', 'Prana herunterbringen', 'sit_arms', 'stärkt das Prana im Körper und regt den Lymphfluss an.', 'Im einfachen Sitz einatmen und Arme und Finger hoch über den Kopf strecken; mit dem Ausatmen die Hände im Shakti Mudra zu den Schultern herunterbringen. Langsam beginnen und das Tempo allmählich steigern.');
  SIT('sn_s_prana_grab', 'Prana greifen', 'sit_arms', 'stärkt Herz und Arterien.', 'Im einfachen Sitz einatmen und die Arme gerade nach vorn strecken (Handflächen nach unten, Finger gespreizt); Fäuste machen (Daumen außen) und mit dem Ausatmen die Arme zurückziehen, dabei drehen sich die Handflächen nach oben.');
  SIT('sn_s_cross', 'Abwechselndes Kreuzen der Arme im Segnungs-Mudra', 'sit_arms', 'harmonisiert das Gehirn und reinigt das Blut.', 'Arme angewinkelt, Hände auf Schulterhöhe im Segnungs-Mudra, Handflächen nach vorn; durch die Nase einatmen und die Ellbogen zurückziehen, durch den Mund ausatmen und die Unterarme vor der Brust kreuzen, abwechselnd links oder rechts oben.');
  SIT('sn_s_fan', 'Zum Herzen fächeln (im Sitzen)', 'sit_arms', 'unterstützt das Herz, stärkt das Immunsystem, die Thymusdrüse und das elektromagnetische Feld.', 'Im einfachen Sitz, Wirbelsäule gerade, Kinn leicht zur Brust: abwechselnd bewegt sich eine Handfläche bis etwa 10 cm zum Herzen, die andere zum gegenüberliegenden Knie – als würdest du dem Herzen zufächeln. Atem reguliert sich von selbst.');
  SIT('sn_s_circles', 'Rückwärtskreise mit seitlich gestreckten Armen im Shakti Mudra', 'sit_arms', 'harmonisiert und stärkt das elektromagnetische Feld, gut für Drüsen- und Nervensystem und Herz.', 'Arme gerade zur Seite gestreckt, Hände im Shakti Mudra; synchron mit beiden Armen rückwärts kreisen. Atem durch die Nase, reguliert sich von selbst.');
  SIT('sn_s_wings', 'Flügelschlagen mit Silbernem Dreieck', 'sit_elbow', 'öffnet den Brustkorb, stimuliert den Gallenblasen-Meridian.', 'Arme angewinkelt, Ellbogen am Brustkorb, Hände im Silbernen Dreieck (Spitzen von Daumen, Ring- und kleinem Finger zusammen); einatmen und die Ellbogen auf Schulterhöhe heben (Unterarme parallel zum Boden), ausatmen und senken – die Ellbogen „schlagen“ dabei leicht an den Brustkorb. Kräftiges Ein- und Ausatmen durch die Nase.');
  // --- Cardio Übungen mit Detailseiten (S. 28–37) und HWS Mobilisation / Nackenöffnungen (S. 38–43) ---
  SN('sn_brain', 'Brain Booster', 'arms_up', 2, 2, 'energie herz kreislauf', 'schwindel blutdruck', 'Modul 6, S. 31', 'Im Stehen die Arme mit dem Einatmen vor der Brust kreuzen, sofort weiter einatmen und die Arme weit öffnen, dann über den Kopf ziehen. Mit dem Ausatmen (durch den Mund oder mit „Haaa“) den Oberkörper bei leicht gebeugten Knien nach vorn unten führen, der Nabel zieht leicht nach innen. Eingeatmet wird in drei Segmenten durch die Nase, ausgeatmet in einem Zug. Zum Schluss mit den Armen über dem Kopf nachatmen und ausschütteln. Soll Gehirn, Kreislauf und Verdauung anregen und beim Loslassen von Ärger helfen.', { w: 'Bei Schwindel oder Bluthochdruck vorsichtig und mit kleiner Vorbeuge üben.' });
  SN('sn_armkreise', 'Cardio Armkreise', 'arm_swing', 2, 2, 'herz kreislauf energie', 'schulter blutdruck osteoporose schwindel', 'Modul 6, S. 32', 'Aufrecht stehen, Füße zusammen, Hände im Shakti Mudra. Tief durch die Nase einatmen, den Atem halten und mit beiden gestreckten Armen gleichzeitig 26 bis 30 Rückwärtskreise ziehen. Danach die Ellbogen zurückziehen, die Arme gerade nach vorn stoßen und zischend ausatmen. Wiederholen mit Vorwärtskreisen und mit gegenläufigen Armen (links vor, rechts zurück und umgekehrt). Öffnet den Brustraum und unterstützt das Herz.', { w: 'Laut Skript nicht bei Schulter- oder Armproblemen, Bluthochdruck, Glaukom, Osteoporose, Schwindel und Schwangerschaft; Ältere eventuell mit Unterstützung.' });
  SN('sn_prana_himmel', 'Himmlisches Prana anziehen', 'arms_up', 2, 2, 'energie herz kreislauf', 'schulter knie osteoporose', 'Modul 6, S. 33', 'Schulterbreiter Stand. Mit dem Einatmen die Arme und Finger gerade über den Kopf strecken, mit dem Ausatmen die Hände im Shakti Mudra zu den Schultern bringen und dabei die Knie beugen; im Wechsel weitermachen. Zum Schluss einatmen, strecken, den Atem kurz halten, ausatmen und die Arme ausschütteln. Regt Kreislauf und Lymphfluss an, stärkt das Prana.', { w: 'Laut Skript nicht bei Schulter-, Arm- oder Knieproblemen und Osteoporose; Ältere eventuell mit Unterstützung.' });
  SN('sn_haratanz', 'Hara Tanz', 'hips_hands', 2, 2, 'energie wurzel kreislauf', 'knie osteoporose', 'Modul 6, S. 34', 'Schulterbreit stehen. Mit flachen Händen den Bereich des Hara (unter dem Nabel, zwischen den Hüftknochen) abklopfen, dann in die Hände klatschen, bei jedem Schlag leicht in die Knie gehen: klopf, klatsch, klopf, klatsch. Varianten: beim Berühren „Har“ chanten, oder den Oberkörper im Wechsel nach links und rechts drehen. Zum Schluss einatmen, strecken, Arme über dem Kopf ausschütteln. Wärmt auf und stärkt die Körpermitte.', { w: 'Laut Skript nicht bei Knieproblemen, Osteoporose und Schwangerschaft; Ältere eventuell mit Unterstützung.' });
  SN('sn_lichtwall', 'Lichtwall', 'arms_side', 2, 2, 'energie kraft atem', 'schulter knie osteoporose', 'Modul 6, S. 35', 'Hüftbreiter Stand. Mit dem Ausatmen durch den o-förmigen Mund die Arme nach vorn strecken (Handflächen nach vorn, Finger nach oben) und die Knie beugen. Hände zur Schulter zurück, den Oberkörper nach links eindrehen und die Arme nach links strecken, wieder nach vorn, dann nach rechts, im zügigen Wechsel. Zum Schluss tief einatmen, Atem halten, Arme und Hände über dem Kopf schütteln, ausatmen. Stärkt Wirbelsäule und Lungen.', { w: 'Laut Skript nicht bei Schulter-, Arm- oder Knieproblemen und Osteoporose; Ältere eventuell mit Unterstützung.' });
  SN('sn_superheld', 'Superheld Sequenz', 'side_bend', 2, 3, 'seit dehnen herz', 'schulter ruecken', 'Modul 6, S. 36–37', 'Aufrecht stehen, Füße zusammen, Körpermitte aktivieren. Einen Arm gerade hinter dem Ohr nach oben strecken, dreimal tief ein- und ausatmen und sich lang machen; dann die Hand zum Shakti Mudra formen, erneut dreimal. Mit der anderen Hand das Handgelenk umfassen und noch weiter dehnen. Mit angehaltenem Atem einen Ausfallschritt zur Seite machen und die Körperseite dehnen, zuerst nach oben, dann zur Seite, als stünde man zwischen zwei Glaswänden. In der Haltung drei tiefe Atemzüge, dann zurück in den Stand. Alle Schritte mit dem anderen Arm wiederholen. Linker Arm unterstützt das Herz, rechter die Leber.', { w: 'Laut Skript nicht bei Schulterproblemen und Verletzungen der Wirbelsäule.' });
  SN('sn_nacken1', 'Nackenöffnung mit verschränkten Händen (Option 1)', 'stand', 1, 2, 'nacken mobi', 'nacken blutdruck', 'Modul 6, S. 39', 'Aufrecht stehen, Hände hinter dem Rücken verschränken, Schulterblätter zusammenziehen, Schultern senken. Einatmend den Kopf nach links drehen, ausatmend zurück zur Mitte, dann rechts, je dreimal. Dann den Kopf heben und zur Brust senken, je dreimal. Dann das linke Ohr zur linken Schulter, das rechte zur rechten, je dreimal. Zuletzt den Kopf behutsam einmal in jede Richtung kreisen. Abschluss: tief einatmen, Atem halten, ausatmen und nachspüren.', { c: 'mobi_stand', s: 1, w: 'Laut Skript nicht bei Nackenverletzungen und Bluthochdruck.' });
  SN('sn_nacken2', 'Kinnkreise / Schildkrötenübung (Option 2)', 'stand', 1, 2, 'nacken mobi', 'nacken blutdruck', 'Modul 6, S. 40–41', 'Aufrecht stehen, die Hände in der Taille. Mit dem Kinn acht liegende Nullen zeichnen: von links nach rechts, dann von rechts nach links, dann nach vorn. Abschluss: Kopf zur Mitte bringen, tief einatmen, Atem halten, ausatmen und nachspüren. Öffnet den Halsbereich und löst Nackenspannung.', { c: 'mobi_stand', s: 1, w: 'Laut Skript nicht bei Nackenverletzungen und Bluthochdruck.' });
  SN('sn_hamster', 'Hamster im Glück (Option 3)', 'stand', 2, 2, 'nacken atem', 'nacken blutdruck', 'Modul 6, S. 42', 'Aufrecht stehen, Arme seitlich, Hände im Shakti Mudra, Handrücken nach vorn. Den Kopf leicht zurücklegen, durch den o-förmigen Mund einatmen, den Atem halten, die Wangen aufplustern und das Kinn zur Brust bringen. Mit angehaltenem Atem die Schultern 8 bis 10 Mal (oder 30 Sekunden) heben und senken, die Arme bleiben gestreckt. Kopf aufrichten, sanft durch die Nase ausatmen. Insgesamt dreimal. Unterstützt Schilddrüse und Gesichtshaut.', { c: 'mobi_stand', w: 'Mit angehaltenem Atem: laut Skript nicht bei Nackenverletzungen und Bluthochdruck.' });
  SN('sn_tattva', 'Backen aufplustern mit Tattva Mudra (Option 4)', 'prayer', 2, 2, 'nacken atem', 'nacken blutdruck', 'Modul 6, S. 43', 'Aufrecht stehen, die Fingerspitzen im Tattva Mudra zusammen, Daumen zum Körper. Die Daumen auseinander nehmen und beide Nasenlöcher verschließen, nach oben blicken, durch den o-förmigen Mund einatmen, Atem halten, Wangen aufplustern. Kinn zur Brust, Handgelenke so drehen, dass die kleinen Finger die Brust berühren. Halten, solange der Atem angehalten werden kann (etwa 15 Sekunden), dann Kinn heben, Daumen lösen und langsam durch die Nase ausatmen. Dreimal. Gut für Zähne, Zahnfleisch und Kiefer.', { c: 'mobi_stand', w: 'Laut Skript nicht bei Nackenverletzungen, Bluthochdruck und Glaukom.' });
})();
