/* Erweiterung des Katalogs um Übungen aus dem Ausbildungsskript (300h Multi-Style Yogalehrer-Ausbildung, Module 1–11).
   Nur Übungen, die im Skript vorkommen. Beschreibungen sind eigene, knappe Zusammenfassungen (keine Textübernahme); Quelle = Modul + Seite.
   sa = Sanskrit-Name, sv = im Skript belegt (true) bzw. Standardbezeichnung ohne Beleg im Skript (false)
   st = Yogastile, d = Beschreibung, w = Vorsicht/Hinweis laut Skript, man = nur manuell wählbar (nicht automatisch vorgeschlagen) */
const STILE = {
  sen: 'Senioren-Kurs', hatha: 'Hatha', vinyasa: 'Vinyasa', yin: 'Yin', kund: 'Kundalini / Shakti Naam', chakra: 'Chakra-Yoga', natal: 'Prä-/Postnatal', adv: 'Advanced'
};

// ---------- zusätzliche Strichmännchen-Posen ----------
(function () {
  const P = (k, s) => { POSES[k] = s.trim().split(/\s+/).map(p => p.split(',').map(Number)); };
  P('pyramid', '70,66 62,56 40,46 70,72 74,88 66,74 70,88 52,70 56,92 30,70 22,92');
  P('triangle', '82,58 72,52 50,42 76,68 78,84 72,38 72,24 64,66 78,92 36,66 22,92');
  P('half_moon', '18,52 28,52 50,52 28,66 28,80 28,38 28,24 50,72 50,92 72,52 94,52');
  P('hand_to_toe', '46,14 46,23 46,52 62,36 82,50 34,36 30,52 68,52 90,52 46,72 46,92');
  P('bird', '46,14 48,23 50,52 62,40 64,56 40,40 52,56 64,36 70,12 50,72 50,92');
  P('wheel', '26,74 34,62 52,42 28,78 20,90 30,80 24,90 68,62 78,90 66,64 74,90');
  P('camel', '34,46 42,36 48,60 58,52 62,84 56,54 66,84 48,80 66,88 46,82 64,88');
  P('bow', '24,50 32,60 50,76 52,66 74,50 54,68 76,52 68,84 88,52 66,84 86,54');
  P('locust', '24,66 32,72 60,80 46,80 60,84 46,82 60,84 78,76 96,72 78,78 96,74');
  P('downdog', '30,66 38,58 50,34 28,74 20,88 30,74 24,88 66,62 80,88 64,62 78,88');
  P('updog', '26,40 34,48 50,70 36,66 34,86 38,66 36,86 70,80 90,88 72,82 90,88');
  P('plank_hi', '18,48 26,52 60,62 26,68 26,82 28,68 28,82 76,72 92,82 78,72 94,82');
  P('chatur', '18,64 26,66 60,70 36,70 28,80 38,70 30,82 76,76 92,82 78,76 94,84');
  P('sideplank', '20,36 26,44 54,60 24,64 22,84 24,28 24,14 70,72 86,84 72,74 88,86');
  P('crow', '30,38 38,48 58,50 36,68 30,86 38,68 32,86 44,58 66,62 46,60 68,64');
  P('headstand', '50,82 50,74 50,44 38,84 46,88 62,84 54,88 50,26 50,8 52,26 52,8');
  P('shoulderstand', '10,84 18,82 34,50 26,84 30,64 28,86 32,66 38,30 40,10 40,30 42,10');
  P('plow', '10,84 18,82 34,50 30,86 44,88 32,86 46,88 56,30 76,84 58,32 78,84');
  P('handstand', '50,74 50,66 50,38 46,78 46,90 54,78 54,90 50,22 50,6 52,22 52,6');
  P('forearm', '46,66 48,58 50,34 36,88 52,88 38,88 54,88 50,18 50,4 52,18 52,4');
  P('scorpion', '46,66 48,58 50,38 36,88 52,88 38,88 54,88 38,18 30,28 40,18 32,30');
  P('viparita', '10,84 18,82 38,62 28,86 38,80 30,86 40,80 46,40 50,20 48,40 52,20');
  P('lizard', '30,58 40,62 66,74 38,80 30,88 42,80 34,88 44,72 38,90 84,84 96,90');
  P('happy_baby', '10,80 18,80 46,80 38,66 60,44 40,66 62,46 60,62 62,40 58,64 60,38');
  P('hero', '50,38 50,48 50,80 62,62 68,80 38,62 32,80 70,82 56,90 30,82 44,90');
  P('supta_hero', '16,80 24,76 46,78 30,84 40,86 32,85 42,87 74,80 56,88 72,82 54,90');
  P('gomukhasana_sit', '50,38 50,48 50,78 58,30 52,44 44,62 50,54 70,80 52,88 30,80 48,88');
  P('splits', '50,36 50,46 50,82 58,34 56,20 42,34 44,20 36,84 22,88 64,84 78,88');
  P('half_splits', '78,60 68,58 46,70 76,74 84,86 74,76 82,88 70,80 92,88 30,82 14,88');
  P('seated_fold', '70,66 58,64 34,78 74,74 88,80 72,76 86,82 62,80 90,82 62,81 90,83');
  P('wide_seat', '50,38 50,48 50,78 62,60 72,78 38,60 28,78 72,72 92,66 28,72 8,66');
  P('turtle', '50,88 50,78 50,62 66,72 82,80 34,72 18,80 70,56 90,64 30,56 10,64');
  P('pigeon', '56,34 56,44 56,72 52,62 50,84 62,62 62,84 30,70 56,88 82,82 96,88');
  P('swan', '26,76 36,70 56,74 30,86 16,88 32,86 18,88 30,72 54,88 82,82 96,88');
  P('crescent', '52,16 50,26 44,56 56,14 57,2 44,14 43,2 66,66 66,92 28,80 14,90');
})();

// ---------- Übungen aus dem Skript ----------
function K(o) {
  const e = Object.assign({
    s: 0, m: 2, e: '', h: '', sv: true, man: false, script: true, t: [], x: [], st: ['hatha'], d: '', w: '', sa: ''
  }, o);
  e.t = typeof o.t === 'string' ? o.t.split(' ') : (o.t || []);
  e.x = typeof o.x === 'string' ? (o.x ? o.x.split(' ') : []) : (o.x || []);
  e.st = typeof o.st === 'string' ? o.st.split(' ') : (o.st || ['hatha']);
  e.o = EX.length;
  EX.push(e);
}
// Pawanmuktasana / Wirbelsäulen-Mobilisation (Modul 1 und 2)
K({ id: 'sufi_kreise', n: 'Sufi-Kreise im Sitz', c: 'mobi_sitz', lv: 1, m: 1, pose: 'sit_twist', t: 'ruecken mobi loslassen', st: 'hatha', src: 'Modul 2, S. 6', d: 'Im aufrechten Sitz mit den Händen auf den Knien den Oberkörper in großen Kreisen bewegen: nach vorn, zur Seite, nach hinten und zur anderen Seite – mobilisiert die Wirbelsäule.' });
K({ id: 'drehschwingen', n: 'Drehschwingen im Stand', c: 'mobi_stand', lv: 1, m: 1, pose: 'twist', t: 'ruecken mobi loslassen', x: 'osteoporose', st: 'hatha', src: 'Modul 2, S. 6', d: 'Aus dem Stand den Oberkörper locker von Seite zu Seite drehen und schwingen lassen – erwärmt und mobilisiert die Wirbelsäule.' });
K({ id: 'kati_chakrasana', n: 'Drehung in der Taille', sa: 'Kati Chakrasana', c: 'mobi_stand', lv: 1, m: 1, pose: 'twist', t: 'ruecken mobi', x: 'osteoporose', st: 'hatha', src: 'Modul 2, S. 6', d: 'Stehende Taillendrehung aus der Wirbelsäule heraus, Becken bleibt ruhig; Teil des Wirbelsäulen-Übungsprogramms.' });
K({ id: 'tiryaka_tadasana', n: 'Sich wiegende Palme', sa: 'Tiryaka Tadasana', c: 'mobi_stand', lv: 1, m: 1, pose: 'side_bend', t: 'ruecken atem mobi', st: 'hatha', src: 'Modul 2, S. 7', d: 'Stand etwas weiter als schulterbreit, Finger über dem Kopf verschränkt, mit der Ausatmung seitlich neigen – ohne den Oberkörper zu drehen, Arme bleiben aktiv.' });
K({ id: 'halasana_wand', n: 'Pflug gegen die Wand', sa: 'Halasana', c: 'boden', lv: 2, m: 1.5, pose: 'legs_wall', t: 'ruecken kraft', x: 'ruecken nacken blutdruck osteoporose', st: 'hatha', src: 'Modul 2, S. 8', d: 'Rückenlage: Beine mit der Kraft der Bauchmuskeln anheben (zuerst bis ca. 60°, dann Richtung 90° bzw. zur Wand) und wieder absenken – bereitet den Pflug vor.', w: 'Auf den unteren Rücken achten.', h: 'halasana' });
K({ id: 'jhulana', n: 'Abrollen in der Päckchenstellung', sa: 'Jhulana Lurhakanasana', c: 'boden', lv: 1, m: 1.5, pose: 'supine_knee', t: 'ruecken loslassen mobi', x: 'ruecken nacken osteoporose', st: 'hatha', src: 'Modul 2, S. 9', d: 'Beine mit den Armen umfassen und mit dem ganzen Körper vor- und zurückschaukeln, über den gesamten Rücken rollen; auch seitlich von rechts nach links.' });
K({ id: 'meru_wakrasana', n: 'Drehsitz (Variation)', sa: 'Meru Wakrasana', c: 'mobi_sitz', lv: 1, m: 1, pose: 'sit_twist', t: 'ruecken loslassen', x: 'osteoporose', st: 'hatha', src: 'Modul 2, S. 10', d: 'Sitzende Wirbelsäulendrehung als Mobilisation im Wirbelsäulenprogramm.' });
K({ id: 'shava_udara', n: 'Dreh-Dehnlage (dynamisch)', sa: 'Shava Udarakarshanasana', c: 'boden', lv: 1, m: 1.5, pose: 'twist_supine', t: 'ruecken loslassen ruhe', x: 'osteoporose', st: 'hatha', src: 'Modul 2, S. 10', d: 'Dynamische Drehung in Rückenlage: Beine im Wechsel zur Seite ablegen, Schultern bleiben am Boden.' });
K({ id: 'ardha_matsyendrasana', n: 'Halber Drehsitz', sa: 'Ardha Matsyendrasana', c: 'boden', lv: 2, m: 1.5, pose: 'sit_twist', t: 'ruecken huefte loslassen', x: 'ruecken osteoporose', st: 'hatha yin', src: 'Modul 2, S. 10; Modul 7, S. 49–52', d: 'Aufrechter Sitz mit aufgestelltem Bein, Drehung zum aufgestellten Bein, beide Gesäßhälften behalten Bodenkontakt. Im Skript als gutes Beispiel für das Apana-Prinzip genannt.', g: 'fsit' });
K({ id: 'makarasana', n: 'Krokodil – Drehdehnlage', sa: 'Makarasana', c: 'boden', lv: 1, m: 1.5, pose: 'twist_supine', t: 'ruecken loslassen ruhe', x: 'osteoporose', st: 'hatha', src: 'Modul 7, S. 53–56', d: 'Liegende Drehung (auch Nakrasana / Jathara Parivartanasana genannt): Knie zur Seite ablegen, Schultern am Boden; regt Leber, Milz und Bauchspeicheldrüse an.' });
// Sonnengruß, Mondgruß, Krieger-Serie (Modul 1 und 2)
K({ id: 'ashwa', n: 'Sprinter', sa: 'Ashwa Sanchalanasana', c: 'stand', lv: 1, m: 1, pose: 'lunge', t: 'kraft huefte energie', x: 'knie handgelenk', st: 'hatha vinyasa', src: 'Modul 1, S. 75', d: 'Tiefer Ausfallschritt mit den Händen am Boden (Schritt im Sonnengruß): dehnt Oberschenkel und Hüftbeuger, aktiviert Waden und hintere Oberschenkel, Rücken lang, Blick nach oben.' });
K({ id: 'mondgruss', n: 'Mondgruß', sa: 'Chandra Namaskar', c: 'flow', lv: 1, m: 4, pose: 'side_bend', t: 'ruhe energie huefte', x: 'knie schwindel', st: 'hatha', src: 'Modul 1, S. 80–81', d: 'Dynamische Übungsfolge für innere Ruhe mit seitlichen Bewegungen (u. a. Dreieck, Pyramide, tiefer seitlicher Ausfallschritt). Gegenstück zum aktiven Sonnengruß.' });
K({ id: 'dancing_warrior', n: 'Sonnengruß – tanzender Krieger', c: 'flow', lv: 2, m: 4, pose: 'warrior1', t: 'energie kraft', x: 'knie schulter handgelenk ruecken blutdruck schwindel', st: 'vinyasa hatha', src: 'Modul 2, S. 27–42', d: 'Sonnengruß-Variante, in der die Krieger-Haltungen fließend miteinander verbunden werden.' });
K({ id: 'skandasana', n: 'Seitlicher tiefer Ausfallschritt', sa: 'Skandasana', c: 'stand', lv: 2, m: 1, pose: 'goddess', t: 'huefte kraft', x: 'knie huefte', st: 'hatha', src: 'Modul 1, S. 81 (Mondgruß)', d: 'Weiter Stand, Gewicht in ein tief gebeugtes Bein verlagern, anderes Bein gestreckt; Teil des Mondgrußes.' });
K({ id: 'pyramide', n: 'Pyramide', sa: 'Parsvottanasana', c: 'stand', lv: 2, m: 2, pose: 'pyramid', t: 'ruecken huefte wurzel loslassen', x: 'ruecken blutdruck', st: 'hatha chakra', src: 'Modul 3, S. 38–40', d: 'Beine gestreckt, Oberkörper lang zum vorderen Bein gestreckt; steht im Skript für eine stabile, unerschütterliche Basis.', w: 'Bei Rückenverletzung oder zu hohem Blutdruck verzichten.' });
K({ id: 'dreieck', n: 'Dreieck', sa: 'Trikonasana', c: 'stand', lv: 2, m: 2, pose: 'triangle', t: 'herz huefte ruecken kraft', x: 'ruecken huefte blutdruck schwindel', st: 'hatha', src: 'Modul 1, S. 81; Modul 3 (Trikonasana)', d: 'Weiter Stand, Oberkörper seitlich über das vordere Bein, unterer Arm am Bein, oberer Arm zur Decke – öffnet Brustkorb und Beinrückseite.' });
K({ id: 'halbmond_chandra', n: 'Halbmond – Seitbalance', sa: 'Ardha Chandrasana', c: 'balance', lv: 3, m: 2, pose: 'half_moon', t: 'balance kraft', x: 'schwindel huefte knie blutdruck', st: 'chakra hatha', src: 'Modul 3, S. 86–88', d: 'Stand auf einem Bein, die Körperseite bildet vom Fußknöchel bis zum Scheitel eine gerade Linie. Stabilität vorher z. B. mit Krieger-Haltungen trainieren.' });
K({ id: 'halbmond_chakra', n: 'Halbrad – stehende Rückbeuge', sa: 'Ardha Chakrasana', c: 'flow', lv: 2, m: 1, pose: 'backbend', t: 'herz licht energie', x: 'ruecken nacken schwindel', st: 'chakra hatha', src: 'Modul 3, S. 84–88', d: 'Stehende Rückbeuge mit den Händen in den Hüften oder am Rücken, Brustbein hebt sich; wird im Skript dem Solarplexus-Chakra zugeordnet.' });
K({ id: 'krieger3', n: 'Krieger III', sa: 'Virabhadrasana III', c: 'balance', lv: 3, m: 2, pose: 'warrior3s', t: 'balance kraft energie', x: 'schwindel knie blutdruck', st: 'hatha vinyasa', src: 'Modul 10, S. 7 (als Vorbereitung genannt)', d: 'Einbeinige Balance mit waagerechtem Oberkörper und gestrecktem hinteren Bein.', e: 'krieger3_unt' });
K({ id: 'parivrtta_parsva', n: 'Gedrehter seitlicher Winkel', sa: 'Parivrtta Parsvakonasana', c: 'stand', lv: 2, m: 2, pose: 'lunge', t: 'ruecken kraft huefte loslassen', x: 'knie ruecken schwindel', st: 'hatha', src: 'Modul 7, S. 57–58', d: 'Ausfallschritt mit Drehung zum vorderen Bein: kräftigt und dehnt Beine, Knie und Fußgelenke, dehnt die Leisten, mobilisiert die Wirbelsäule, weitet Brust und Schultern.', w: 'Bei Kopf- und Knieschmerzen vermeiden.' });
K({ id: 'parivrtta_trikona', n: 'Gedrehtes Dreieck', sa: 'Parivrtta Trikonasana', c: 'stand', lv: 2, m: 2, pose: 'triangle', t: 'ruecken huefte loslassen', x: 'ruecken huefte blutdruck schwindel', st: 'hatha', src: 'Modul 7, S. 59–60', d: 'Gestrecktes vorderes Bein, Wirbelsäule lang, Drehung des Oberkörpers zum vorderen Bein; die Hand kann am Boden oder auf einem Block ruhen.', e: 'dreieck' });
K({ id: 'parivrtta_utkata', n: 'Gedrehte Stuhlhaltung (Machtvolle Haltung)', sa: 'Parivrtta Utkatasana', c: 'stand', lv: 2, m: 2, pose: 'chair', t: 'kraft ruecken loslassen', x: 'knie ruecken schulter', st: 'hatha', src: 'Modul 7, S. 61–63', d: 'Aus der Stuhlhaltung mit den Händen im Namaskar Mudra seitlich eindrehen: kräftigt Beine und seitliche Brustmuskeln, regt durch die Rotation die Verdauung an.', e: 'utkatasana' });
K({ id: 'parivrtta_chandra', n: 'Gedrehter Halbmond', sa: 'Parivrtta Ardha Chandrasana', c: 'balance', lv: 3, m: 2, pose: 'half_moon', t: 'balance ruecken', x: 'schwindel knie huefte ruecken', st: 'hatha', man: true, src: 'Modul 7, S. 64–66', d: 'Einbeinige Balance aus der halben Vorbeuge mit Drehung; das hintere Bein wird gestreckt angehoben.' });
K({ id: 'eka_pada_utkata', n: 'Einbeinige Stuhlhaltung', sa: 'Eka Pada Utkatasana', c: 'balance', lv: 2, m: 2, pose: 'chair', t: 'balance kraft huefte', x: 'knie huefte schwindel', st: 'hatha', src: 'Modul 7, S. 35–36', d: 'Aus der Stuhlhaltung ein Fußgelenk auf den Oberschenkel legen, Hände im Anjali Mudra: verbessert Rumpfkraft und Gleichgewicht, öffnet die Hüften, stabilisiert die Kniegelenke, schult die Konzentration (Drishti).', e: 'utkatasana' });
K({ id: 'garudasana', n: 'Adler', sa: 'Garudasana', c: 'balance', lv: 3, m: 2, pose: 'eagle', t: 'balance schulter', x: 'knie schulter schwindel', st: 'hatha adv', src: 'Modul 10, S. 7–8', d: 'Anspruchsvolle Standhaltung mit verschlungenen Armen und Beinen: stärkt Knöchel, Waden und Füße, öffnet Schultern und oberen Rücken, verbessert Konzentration und Gleichgewicht.', w: 'Bei Verletzungen oder Beschwerden an Knie oder Knöchel unbedingt vermeiden.', e: 'adlerarme' });
K({ id: 'hasta_padangustha', n: 'Standwaage mit Hand-zu-Fuß-Streckung', sa: 'Utthita Hasta Padangusthasana', c: 'balance', lv: 3, m: 2, pose: 'hand_to_toe', t: 'balance kraft huefte', x: 'knie huefte schwindel ruecken', st: 'adv', man: true, src: 'Modul 10, S. 9–10', d: 'Stand auf einem Bein, das andere Bein wird gestreckt gehalten: stärkt Beine, Knöchel und Rumpf, dehnt Oberschenkelrückseite und Hüften, schult Kraft und Koordination.', w: 'Bei Verletzungen oder Beschwerden an Knöcheln, Knien oder Oberschenkeln vermeiden.' });
K({ id: 'bird_of_paradise', n: 'Bird of Paradise', sa: 'Svarga Dvijasana', c: 'balance', lv: 3, m: 2, pose: 'bird', t: 'balance huefte herz', x: 'knie huefte ruecken schwindel', st: 'adv', man: true, src: 'Modul 10, S. 11–12', d: 'Anspruchsvolle einbeinige Haltung: stärkt Beine, Knöchel und Rumpf, öffnet Hüften und Schultern, dehnt Oberschenkelinnenseiten.', w: 'Bei Verletzungen oder Beschwerden an Knie, Hüften oder unterem Rücken vermeiden.' });
// Vorbeugen, Hüften, Sitzhaltungen (Modul 3, 5, 7)
K({ id: 'upavistha', n: 'Offene Winkelhaltung', sa: 'Upavistha Konasana', c: 'boden', lv: 1, m: 1.5, pose: 'wide_seat', t: 'huefte loslassen ruhe', x: 'knie huefte', st: 'hatha chakra yin', src: 'Modul 3, S. 60–63', d: 'Sitz mit gegrätschten Beinen: öffnet sanft die Beininnenseiten, fördert die Beweglichkeit der Hüfte, stimuliert die Bauchorgane. Kann Ischiasbeschwerden lindern und gilt als gute Übung in der Schwangerschaft.', w: 'Bei Knie- oder Hüftverletzung verzichten.', g: 'fsit' });
K({ id: 'paschimottanasana', n: 'Sitzende Vorbeuge', sa: 'Paschimottanasana', c: 'boden', lv: 2, m: 1.5, pose: 'seated_fold', t: 'loslassen ruhe ruecken', x: 'ruecken osteoporose', st: 'hatha chakra', src: 'Modul 3, S. 64–67; Modul 5, S. 34–36', d: 'Vorbeuge über die gestreckten Beine im Sitz: dehnt die Körperrückseite, wirkt beruhigend und nach innen gerichtet.', g: 'fsit' });
K({ id: 'virasana', n: 'Heldensitz', sa: 'Virasana', c: 'boden', lv: 2, m: 1.5, pose: 'hero', t: 'huefte ruhe', x: 'knie huefte', st: 'hatha', src: 'Modul 7, S. 23–26', d: 'Sitz zwischen den Fersen; dehnt Oberschenkelvorderseite. Vorbereitung durch Dehnen des Quadrizeps empfohlen.', w: 'Bei Knieproblemen nur mit viel Vorsicht oder gar nicht.', g: 'fsit' });
K({ id: 'supta_virasana', n: 'Liegender Held', sa: 'Supta Virasana', c: 'boden', lv: 3, m: 1.5, pose: 'supta_hero', t: 'huefte herz', x: 'knie huefte ruecken', st: 'hatha', man: true, src: 'Modul 7, S. 23–26', d: 'Aus dem Heldensitz nach hinten zurücklehnen; intensive Dehnung der Oberschenkelvorderseite.', w: 'Bei Knieproblemen nur mit viel Vorsicht oder gar nicht.', e: 'virasana' });
K({ id: 'agnistambha', n: 'Feuerholzstellung', sa: 'Agnistambhasana', c: 'boden', lv: 2, m: 2, pose: 'sit', t: 'huefte loslassen', x: 'knie huefte', st: 'hatha yin', src: 'Modul 7, S. 27–28', d: 'Beide Schienbeine übereinander gestapelt (auch Doppelter Taubensitz / Viereck): intensive Dehnung von Gesäß-, Lenden- und Hüftregion.', g: 'fsit' });
K({ id: 'gomukhasana', n: 'Kuhsitz', sa: 'Gomukhasana', c: 'boden', lv: 2, m: 1.5, pose: 'gomukhasana_sit', t: 'schulter huefte herz', x: 'knie huefte schulter', st: 'hatha yin', src: 'Modul 7, S. 29–30', d: 'Beine übereinander, ein Arm von oben und einer von unten zusammenführen: dehnt Brust und Schultern, verbessert die Haltung des Oberkörpers, macht Hüften, Becken und Knie geschmeidig.', g: 'fsit' });
K({ id: 'malasana', n: 'Tiefe Hocke (Girlanden-Haltung)', sa: 'Malasana', c: 'boden', lv: 2, m: 1.5, pose: 'malasana', t: 'wurzel huefte loslassen', x: 'knie huefte schwindel', st: 'hatha yin natal', src: 'Modul 7, S. 31–34', d: 'Hocke mit Füßen etwas breiter als hüftbreit, Fersen am Boden (sonst unterlegen): entspannt Beckenboden und Organe, regt die Verdauung an, erleichtert die Geburt – Schwangere sollten sie regelmäßig üben.', g: 'fsit' });
K({ id: 'hanumanasana', n: 'Spagat', sa: 'Hanumanasana', c: 'boden', lv: 3, m: 2, pose: 'splits', t: 'huefte', x: 'huefte knie ruecken', st: 'hatha', man: true, src: 'Modul 7, S. 37–42', d: 'Der „Affe“: Beine nach vorn und hinten gestreckt. Das Skript beschreibt ausführliche Vorbereitungsasanas (u. a. Uttanasana, Hund).', g: 'fsit', e: 'ardha_hanumanasana' });
K({ id: 'ardha_hanumanasana', n: 'Halber Spagat', sa: 'Ardha Hanumanasana', c: 'boden', lv: 2, m: 1.5, pose: 'half_splits', t: 'huefte loslassen', x: 'huefte knie', st: 'hatha', src: 'Modul 7, S. 37–42 (Vorbereitung)', d: 'Vorbeuge über das gestreckte vordere Bein aus dem Ausfallschritt; dehnt die hintere Beinlinie.', g: 'fsit' });
K({ id: 'eidechse', n: 'Eidechse', sa: 'Utthan Pristhasana', c: 'boden', lv: 2, m: 2, pose: 'lizard', t: 'huefte loslassen', x: 'knie huefte', st: 'hatha yin', src: 'Modul 7, S. 17–20', d: 'Tiefer Ausfallschritt, beide Hände innen neben dem vorderen Fuß: öffnet die Hüfte; auf Fuß-, Knie- und Hüftwinkel achten.', g: 'quad' });
K({ id: 'happy_baby', n: 'Happy Baby', sa: 'Ananda Balasana', c: 'boden', lv: 1, m: 1.5, pose: 'happy_baby', t: 'huefte loslassen ruhe', x: 'nacken ruecken huefte', st: 'hatha yin', src: 'Modul 7, S. 21–22', d: 'Rückenlage, Füße außen greifen, Knie weiter als der Oberkörper öffnen: öffnet und entspannt Hüften und Becken, bringt Länge in die Wirbelsäule, wirkt stressreduzierend.', w: 'Bei HWS- und LWS-Beschwerden vorsichtig (Gurt für Anfänger möglich).', g: 'supine' });
K({ id: 'taube', n: 'Taube', sa: 'Rajakapotasana', c: 'boden', lv: 2, m: 2, pose: 'pigeon', t: 'huefte herz loslassen', x: 'knie huefte', st: 'hatha', src: 'Modul 5, S. 42–44', d: 'Ein Bein vorn gebeugt, das andere nach hinten gestreckt: tiefe Hüftöffnung mit Rückbeuge.', g: 'fsit' });
K({ id: 'schlafender_schwan', n: 'Schlafender Schwan', sa: 'Kapotasana II', c: 'boden', lv: 2, m: 2, pose: 'swan', t: 'huefte loslassen ruhe', x: 'knie huefte', st: 'hatha yin', src: 'Modul 5, S. 45; Modul 7, S. 103', d: 'Rotierte halbe Taubenpose, Oberkörper auf den Unterarmen oder vorgebeugt abgelegt: tiefe Dehnung der äußeren Hüfte.', g: 'fsit' });
K({ id: 'fliegende_taube', n: 'Fliegende Taube', sa: 'Eka Pada Galavasana', c: 'balance', lv: 3, m: 1.5, pose: 'crow', t: 'kraft balance huefte', x: 'handgelenk schulter huefte knie', st: 'adv', man: true, src: 'Modul 5, S. 46; Modul 7, S. 36', d: 'Armbalance aus der Taubenposition (Bein auf dem Oberarm).' });
K({ id: 'kurmasana', n: 'Schildkröte', sa: 'Kurmasana', c: 'boden', lv: 3, m: 1.5, pose: 'turtle', t: 'loslassen ruhe huefte', x: 'ruecken knie huefte', st: 'hatha', man: true, src: 'Modul 5, S. 52–55', d: 'Beine gegrätscht, Oberkörper nach vorn unter den Beinen: Rückzug der Sinne; regt Magen, Leber und Bauchspeicheldrüse an. Die offene Winkelhaltung zeigt, ob der Körper bereit ist.', e: 'upavistha', g: 'fsit' });
// Rückbeugen und Umkehrhaltungen (Modul 3, 5, 9, 10)
K({ id: 'dhanurasana', n: 'Bogen', sa: 'Dhanurasana', c: 'boden', lv: 2, m: 1.5, pose: 'bow', t: 'herz kraft energie', x: 'ruecken nacken blutdruck', st: 'chakra hatha', src: 'Modul 3, S. 73–78', d: 'Bauchlage, Füße von hinten greifen, Brust und Beine heben: kombiniert die Wirkungen von Kobra und Heuschrecke, streckt Nerven, Sehnen und Muskeln der ganzen Wirbelsäule.', g: 'prone', e: 'shalabasana' });
K({ id: 'shalabasana', n: 'Heuschrecke', sa: 'Shalabasana', c: 'boden', lv: 2, m: 1.5, pose: 'locust', t: 'kraft ruecken herz', x: 'ruecken', st: 'hatha', src: 'Modul 5, S. 17–18', d: 'Bauchlage, Brust und Beine heben: streckt die Wirbelsäule, öffnet und dehnt die Körpervorderseite; der Druck auf den Bauch massiert die Bauchorgane.', g: 'prone', e: 'sphinx' });
K({ id: 'urdhva_mukha', n: 'Heraufschauender Hund', sa: 'Urdhva Mukha Svanasana', c: 'boden', lv: 2, m: 1.5, pose: 'updog', t: 'herz energie', x: 'handgelenk ruecken schulter', st: 'hatha vinyasa', src: 'Modul 5, S. 15–16', d: 'Rückbeuge mit gestreckten Armen, Oberschenkel angehoben; Übergang im Sonnengruß.', g: 'prone', e: 'kobra' });
K({ id: 'ustrasana', n: 'Kamel', sa: 'Ustrasana', c: 'boden', lv: 2, m: 1.5, pose: 'camel', t: 'herz licht energie', x: 'ruecken nacken blutdruck schwindel', st: 'chakra hatha', src: 'Modul 3 (Teil 2), S. 28–34', d: 'Kniende Rückbeuge, die den Brustraum öffnet; im Skript auch emotional als Gegenbewegung zur schützend nach vorn gebeugten Haltung beschrieben. Typische Fehler werden erläutert.', g: 'quad' });
K({ id: 'urdhva_dhanurasana', n: 'Rad', sa: 'Urdhva Dhanurasana', c: 'boden', lv: 3, m: 1.5, pose: 'wheel', t: 'herz energie kraft', x: 'handgelenk schulter ruecken nacken blutdruck', st: 'chakra adv', man: true, src: 'Modul 3, S. 79–83; Modul 10, S. 5', d: 'Tiefe Rückbeuge im Hochstütz. Im Skript als fortgeschrittene Praxis beschrieben, die sichere Ausführung und sorgfältige Vorbereitung braucht.', w: 'Fortgeschrittene Haltung – gründlich vorbereiten.', e: 'bruecke', g: 'supine' });
K({ id: 'camatkarasana', n: 'Wild Thing', sa: 'Camatkarasana', c: 'boden', lv: 3, m: 1.5, pose: 'wheel', t: 'herz energie', x: 'handgelenk schulter ruecken', st: 'chakra', man: true, src: 'Modul 3 (Teil 2), S. 21–27', d: 'Seitliche, offene Rückbeuge aus dem Seitstütz mit Fuß hinter dem Körper.', g: 'prone' });
K({ id: 'adho_mukha', n: 'Herabschauender Hund', sa: 'Adho Mukha Svanasana', c: 'boden', lv: 1, m: 1.5, pose: 'downdog', t: 'ruecken energie kraft', x: 'handgelenk schulter blutdruck', st: 'hatha vinyasa', src: 'Modul 1, S. 73–74; Modul 5, S. 27–30', d: 'Hauptasana des Sonnengrußes, zählt zu Umkehrhaltungen und Vorbeugen; gut für Übergänge und Vinyasa-Flows. Hände aktiv in den Boden schieben, unterer Rücken hängt nicht durch.', g: 'quad' });
K({ id: 'anjaneyasana', n: 'Halbmond-Ausfallschritt', sa: 'Anjaneyasana', c: 'stand', lv: 1, m: 1.5, pose: 'crescent', t: 'huefte kraft licht', x: 'knie schulter', st: 'hatha vinyasa', src: 'Modul 5, S. 19–20', d: 'Ausfallschritt aus dem Vierfüßler oder Hund, beide Arme mit nach oben zeigenden Daumen über den Kopf: dehnt Hüftbeuger, öffnet Brust und Schultern.', e: 'ausfall_klein' });
K({ id: 'phalakasana', n: 'Planke', sa: 'Phalakasana', c: 'kraft', lv: 2, m: 3, pose: 'plank_hi', t: 'kraft energie', x: 'handgelenk schulter ruecken blutdruck osteoporose', st: 'hatha vinyasa', src: 'Modul 1, S. 69; Modul 9, S. 13–14', d: 'Stützhaltung: stärkt die gesamte Körpermuskulatur, Schultern über den Handgelenken, Spannung im ganzen Körper, Rücken und Beine bilden eine Linie.', w: 'Bei starken Rückenproblemen, Bluthochdruck oder Herzproblemen Knie ablegen.', how: 'Schultern über die Handgelenke, Bauch, Gesäß und Beine aktiv, Körper als gerade Linie.', ev: 'Knie ablegen (einfachere Variante).', reps: '', h: 'chaturanga' });
K({ id: 'chaturanga', n: 'Viergliedrige Stabstellung', sa: 'Chaturanga Dandasana', c: 'kraft', lv: 3, m: 3, pose: 'chatur', t: 'kraft energie', x: 'handgelenk schulter ruecken blutdruck osteoporose', st: 'hatha vinyasa', man: true, src: 'Modul 1, S. 70; Modul 9, S. 17–18', d: 'Aus der Planke die Ellbogen eng am Körper beugen, ohne ins Hohlkreuz zu kommen; Körper bleibt wie ein Stock gerade. Stark energetisierend.', how: 'Aus der Planke Ellbogen langsam beugen, eng am Oberkörper, kein Hohlkreuz.', ev: 'Knie ablegen oder in der Planke bleiben.', reps: '', e: 'phalakasana' });
K({ id: 'vasisthasana', n: 'Seitstütz', sa: 'Vasisthasana', c: 'kraft', lv: 3, m: 3, pose: 'sideplank', t: 'kraft balance', x: 'handgelenk schulter ruecken', st: 'adv', man: true, src: 'Modul 9, S. 15–16', d: 'Seitlicher Stütz auf einer Hand mit gestreckten Beinen.', how: 'Auf einer Hand und dem Fußrand stützen, Körper bildet eine Linie.', ev: 'Unteres Knie ablegen.', reps: '' });
K({ id: 'kakasana', n: 'Krähe', sa: 'Kakasana', c: 'balance', lv: 3, m: 1.5, pose: 'crow', t: 'kraft balance', x: 'handgelenk schulter schwindel', st: 'adv', man: true, src: 'Modul 9, S. 19–22', d: 'Armbalance aus der tiefen Hocke; Kissen vor den Händen und ein Klotz unter den Fersen können Sicherheit geben.' });
K({ id: 'sirsasana', n: 'Kopfstand', sa: 'Sirsasana', c: 'boden', lv: 3, m: 2, pose: 'headstand', t: 'balance energie', x: 'nacken ruecken blutdruck schwindel osteoporose schulter', st: 'chakra adv', man: true, src: 'Modul 3 (Teil 2), S. 48–58; Modul 9, S. 27', d: 'Als „König der Asanas“ bezeichnet: regt Durchblutung und Hirntätigkeit an, schult das Gleichgewicht. Bei ungenauer Ausführung belastet er die Halswirbelsäule stark.', w: 'Halswirbelsäule schützen – nur mit sorgfältiger Vorbereitung.', h: 'mukta_hasta', g: 'inv' });
K({ id: 'mukta_hasta', n: 'Freihändiger Kopfstand', sa: 'Mukta Hasta Shirshasana', c: 'boden', lv: 3, m: 2, pose: 'headstand', t: 'balance', x: 'nacken ruecken blutdruck schwindel osteoporose schulter', st: 'adv', man: true, src: 'Modul 3 (Teil 2), S. 56', d: 'Kopfstand mit abgelegten Armen (ohne Handunterstützung).', e: 'sirsasana', g: 'inv' });
K({ id: 'sarvangasana', n: 'Schulterstand', sa: 'Salamba Sarvangasana', c: 'boden', lv: 3, m: 2, pose: 'shoulderstand', t: 'ruhe', x: 'nacken ruecken blutdruck schwindel osteoporose schulter', st: 'chakra hatha', man: true, src: 'Modul 3 (Teil 2), S. 12–15; Modul 9, S. 27', d: 'Zählt zu den 84 Grundasanas und eignet sich zur Regeneration, auch kurz vor dem Zubettgehen.', w: 'Nur mit sorgfältiger Vorbereitung; Nacken schützen.', h: 'niralamba', g: 'inv' });
K({ id: 'niralamba', n: 'Schulterstand ohne Unterstützung', sa: 'Niralamba Sarvangasana', c: 'boden', lv: 3, m: 1.5, pose: 'shoulderstand', t: 'balance', x: 'nacken ruecken blutdruck schwindel osteoporose schulter', st: 'chakra', man: true, src: 'Modul 3 (Teil 2), S. 16', d: 'Schulterstand ohne Handunterstützung am Rücken.', e: 'sarvangasana', g: 'inv' });
K({ id: 'halasana', n: 'Pflug', sa: 'Halasana', c: 'boden', lv: 3, m: 1.5, pose: 'plow', t: 'ruecken loslassen', x: 'nacken ruecken blutdruck schwindel osteoporose', st: 'chakra hatha', man: true, src: 'Modul 3 (Teil 2), S. 8–11', d: '„Königin der Asanas“: dehnt den Ischiasnerv, wirkt befreiend auf den unteren Rücken und spricht Körper und Geist an.', e: 'halasana_wand', g: 'inv' });
K({ id: 'matsyasana', n: 'Fisch', sa: 'Matsyasana', c: 'boden', lv: 2, m: 1.5, pose: 'heart_supine', t: 'herz licht atem', x: 'nacken ruecken blutdruck osteoporose', st: 'chakra hatha', src: 'Modul 3 (Teil 2), S. 17–20', d: 'Rückbeuge in Rückenlage mit gehobenem Brustkorb: harmonisiert die Schilddrüse, löst Verspannungen in Schultern und Rücken, stärkt den oberen Rücken.', w: 'Nicht geeignet bei Schwangerschaft, Brüchen, starken Rückenproblemen, Herzkrankheiten oder Magengeschwüren.', g: 'supine' });
K({ id: 'viparita_karani', n: 'Siegel der Umkehr', sa: 'Viparita Karani', c: 'boden', lv: 2, m: 2, pose: 'viparita', t: 'ruhe energie', x: 'nacken blutdruck schwindel', st: 'hatha', src: 'Modul 9, S. 31–32', d: 'Rückenlage, Beine heben, Hände stützen den unteren Rücken: Asana und zugleich Mudra, wirkt als sanfte Umkehrhaltung.', g: 'inv' });
K({ id: 'pincha', n: 'Unterarmstand', sa: 'Pincha Mayurasana', c: 'boden', lv: 3, m: 2, pose: 'forearm', t: 'kraft balance', x: 'schulter nacken blutdruck schwindel handgelenk', st: 'adv', man: true, src: 'Modul 9, S. 33–35', d: 'Umkehrhaltung („Haltung des Pfaus“) auf den Unterarmen; braucht viel Kraft in Schultern und Körpermitte, Aufwärmen und Öffnen sind wichtig. Der Delphin dient als Vorübung.', g: 'inv' });
K({ id: 'vrishikasana', n: 'Skorpion', sa: 'Vrishikasana', c: 'boden', lv: 3, m: 1.5, pose: 'scorpion', t: 'kraft balance', x: 'schulter nacken ruecken blutdruck schwindel', st: 'adv', man: true, src: 'Modul 9, S. 36', d: 'Unterarmstand mit Rückbeuge, Füße nähern sich dem Kopf.', e: 'pincha', g: 'inv' });
K({ id: 'handstand', n: 'Handstand', sa: 'Adho Mukha Vrksasana', c: 'boden', lv: 3, m: 1.5, pose: 'handstand', t: 'kraft balance', x: 'handgelenk schulter nacken blutdruck schwindel', st: 'adv', man: true, src: 'Modul 9, S. 39', d: 'Umkehrhaltung auf den Händen; das Skript behandelt auch den Umgang mit der Angst vor dem Handstand.', g: 'inv' });
// Yin Yoga (Modul 7, Elemente)
const YIN = (id, n, sa, pose, t, src, d, o) => K(Object.assign({ id, n, sa, c: 'boden', lv: 1, m: 3, pose, t, st: 'yin', src, d, g: 'supine', sv: !!sa }, o || {}));
YIN('sattel', 'Sattel', '', 'supta_hero', 'huefte ruhe', 'Modul 7, S. 85–86', 'Yin-Haltung (Erde): dehnt die Oberschenkelvorderseite, die Hüftbeuger und den Bauchraum; mit oder ohne Unterstützung unter den Knien. Haltezeit im Yin Yoga etwa 3–5 Minuten.', { x: 'knie ruecken', lv: 2, g: 'fsit' });
YIN('libelle', 'Libelle', '', 'wide_seat', 'huefte loslassen', 'Modul 7, S. 85–86', 'Yin-Haltung (Erde): Grätsch-Sitz mit Vorbeuge; dehnt Beininnenseiten und Beinrückseiten, die Vorbeuge stimuliert die Bauchorgane; Beine gestreckt oder leicht gebeugt.', { x: 'knie huefte ruecken', g: 'fsit' });
YIN('seehund', 'Seehund / Robbe', '', 'cobra', 'herz', 'Modul 7, S. 85–86', 'Yin-Haltung (Erde): sanfte Rückbeuge in Bauchlage mit gestreckten Armen, dehnt den vorderen Bauchraum.', { x: 'handgelenk ruecken', g: 'prone', e: 'sphinx' });
YIN('schmetterling_vorbeuge', 'Schmetterling mit Vorbeuge', 'Baddha Konasana', 'butterfly_sit', 'huefte loslassen', 'Modul 7, S. 91–92', 'Yin-Haltung (Metall): Schmetterling mit sanfter Vorbeuge und optionaler Drehung des Oberkörpers, öffnet Hüften und seitliche Rumpfbereiche.', { x: 'huefte knie', g: 'fsit', sv: true });
YIN('twisted_roots', 'Gedrehte Wurzeln (Twisted Roots)', '', 'twist_supine', 'ruecken loslassen ruhe', 'Modul 7, S. 91–92', 'Yin-Haltung (Metall): liegende Drehung, die Brustkorb und Bauchraum sanft dehnt; Beinpositionen übereinander gekreuzt oder variiert.', { x: 'osteoporose', e: 'drehung_liegend' });
YIN('drehsitz_liegend', 'Unterstützter liegender Drehsitz', '', 'twist_supine', 'ruecken loslassen ruhe', 'Modul 7, S. 85–86', 'Yin-Haltung (Erde): sanfte Drehung des Oberkörpers, die die Bauchorgane massiert; verschiedene Beinpositionen und Unterstützung unter den Knien möglich.', { x: 'osteoporose' });
YIN('baumeln', 'Baumeln (Dangling)', '', 'fold', 'loslassen ruhe', 'Modul 7, S. 97–98', 'Yin-Haltung (Wasser): hängende Vorbeuge im Stand, Oberkörper locker nach unten sinken lassen.', { x: 'ruecken osteoporose blutdruck schwindel', g: 'stand' });
YIN('nadeloehr', 'Nadelöhr', 'Suchirandhrasana', 'supine_knee', 'huefte loslassen', 'Modul 2, S. 7; Modul 7, S. 103–104', 'Yin-Haltung (Holz): in Rückenlage Knöchel über das gegenüberliegende Knie legen; dehnt intensiv die äußere Hüfte und das Gesäß, die Drehung wirkt sanft auf die Rumpfseiten. Mobilisation der Wirbelsäule durch Rotation.', { x: 'knie huefte' });
YIN('schnuersenkel', 'Schnürsenkel', '', 'sit', 'huefte loslassen', 'Modul 7, S. 103–104', 'Yin-Haltung (Holz): Beine im Sitz übereinander gestapelt, tiefe Dehnung der äußeren Hüfte und des Gesäßes.', { x: 'knie huefte', lv: 2, g: 'fsit' });
YIN('reh', 'Reh', 'Parivritta Merudandasana', 'sit_twist', 'ruecken huefte loslassen', 'Modul 7, S. 103–104', 'Yin-Haltung (Holz): intensive Drehung im Sitz mit gebeugten Beinen zur Seite.', { x: 'knie huefte osteoporose', lv: 2, g: 'fsit' });
YIN('frosch_gedreht', 'Gedrehter Frosch', 'Parivritta Mandukasana', 'anahatasana', 'huefte loslassen', 'Modul 7, S. 103–104', 'Yin-Haltung (Holz): kombiniert die Frosch-Dehnung der Hüften mit einer Drehung.', { x: 'knie huefte', lv: 3, man: true, g: 'quad' });
YIN('umarmende_fluegel', 'Umarmende Flügel', '', 'sit_shoulder', 'schulter herz loslassen', 'Modul 7, S. 109–111', 'Yin-Haltung (Feuer): Arme vor dem Körper umarmend kreuzen; dehnt den oberen Rücken und die Schulterblätter, öffnet sanft den Brustkorb. Im Sitzen oder Liegen.', { x: 'schulter', g: 'fsit' });
YIN('offene_fluegel', 'Offene Flügel', '', 'heart_supine', 'schulter herz', 'Modul 7, S. 109–111', 'Yin-Haltung (Feuer): in Rückenlage Arme seitlich öffnen (ca. 90°): öffnet den Brustkorb und dehnt die Schultervorderseite.', { x: 'schulter', g: 'supine' });
YIN('unterstuetzter_fisch', 'Unterstützter Fisch', '', 'heart_supine', 'herz licht', 'Modul 7, S. 109–111', 'Yin-Haltung (Feuer): Rückbeuge mit Unterstützung unter dem oberen Rücken; öffnet den Brustkorb und dehnt die Halsvorderseite.', { x: 'nacken schulter', g: 'supine' });
YIN('halbe_libelle', 'Halbe Libelle mit Seitbeuge', '', 'janu', 'huefte loslassen', 'Modul 7, S. 109–111', 'Yin-Haltung (Feuer): ein Bein gestreckt, das andere gebeugt; Seitbeuge über das gestreckte Bein dehnt die Beininnenseite und die seitliche Rumpfseite.', { x: 'knie huefte ruecken', g: 'fsit' });
// Beckenboden (Modul 11)
const BEBO = (id, n, pose, t, src, d, o) => K(Object.assign({ id, n, c: 'boden', lv: 1, m: 1.5, pose, t, st: 'natal', src, d, man: true, sv: true }, o || {}));
BEBO('beckenkippen_rl', 'Beckenkippen (Rücken-/Bauchlage)', 'supine_bent', 'ruhe ruecken', 'Modul 11, S. 12', 'Mit der Ausatmung das Schambein Richtung Bauchnabel führen; in Rückenlage die Lendenwirbelsäule gegen die Unterlage drücken, in Bauchlage das Schambein in die Unterlage.', { g: 'supine' });
BEBO('bebo_fahrstuhl', 'Fahrstuhl (Beckenboden)', 'sit', 'ruhe', 'Modul 11, S. 12', 'Im Sitzen die Beckenbodenmuskulatur über drei „Stockwerke“ anspannen – je höher, desto größer die Anspannung.', { g: 'fsit' });
BEBO('bebo_wedel', 'Wedel (Beckenboden)', 'quad_cat', 'ruhe mobi', 'Modul 11, S. 12', 'Im Vierfüßler oder Ellbogenstütz „schwanzwedeln“ nach rechts, links, oben und unten; mit dem Becken Zahlen schreiben oder ein Bild malen.', { g: 'quad', x: 'handgelenk knie' });
BEBO('bebo_seerose', 'Seerose (Beckenboden)', 'sit', 'ruhe loslassen', 'Modul 11, S. 13', 'Sich vorstellen, der Beckenboden öffnet und schließt sich behutsam wie die Blüte einer Seerose – mit der Einatmung öffnen, mit der Ausatmung schließen.', { g: 'fsit' });

// ---------- Anreicherung bestehender Übungen (Kursunterlagen) mit Stilen, Beschreibung und Quelle ----------
// [Stile, Quelle, Beschreibung, Vorsicht, Sanskrit-Korrektur / -Beleg (sv)]
const ENRICH = {
  fuss_reiben: ['hatha'],
  zehen_bewegen: ['hatha', 'Modul 1, S. 37', 'Übung 1 der Pawanmuktasana-Reihen im Langsitz: Zehen beim Einatmen spreizen, beim Ausatmen krallen (5–10 Mal). Die Reihen befreien die Gelenke, dehnen die Muskeln und fördern Durchblutung und Energiefluss.', '', 'Padanguli Naman', true],
  fuss_flex: ['hatha', 'Modul 1, S. 37', 'Übung 2 (Knöchel beugen) im Langsitz: Zehen heranziehen, Fuß ausstrecken im Wechsel mit dem Atem, 5–10 Mal.', '', 'Goolf Naman', true],
  fussgelenk: ['hatha', 'Modul 1, S. 37', 'Übung 3 (Knöchelrotation): Fuß bei aktivem, gestrecktem Bein je 5 Mal im und gegen den Uhrzeigersinn rotieren, Bewegungsgrenze austesten.', '', 'Goolf Chakra', true],
  knie_flex: ['hatha', 'Modul 1, S. 38', 'Übung 4 (Knie beugen) im Langsitz: Fuß heranziehen, Ferse zum Gesäß, mit der Ferse knapp über dem Boden zurück, 5–10 Mal pro Seite.', '', 'Janu Naman', true],
  knie_kreise: ['hatha', 'Modul 1, S. 38', 'Übung 5 (Knie kurbeln): Oberschenkel mit verschränkten Händen halten, Unterschenkel in einem großen Kreis rotieren, 5–10 Mal pro Seite.', '', 'Janu Chakra', true],
  bein_anwinkeln: ['hatha', 'Modul 1, S. 38', 'Übung 6 (halber Schmetterling) im Langsitz: ein Bein angewinkelt auf den Oberschenkel legen, das Knie abwechselnd Richtung Brust und Boden bewegen, 5–10 Mal.', '', 'Ardha Titali Asana', true],
  huefte_kreis: ['hatha', 'Modul 1, S. 39', 'Übung 7 (Hüfte rotieren): angewinkeltes Bein mit dem Knie in Kreisen bewegen, 5–10 Mal in beide Richtungen.', '', 'Shroni Chakra', true],
  schmetterling_sitz: ['hatha chakra', 'Modul 1, S. 39; Modul 3, S. 53–56', 'Dynamisch (Übung 8): Fußsohlen zusammen, Knie mit schnellen kleinen Bewegungen Richtung Boden und Decke, 30–50 Mal. Statisch als Schustersitz: öffnet Hüften und Leisten.', '', 'Poorna Titali Asana / Baddha Konasana', true],
  finger_faust: ['hatha', 'Modul 1, S. 39', 'Übung 9 (Faustschluss): Arme nach vorn, beim Einatmen Finger spreizen, beim Ausatmen zur Faust schließen (Daumen eingerollt), 5–10 Mal.', '', 'Mushtika Bandhana', true],
  haende_flex: ['hatha', 'Modul 1, S. 39', 'Übung 10 (Handgelenk beugen): Arme auf Schulterhöhe, Hand abwechselnd in Extension und Flexion bringen, 5–10 Mal.', '', 'Manibandha Naman', true],
  handgelenk_kreis: ['hatha', 'Modul 1, S. 40', 'Übung 11: Hand fausten (Daumen innen), große Handgelenkskreise bis zum Bewegungsende, je 5–10 Runden.', '', 'Manibandha Chakra', true],
  ellenbogen: ['hatha', 'Modul 1, S. 40', 'Übung 12 (Ellenbogen beugen): Arme auf Schulterhöhe, Handflächen nach oben, Finger an die Schulter legen, abwechselnd Ellenbogen strecken und beugen.', '', 'Kehuni Naman', true],
  schulter_kreis: ['hatha', 'Modul 1, S. 40', 'Übung 13 (Schultern rotieren): Finger auf die Schultern legen, die Ellenbogen kreisen in einem großen Kreis, 5–10 Runden in beide Richtungen.', '', 'Skandha Chakra', true],
  nacken_mobi: ['hatha', 'Modul 1, S. 41', 'Übungen 14–16 im Meditationssitz: Kinn heben und zur Brust senken, Ohr Richtung Schulter, Kopf drehen – Oberkörper bleibt still, 5–10 Mal.', '', 'Greeva Sanchalana', true],
  tadasana: ['hatha vinyasa chakra', 'Modul 1, S. 64–65', 'Bergposition (auch Samasthiti): aufrechter, ruhiger Stand mit gleichmäßig verteiltem Gewicht – Grundhaltung aller stehenden Asanas und Beginn des Sonnengrußes.', '', 'Tadasana', true],
  arme_zur_sonne: ['hatha vinyasa', 'Modul 1, S. 66', 'Stand mit Armen über dem Kopf (zweite Haltung im Sonnengruß): streckt Wirbelsäule und Brustkorb; Bauch und Gesäß bleiben aktiv, damit keine Hohlkreuz entsteht.', '', 'Hasta Uttanasana', true],
  halbe_vorbeuge: ['hatha vinyasa', 'Modul 5, S. 31', 'Halbe Vorbeuge im Stand: Rücken gerade und parallel zum Boden, Blick nach vorn unten.', '', 'Ardha Uttanasana', true],
  vorbeuge: ['hatha vinyasa', 'Modul 1, S. 76; Modul 5, S. 32', 'Tiefe Vorwärtsbeuge aus der Hüfte mit langem Rücken; Schulter- und Kniesehnen dehnen, Kniescheiben anziehen.', 'Bei Rückenproblemen Wirbel für Wirbel aufrichten.', 'Uttanasana', true],
  weite_vorbeuge: ['hatha chakra', 'Modul 3, S. 41; Modul 5, S. 38–40', 'Gegrätschte Vorbeuge im Stand: dehnt Beine und Wirbelsäule, vertieft die Atmung, schult die Koordination und bereitet Beinarbeit in stehenden Haltungen vor.', '', 'Prasarita Padottanasana', true],
  krieger1: ['hatha vinyasa', 'Modul 2, S. 12–16', 'Aus Tadasana Beine weit spreizen, Becken nach vorn ausrichten, vorderes Knie beugen, Arme nach oben: kräftigt Fuß-, Bein-, teils Rumpf- und Armmuskulatur, verbessert die Hüftbeweglichkeit und stärkt das Durchhaltevermögen.', 'Keine Rückbeuge im Oberkörper; Becken nach vorn ausrichten.', 'Virabhadrasana I', true],
  krieger2: ['hatha vinyasa', 'Modul 2, S. 17–20', 'Arme auf einer Linie, vorderes Knie über dem Fuß, Oberkörper aufrecht ohne Drehung: kräftigt Brust, Beine und Arme, öffnet Brust- und Lungenraum.', 'Knie des vorderen Beins nicht nach innen kippen lassen.', 'Virabhadrasana II', true],
  seitwinkel: ['hatha', 'Modul 2, S. 22–25', 'Seitlicher Winkel aus der Krieger-Serie: kräftigt die Beine, öffnet die Hüfte, macht die Wirbelsäule beweglich und stimuliert das Zwerchfell einseitig.', 'Auf die Beckenstellung achten, vorderes Knie nicht über den Fuß hinaus.', 'Utthita Parsvakonasana', true],
  baum: ['hatha chakra', 'Modul 3, S. 34–37', 'Unterstützt die Verwurzelung und Verbindung mit der Welt: stabiler Stand auf einem Bein, Blick auf einen Punkt; zuerst aus der Berghaltung heraus aufbauen.', '', 'Vrksasana', true],
  utkatasana: ['hatha', 'Modul 7, S. 35, 61', 'Stuhlhaltung: Knie beugen, Gesäß zurück, Brustbein aufrichten; kräftigt die Beinmuskulatur und ist Ausgangshaltung für einbeinige und gedrehte Varianten.', '', 'Utkatasana', true],
  goettin: ['natal', 'Modul 11, S. 29 (Göttinnen-Haltung mit Variationen)', 'Weiter Stand mit gebeugten Knien und nach außen gedrehten Füßen; kräftigt Po und Oberschenkel, öffnet die Hüften.', '', 'Utkata Konasana', false],
  adlerarme: ['hatha', 'Modul 10, S. 7 (Armhaltung des Adlers)', 'Arme verschlingen: öffnet oberen Rücken und Schultern – die Armhaltung des Adlers (Garudasana).', '', 'Garudasana (Arme)', true],
  gomukhasana_arme: ['hatha', 'Modul 7, S. 29–30', 'Armhaltung des Kuhsitzes: dehnt Brust- und Schultermuskulatur und verbessert die Haltung des Oberkörpers.', '', 'Gomukhasana (Arme)', true],
  sonnengruss: ['hatha vinyasa', 'Modul 1, S. 44–77; Modul 2, S. 27–42', 'Fließende Folge aus Tadasana, Arme hoch, Vorbeuge, Sprinter, Planke, Kobra, herabschauendem Hund u. a.: wärmt den ganzen Körper auf, bereitet auf Asanas vor, beugt Verletzungen vor.', 'Bei starken Rückenproblemen, Bluthochdruck oder Herzproblemen Varianten wählen.', 'Surya Namaskar', true],
  katze_kuh_vier: ['hatha chakra natal', 'Modul 3, S. 49–52; Modul 11, S. 27', 'Beweglichkeit der Wirbelsäule im Vierfüßlerstand: mit dem Atem zwischen Rundung und Streckung wechseln; auch mit Baby möglich.', '', 'Marjaryasana / Bitilasana', true],
  kindhaltung: ['hatha chakra yin', 'Modul 3, S. 51; Modul 5, S. 48–51', 'Beruhigende Haltung, die den Körper entspannt und regeneriert – zwischen anstrengenden Asanas oder zu Beginn bzw. Ende einer Praxis.', '', 'Balasana', true],
  kind_breit: ['yin hatha', 'Modul 7, S. 97', 'Sanfte Vorbeuge in der Kindhaltung mit gespreizten Knien; Arme vorn oder neben den Beinen; dehnt den unteren Rücken.', '', 'Balasana', true],
  anahatasana: ['hatha yin', 'Modul 5, S. 11–12; Modul 7, S. 109', 'Herzposition (Geschmolzenes Herz): Brustbein und Kinn Richtung Boden, Hände wandern nach vorn; öffnet Brust und Schultern.', 'Unteren Rücken stabilisieren und das Gewicht nicht in die Schultern hängen.', 'Anahatasana', true],
  sphinx: ['hatha yin', 'Modul 2, S. 7; Modul 7, S. 85, 109', 'Sanfte Rückbeuge in Bauchlage auf den Unterarmen; dehnt den vorderen Bauchraum, öffnet Brustkorb und entlastet den unteren Rücken.', '', 'Saral Bhujangasana', true],
  kobra: ['hatha vinyasa', 'Modul 1, S. 71–72; Modul 5, S. 13–14', 'Schlange: Handflächen in den Boden pressen, Rumpf anheben, Beine bleiben aktiv; kräftigt den Rücken, dehnt die Brust.', 'Bei Schilddrüsenüberfunktion, Magengeschwür oder Hernien vermeiden (Variationen nutzen).', 'Bhujangasana', true],
  janu: ['hatha', 'Modul 3 (Teil 2) / Modul 5 (Vorbeugen)', 'Sitzende Vorbeuge mit einem angewinkelten Bein; dehnt Rückseite des gestreckten Beins und den Rücken.', '', 'Janu Sirsasana', true],
  malasana_hoch: ['hatha yin natal', 'Modul 7, S. 31–34', 'Erhöhte tiefe Hocke (Unterlage unter dem Gesäß oder den Fersen): entspannt Beckenboden und Organe, regt die Verdauung an.', '', 'Malasana', true],
  apanasana: ['hatha', 'Modul 2, S. 8 (Päckchenstellung)', 'Knie zur Brust in Rückenlage, bei Bedarf kreisen: entspannt unteren Rücken und Hüften. Im Skript auch als Supta Pawanmuktasana (Päckchenstellung) geführt.', '', 'Apanasana', false],
  bruecke: ['hatha vinyasa natal', 'Modul 3 (Teil 2); Modul 11, S. 28', 'Schulterbrücke: Becken heben, Gesäß aktivieren, kräftigt Gesäß, hintere Beine und Rücken; auch mit Baby als Kräftigung.', '', 'Setu Bandha Sarvangasana', true],
  bruecke_sanft: ['hatha', 'Modul 3 (Teil 2)', 'Schulterbrücke dynamisch mit kleinem Bewegungsumfang.', '', 'Setu Bandha Sarvangasana', true],
  bruecke_halten: ['hatha', 'Modul 3 (Teil 2)', 'Brücke mit Haltephase.', '', 'Setu Bandha Sarvangasana', true],
  schmetterling_liegend: ['hatha chakra yin', 'Modul 3, S. 57–59; Modul 7, S. 91', 'Liegender Schmetterling: öffnet Hüfte und entspannt den Unterleib, öffnet Brustkorb und Schultervorderseite; lässt sich mit Unterstützung und Armvarianten üben.', '', 'Supta Baddha Konasana', true],
  beine_wand: ['hatha yin', 'Modul 9, S. 31', 'Beine an der Wand als sanfte, regenerierende Umkehrhaltung.', '', 'Viparita Karani', true],
  knieheben_tab: ['sen'], knieheben_stand: ['sen'], wirbel_aufrollen: ['sen'], gewichtsverlagerung: ['sen']
};
EX.forEach(e => {
  const r = ENRICH[e.id];
  if (r) {
    e.st = ['sen'].concat(r[0].split(' ').filter(s => s !== 'sen'));
    if (r[1]) e.src = r[1];
    if (r[2]) e.d = r[2];
    if (r[3]) e.w = r[3];
    if (r[4] !== undefined) { e.sa = r[4]; e.sv = r[5] === undefined ? true : r[5]; }
  } else if (!e.script) { e.st = ['sen']; }
});
// Sanskrit-Namen ohne Beleg im Skript (Prüfung gegen den Skripttext): Standardbezeichnung, sv = false
const NICHT_IM_SKRIPT = new Set(['goettin', 'apanasana', 'vierfuessler_diag']);
EX.forEach(e => { if (e.sa) e.sv = !NICHT_IM_SKRIPT.has(e.id); });

// ---------- zusätzliche Atem-/Wahrnehmungsübungen (Pranayama aus Modul 1, 2, 5, 6, 8) ----------
function BK(o) { BR.push(Object.assign({ s: 0, lv: 1, m: 5, x: [], t: [], st: ['hatha'], sv: true, script: true, txt: '', d: '', w: '' }, o, { t: typeof o.t === 'string' ? o.t.split(' ') : (o.t || []), st: typeof o.st === 'string' ? o.st.split(' ') : (o.st || ['hatha']) })); }
BK({ id: 'volle_yogaatmung', n: 'Volle Yogaatmung', k: 'atem', sa: '', t: 'atem ruhe herz', src: 'Modul 1, S. 100–103', d: 'Einatmen in den Bauch, die Flanken und den oberen Brustkorb, Ausatmen in umgekehrter Richtung; im Sitzen oder in Shavasana. Belüftet alle Lungenabschnitte und nutzt das Zwerchfell voll.', txt: 'Atme zuerst in den Bauch, dann in die Flanken und den oberen Brustkorb ein – und in umgekehrter Richtung wieder aus. Drei bis vier volle Atemzüge, dann zur Bauchatmung übergehen.' });
BK({ id: 'brustkorbatmung', n: 'Brustkorbatmung', k: 'atem', t: 'atem herz schulter', src: 'Modul 1, S. 102', d: 'Atmung in Rücken und Flanken (etwa 30 % der Atmung); Zwischenrippenmuskeln heben und senken den Brustkorb. In allen Ausgangsstellungen möglich.', txt: 'Lenke den Atem in die Flanken und in den Rücken. Spüre, wie sich der Brustkorb weitet und wieder senkt.' });
BK({ id: 'feueratem', n: 'Feueratem', k: 'atem', lv: 3, man: true, t: 'energie kraft', st: 'kund', src: 'Modul 2, S. 56', d: 'Beim Ausatmen den Bauch bzw. Nabel einziehen, beim Einatmen weitet er sich; der Atem kann recht schnell ausgeführt werden (Shakti Naam / Kundalini).', w: 'Im Skript als Naam-Yoga-Technik beschrieben; auf das eigene Befinden achten.', txt: 'Atme rhythmisch durch die Nase: Beim Ausatmen den Nabel zur Wirbelsäule ziehen, beim Einatmen löst sich der Bauch von selbst. Nur so lange, wie es angenehm ist.' });
BK({ id: 'langer_atem', n: 'Langer tiefer Atem', k: 'atem', t: 'atem ruhe', st: 'kund', src: 'Modul 2, S. 57–58', d: 'Nutzt die gesamte Lungenkapazität (anders als der Feueratem): Einatmen in Bauch, Brustraum und oberen Brustbereich, Ausatmen mit eingezogenem Nabel und Zwerchfell.', txt: 'Atme tief und langsam ein: Bauch, mittlerer, dann oberer Brustraum. Beim Ausatmen Nabel und Zwerchfell zur Wirbelsäule ziehen, bis die Lungen entleert sind. Wirbelsäule aufrecht.' });
BK({ id: 'dreipunkt_atem', n: '3-Punkte-Atem', k: 'atem', lv: 2, t: 'balance ruhe', st: 'kund', src: 'Modul 2, S. 60', d: 'Einatmen, Halten und Ausatmen in gleich langen Teilen durch die Nase; Zeiten lassen sich steigern bis zu einem Atemzyklus von einer Minute.', txt: 'Atme durch die Nase ein, halte den Atem und atme aus – alle drei Teile gleich lang. Steigere die Zeiten nur langsam und nur so weit, wie es angenehm ist.' });
BK({ id: 'wechselatmung', n: 'Wechselatmung', k: 'atem', lv: 2, sa: 'Nadi Shodhana', t: 'balance ruhe', st: 'hatha', src: 'Modul 5, S. 62–65', d: 'Grundübung des Yoga: wirkt beruhigend bei Stress und belebend bei Müdigkeit; abwechselnd durch das linke und rechte Nasenloch atmen, 4–8 Runden, Vishnu Mudra.', txt: 'Rechte Hand im Vishnu Mudra. Links einatmen, beide Nasenlöcher schließen, rechts ausatmen; rechts einatmen, schließen, links ausatmen. 4–8 Runden, ruhig und ohne Anstrengung.' });
BK({ id: 'chakra_atem', n: 'Chakra-Atem (Quelle des Lichts)', k: 'atem', t: 'ruhe licht wurzel herz', st: 'kund', src: 'Modul 6, S. 46–48', d: 'Atem mit Vorstellung von Licht, das durch die Chakren fließt; bringt den Körper zur Ruhe und eignet sich als Einstimmung. Im Skript mit Wirkungen auf die einzelnen Chakren beschrieben.', txt: 'Sitze aufrecht, Hände in Gyan Mudra oder vor dem Herzen. Atme Licht vom Scheitel bis zum Wurzelchakra ein und stelle dir vor, wie es sich im ganzen Körper ausbreitet.' });
BK({ id: 'kuehlende_atmung', n: 'Kühlende Atmung', k: 'atem', lv: 2, sa: 'Sitali', t: 'ruhe', st: 'kund hatha', sv: true, src: 'Modul 6, S. 49', d: 'Zunge zu einem Röhrchen rollen, kühle Luft einatmen, Zunge zurückziehen und durch die Nase ausatmen.', txt: 'Rolle die Zunge zu einem Röhrchen, atme die kühle Luft ein, ziehe die Zunge zurück und atme durch die Nase aus.' });
BK({ id: 'ujjayi', n: 'Meeresrauschen-Atem', k: 'atem', lv: 2, sa: 'Ujjayi', t: 'ruhe kraft', st: 'hatha kund', src: 'Modul 6, S. 50–53', d: 'Atmung mit leicht verengter Stimmritze und sanftem Rauschen; kann mit Asanas kombiniert werden. Im Skript: trägt zu einem meditativen Zustand bei, günstig bei Asthma und Bluthochdruck.', w: 'Kontraindikation laut Skript: niedriger Blutdruck, starke Introvertiertheit.', txt: 'Verenge beim Atmen die Stimmritze leicht, sodass ein weiches Rauschen wie Meeresrauschen entsteht. Gleichmäßig ein, gleichmäßig aus.' });
BK({ id: 'pranischer_atem', n: 'Pranischer Atem im Stehen', k: 'atem', man: true, t: 'energie kraft wurzel', st: 'kund', src: 'Modul 6, S. 54–56; Modul 8, S. 50–55', d: 'Atemübungen im Stehen mit verschiedenen Handpositionen (z. B. zur Entwicklung von Willens- und Gedächtniskraft); aufrechter Stand, Bracing, Lächeln.', txt: 'Stehe aufrecht, Füße zusammen, Hände wie in der gewählten Position. Atme rhythmisch und bewusst, Kopf gerade, Augen geöffnet.' });
BK({ id: 'king_kong', n: 'King Kong', k: 'atem', man: true, t: 'energie', st: 'kund', src: 'Modul 8, S. 56–57', d: 'Schwungvolle Atemübung im Stehen: Arme als V über den Kopf, in die Hände klatschen, mit „Haaa“ ausatmen. Wirkung laut Skript: stärkt das Immunsystem, weckt die Lebensenergie, fördert die Durchblutung.', txt: 'Stehe schulterbreit, atme ein und führe die Arme über dem Kopf zu einem V. Klatsche zweimal in die Hände und atme mit einem „Haaa“ kraftvoll aus.' });
// Beschreibungen/Quellen der vorhandenen Atemübungen
(function () {
  const M = {
    bauchatmung: [['hatha'], 'Modul 1, S. 101', 'Bewusst in den Bauch atmen, Hände auf dem Bauch; beim Einatmen wölbt er sich, beim Ausatmen zieht er sich zurück. Schultern, Kiefer und Augen entspannen.'],
    verl_ausatmung: [['sen', 'hatha'], 'Stunde 1 und 10 (Kursunterlagen)', 'Die Ausatmung sanft länger werden lassen (z. B. 4 Sekunden ein, 6 aus) – nur so lange, wie es angenehm ist.'],
    atem_arme: [['sen', 'hatha'], 'Kursplan Stunde 7 und 14', 'Arme mit dem Atem führen: mit der Einatmung heben, mit der Ausatmung senken.'],
    atemraeume: [['sen'], 'Kursplan Stunde 7', 'Atemräume (Bauch, Flanken, Brust) bewusst wahrnehmen.'],
    atem_beobachten: [['sen'], 'Kursplan Stunden 6 und 12', 'Atem beobachten, ohne ihn verändern zu müssen.'],
    bodenkontakt: [['sen'], 'Stunde 1 (Einleitung)', 'Spüren, welche Körperteile Kontakt mit dem Boden haben und dass der Boden trägt.'],
    fuss_wahr: [['sen'], 'Stunde 2 (Wahrnehmung im Stehen)', 'Fersen, Fußballen und Zehen spüren, Gewicht langsam verlagern, Füße sanft in den Boden drücken.'],
    koerperreise: [['sen'], 'Kursplan Stunde 3', 'Aufmerksamkeit langsam durch den Körper wandern lassen.'],
    haende_brust: [['sen'], 'Kursplan Stunde 8', 'Hände auf den Brustkorb legen, Wärme und Atem spüren.'],
    dankbarkeit_wahr: [['sen'], 'Kursplan Stunde 9', 'Atem verbunden mit einem Moment der Dankbarkeit.'],
    licht_brust: [['sen'], 'Kursplan Stunde 13', 'Licht im Brustraum visualisieren: mit der Einatmung Weite, mit der Ausatmung Ruhe.'],
    rueckblick: [['sen'], 'Kursplan Stunde 15', 'Rückblick auf die gemeinsame Zeit.']
  };
  BR.forEach(b => {
    const r = M[b.id];
    if (r) { b.st = r[0]; b.src = r[1]; b.d = r[2]; b.script = false; }
    else if (!b.script) b.st = ['sen'];
  });
})();


// „Senioren-Kurs“ ist kein Yogastil – die Eignung für Senioren steht in der Stufe (Spalte „Stufe“)
delete STILE.sen;
EX.forEach(e => { e.st = (e.st || []).filter(x => x !== 'sen'); });
BR.forEach(b => { b.st = (b.st || []).filter(x => x !== 'sen'); });
