/* Textvorlagen: Mustertexte für jeden Textblock der Stunde + eigene Vorlagen
   Platzhalter: {motto} = Titel des Mottos, {kernsatz} = Kernsatz, {fokus} = körperlicher Fokus */
const TX_KINDS = { einl: 'Einleitung', atem: 'Atemübung', mantra: 'Mantra', schluss: 'Schluss', shava: 'Shavasana', nidra: 'Yoga Nidra' };
const TX_MUSTER = [
  { id: 'm_einl_1', kind: 'einl', name: 'Kurz & ruhig', text: 'Herzlich willkommen zu unserer Stunde. Schön, dass du da bist.\n\nDu musst heute nichts leisten und nichts erreichen. Wir üben in deinem Tempo und nur so weit, wie es sich gut anfühlt.\n\nNimm einen Moment wahr, wie du heute hier ankommst: Wie fühlt sich dein Körper an? Wie dein Atem? Du musst nichts verändern – nur bemerken.\n\nUnser Motto heute: „{motto}“ – {kernsatz}' },
  { id: 'm_einl_2', kind: 'einl', name: 'Ankommen im Körper', text: 'Schön, dass wir wieder gemeinsam üben.\n\nSpür zunächst, welche Körperteile Kontakt mit dem Boden haben. Nimm ganz bewusst wahr, dass der Boden dich trägt.\n\nLass deine Schultern weich werden und spüre, wie sich dein Brustkorb mit jedem Atemzug sanft hebt und senkt. Lass Augen, Stirn und Kiefer locker werden.\n\nWenn Gedanken kommen, lass sie vorüberziehen wie Wolken. Kehre immer wieder zum Spüren zurück – zu den Füßen, zum Atem, zum Kontakt mit dem Boden.\n\nUnser Motto heute: „{motto}“ – {kernsatz}' },
  { id: 'm_einl_3', kind: 'einl', name: 'Mit Absicht (Sankalpa)', text: 'Herzlich willkommen. Nimm dir einen Moment, um in dieser Stunde anzukommen.\n\nSchließe, wenn du magst, die Augen und nimm drei bewusste Atemzüge: durch die Nase ein … und mit einem hörbaren Seufzer wieder aus.\n\nVielleicht möchtest du dir für diese Stunde eine kleine Absicht setzen – ein Wort oder ein Gefühl, das dich beim Üben begleitet. Unser Motto kann dir dabei Anregung sein: „{motto}“.\n\n{kernsatz}' },
  { id: 'm_atem_1', kind: 'atem', name: 'Natürlichen Atem beobachten', text: 'Komm in eine bequeme Haltung und schließe, wenn du magst, die Augen.\n\nSpüre deinen Atem, ohne ihn zu verändern. Wo nimmst du ihn am deutlichsten wahr: an den Nasenflügeln, im Brustkorb oder im Bauch?\n\nBeobachte, wie sich Brustkorb und Bauch mit jedem Atemzug bewegen, ohne etwas zu bewerten.\n\nWenn Gedanken abschweifen, ist das in Ordnung. Kehre freundlich zum Atem zurück.\n\nLass die Übung langsam ausklingen und bleibe noch einen Moment im ganz natürlichen Atem.' },
  { id: 'm_atem_2', kind: 'atem', name: 'Kurz: Atem vertiefen', text: 'Setze dich aufrecht hin und lege eine Hand auf den Bauch.\n\nAtme ruhig durch die Nase ein und spüre, wie sich der Bauch sanft hebt. Atme langsam wieder aus und lass die Schultern dabei weich werden.\n\nWiederhole das einige Atemzüge lang in deinem eigenen Rhythmus. Wenn dir schwindelig wird oder es unangenehm ist, kehre zu deinem natürlichen Atem zurück.' },
  { id: 'm_mantra_1', kind: 'mantra', name: 'Einstimmung auf das Mantra', text: 'Sitze aufrecht, die Schultern sind weich, der Atem fließt ruhig. Schließe gern die Augen und stimme dich innerlich ein.\n\nWir singen nun gemeinsam ein Mantra. Es kommt nicht auf einen schönen Ton an, sondern auf das Schwingen. Spüre den Klang in deinem Körper: im Brustkorb, im Hals, im Kopf.\n\nNach dem letzten Klang bleibe still und spüre die Stille, die entsteht.' },
  { id: 'm_mantra_2', kind: 'mantra', name: 'Mantra still wiederholen', text: 'Komm in einen bequemen Sitz und lege die Hände auf Herz oder Bauch.\n\nWiederhole das Mantra innerlich, im Rhythmus deines Atems. Wenn Gedanken kommen, kehre sanft zum Mantra zurück.\n\nLass das Mantra am Ende ausklingen und bleibe noch einen Moment in der Ruhe.' },
  { id: 'm_schluss_1', kind: 'schluss', name: 'Nachspüren & Motto', text: 'Bleibe noch einen Moment ruhig liegen und spüre nach, was die Bewegung in dir bewegt hat: Wärme, Weite, Ruhe, Lebendigkeit?\n\nNimm wahr, wie sich dein Atem verändert hat und wie dein Körper auf der Matte liegt.\n\nLass das Motto „{motto}“ noch einmal nachklingen: {kernsatz}\n\nDann lass die Bewegungen los und geh in die Schlussentspannung.' },
  { id: 'm_schluss_2', kind: 'schluss', name: 'Kurz: Danke', text: 'Komm jetzt zur Ruhe und spüre nach, was die Übungen in dir hinterlassen haben.\n\nDanke deinem Körper für das, was er heute möglich gemacht hat.\n\nWenn du magst, lege eine Hand auf dein Herz und spüre seinen Rhythmus.' },
  { id: 'm_shava_1', kind: 'shava', name: 'Shavasana – kurz', text: 'Nun darfst du es dir ganz bequem machen und in deiner Schlussentspannung ankommen.\n\nLass Beine, Becken und Rücken schwer werden. Lass Schultern, Arme und Hände los. Entspanne Nacken, Gesicht und Stirn.\n\nNimm deinen Atem wahr. Ganz von selbst kommt die Einatmung … und ganz von selbst geht die Ausatmung.\n\nWiederhole innerlich, in deinem eigenen Tempo: „{kernsatz}“\n\nVertiefe nun langsam wieder deinen Atem. Bewege ganz sanft Finger und Zehen. Nimm dir Zeit, bevor du dich wieder aufrichtest.' },
  { id: 'm_shava_2', kind: 'shava', name: 'Shavasana – ausführlich', text: 'Nun darfst du es dir ganz bequem machen und in deiner Schlussentspannung ankommen.\n\nLege dich so hin, dass dein Körper möglichst wenig halten muss. Wenn es angenehmer ist, kannst du die Knie aufstellen oder eine Decke unter die Knie legen.\n\nSchließe gerne die Augen und spüre noch einmal deinen Körper. Du musst nichts mehr tun. Nichts halten. Nichts erreichen.\n\nLass deine Füße schwer werden. Die Zehen, die Fußsohlen, die Fersen … alles darf loslassen. Deine Beine dürfen entspannen: die Waden, die Knie, die Oberschenkel.\n\nEntspanne dein Becken … deinen Bauch … deinen Rücken. Der Boden trägt dich. Lass deine Schultern weich werden. Deine Arme dürfen schwer werden, die Ellenbogen, die Unterarme, die Hände.\n\nEntspanne deinen Nacken … dein Gesicht … die Augen … die Stirn.\n\nNimm deinen Atem wahr. Ganz von selbst kommt die Einatmung … und ganz von selbst geht die Ausatmung.\n\nWiederhole innerlich, in deinem eigenen Tempo: „{kernsatz}“\n…\n\nSpüre, wie schwer und warm dein Körper geworden ist. Du musst nirgendwo hin. Du bist genau hier.\n…\n\nVerweile noch einen Moment in dieser tiefen Ruhe und genieße sie in deinem eigenen Tempo.\n…\n\nVertiefe nun langsam wieder deinen Atem. Bewege ganz sanft Finger und Zehen. Nimm dir Zeit, bevor du dich wieder aufrichtest.' },
  { id: 'm_nidra_1', kind: 'nidra', name: 'Yoga Nidra, ausführlich (8 Stufen)', text: 'Komm in die Rückenlage und richte dich so ein, dass du die nächste Zeit völlig unbewegt liegen kannst. Eine Decke unter dem Kopf oder unter den Knien darf dir helfen. Die Beine liegen etwas auseinander, die Arme neben dem Körper, die Handflächen zeigen nach oben. Schließe die Augen. Ab jetzt bewegst du dich nicht mehr. Höre einfach weiter meiner Stimme zu und bleibe wach.\n\nSpüre, wo dein Körper den Boden berührt: Fersen, Waden, Gesäß, Rücken, Schultern, Hinterkopf. Lass dich vom Boden tragen. Nimm die Geräusche im Raum wahr, ohne ihnen zu folgen. Sie gehören zu diesem Augenblick wie dein Atem.\n\nNun bilde deinen Vorsatz, dein Sankalpa. Ein kurzer, positiver Satz in der Gegenwart, den du dir schon vor der Stunde überlegt hast. Wenn du keinen hast, nimm diesen Gedanken: „{kernsatz}“. Sprich ihn innerlich dreimal mit voller Aufmerksamkeit.\n\nJetzt wandert dein Bewusstsein durch den Körper. Wiederhole innerlich den Namen jedes Körperteils und spüre ihn kurz, ohne ihn zu bewegen. Rechte Hand: Daumen, Zeigefinger, Mittelfinger, Ringfinger, kleiner Finger, Handfläche, Handrücken, Handgelenk, Unterarm, Ellenbogen, Oberarm, Schulter, Achsel, Taille, Hüfte, Oberschenkel, Knie, Wade, Knöchel, Ferse, Fußsohle, Zehen. Nun dieselbe Reise auf der linken Seite. Dann Hinterkopf, Rücken, Gesäß, Schultern. Dann Stirn, Augenbrauen, Augen, Nase, Wangen, Lippen, Kinn, Hals, Brust, Bauch. Spüre am Ende den ganzen Körper zugleich.\n\nNimm nun deinen Atem wahr. Ohne ihn zu lenken, spüre, wie er in den Bauch kommt und wieder geht. Zähle innerlich die Atemzüge rückwärts von zwanzig bis eins: Ich atme ein, zwanzig. Ich atme aus, zwanzig. Ich atme ein, neunzehn. Wenn du dich verzählst, beginne einfach wieder bei zwanzig.\n\nJetzt erinnere dich an Empfindungen und lass sie wieder los: die Schwere des Körpers, dann die Leichtigkeit. Die Wärme der Sonne auf der Haut, dann die Kühle einer Quelle. Ruhe, dann Lebendigkeit. Spüre jeden Pol kurz und ganz, ohne etwas festzuhalten.\n\nNun entsteht vor deinem inneren Auge ein Bild. Ein weiter Raum, ein Ort der Ruhe, vielleicht ein See, ein Wald oder ein Berg. Lass das Bild von selbst kommen und gehen. Du bist nur Beobachterin oder Beobachter. Verweile in der Stille.\n\nKehre jetzt zu deinem Vorsatz zurück und wiederhole ihn dreimal mit voller Aufmerksamkeit: „{kernsatz}“.\n\nNun kommst du langsam zurück. Spüre deinen Atem, den Körper, den Boden unter dir. Höre die Geräusche im Raum. Bewege sanft Finger und Zehen, räkle dich, wenn du magst. Wenn du bereit bist, rolle dich auf die Seite und bleibe noch einen Moment liegen, bevor du dich langsam aufrichtest.' },
  { id: 'm_nidra_2', kind: 'nidra', name: 'Yoga Nidra, kurz', text: 'Komm in die Rückenlage, die Arme neben dem Körper, die Beine leicht geöffnet. Schließe die Augen und werde ganz still. Du musst jetzt nichts mehr tun, außer wach zuzuhören.\n\nSpüre die Auflagefläche deines Körpers und lass dich tragen. Nimm drei tiefe Atemzüge und lass mit jeder Ausatmung etwas mehr los.\n\nSprich nun innerlich deinen Vorsatz: „{kernsatz}“. Wiederhole ihn dreimal ruhig und klar.\n\nLass dein Bewusstsein jetzt durch den Körper wandern: rechte Hand, rechter Arm, rechte Schulter, rechtes Bein, rechter Fuß. Dann links, Hand, Arm, Schulter, Bein, Fuß. Dann Rücken, Gesäß, Bauch, Brust, Hals und das ganze Gesicht. Zuletzt der ganze Körper als Einheit.\n\nBeobachte deinen Atem, wie er von selbst kommt und geht. Folge ihm, ohne ihn zu lenken.\n\nSpüre nun Schwere im ganzen Körper, dann Leichtigkeit. Lass beides kommen und gehen.\n\nWiederhole deinen Vorsatz noch einmal dreimal: „{kernsatz}“.\n\nKehre langsam zurück. Vertiefe den Atem, bewege Finger und Zehen, räkle dich und öffne die Augen, wenn du so weit bist. Nimm dir Zeit, bevor du dich aufrichtest.' },
  { id: 'm_einl_4', kind: 'einl', name: 'Ankommen nach dem Alltag', text: 'Herzlich willkommen. Schön, dass du dir diese Zeit für dich nimmst.\n\nVielleicht kommst du direkt aus einem vollen Tag, mit Gedanken, die noch Termine und Aufgaben sortieren. Das ist in Ordnung. Du darfst alles, was du mitbringst, für diese Stunde am Rand der Matte ablegen.\n\nAtme einmal tief ein und lass mit einem Seufzer alles los, was nicht mit hierher muss.\n\nUnser Motto heute: „{motto}“. {kernsatz}' },
  { id: 'm_einl_5', kind: 'einl', name: 'Mit Neugier üben', text: 'Willkommen zu unserer Stunde. Schön, dass du da bist.\n\nWir üben heute mit Neugier statt mit Ehrgeiz. Es gibt kein richtig und kein falsch, nur dein Spüren. Probiere aus, was sich gut anfühlt, und verändere eine Haltung, wenn sie es nicht tut.\n\nWenn du eine Pause brauchst, nimm sie dir. Die Kindhaltung steht dir jederzeit offen.\n\nUnser Motto heute: „{motto}“. {kernsatz}' },
  { id: 'm_einl_6', kind: 'einl', name: 'Für Einsteigerinnen und Einsteiger', text: 'Herzlich willkommen, besonders, wenn du heute zum ersten Mal dabei bist.\n\nDu brauchst keine Vorkenntnisse und keine Beweglichkeit. Yoga beginnt dort, wo du gerade stehst. Ich zeige dir die Übungen, und du entscheidest, wie weit du gehst.\n\nHöre immer auf deinen Körper: Ein leichtes Dehnen ist angenehm, Schmerz ist ein Zeichen, sofort sanfter zu werden. Du darfst jederzeit aussetzen, trinken oder dich ausruhen.\n\nUnser Motto heute: „{motto}“. {kernsatz}' },
  { id: 'm_einl_7', kind: 'einl', name: 'Mit Blick auf die Jahreszeit', text: 'Herzlich willkommen. Draußen verändert sich die Natur mit den Jahreszeiten, und auch in uns wechseln Energie, Stimmung und Bedürfnisse.\n\nNimm einen Moment wahr, was dein Körper und dein Geist heute brauchen: mehr Ruhe, mehr Wärme, mehr Bewegung oder mehr Weite?\n\nSchenke dir dafür in dieser Stunde bewusst Raum.\n\nUnser Motto heute: „{motto}“. {kernsatz}' },
  { id: 'm_einl_8', kind: 'einl', name: 'Mit körperlichem Fokus', text: 'Schön, dass du da bist. Nimm dir einen Moment, um zu spüren, wie du heute ankommst.\n\nUnser Körper hat heute einen besonderen Schwerpunkt: {fokus}. Wir bereiten ihn behutsam vor und üben in einem Tempo, das dir guttut.\n\nSpüre schon jetzt in diesen Bereich hinein, ohne etwas zu verändern. Wie fühlt er sich an: warm, eng, weit, müde?\n\nUnser Motto heute: „{motto}“. {kernsatz}' },
  { id: 'm_atem_3', kind: 'atem', name: 'Verlängerte Ausatmung', text: 'Setze oder lege dich bequem hin und schließe, wenn du magst, die Augen.\n\nAtme ruhig durch die Nase ein und zähle dabei innerlich bis vier. Atme langsam aus und zähle bis sechs. Die Ausatmung darf länger sein als die Einatmung, ohne Druck.\n\nWiederhole das einige Atemzüge. Wenn die Zahlen nicht passen, wähle ein Verhältnis, das sich angenehm anfühlt.\n\nKehre dann zu deinem natürlichen Atem zurück und spüre nach.' },
  { id: 'm_atem_4', kind: 'atem', name: 'Dreiteiliger Atem', text: 'Komm in einen aufrechten, bequemen Sitz. Eine Hand liegt auf dem Bauch, eine auf dem Brustkorb.\n\nAtme zuerst in den Bauch, lass dann die Rippen weit werden und fülle zuletzt den oberen Brustkorb. Die Ausatmung entleert von oben nach unten, ganz sanft.\n\nBleibe einige Runden dabei und lass den Atem wie eine ruhige Welle fließen. Wenn du dich angestrengt fühlst, atme wieder ganz natürlich.' },
  { id: 'm_atem_5', kind: 'atem', name: 'Wechselatmung, sanft', text: 'Sitze aufrecht und bequem. Die linke Hand ruht auf dem Oberschenkel. Mit dem Daumen der rechten Hand verschließt du sanft das rechte Nasenloch.\n\nAtme links ein. Verschließe links mit dem Ringfinger, öffne rechts und atme rechts aus. Atme rechts ein, wechsle und atme links aus. Das ist eine Runde.\n\nÜbe einige Runden, ohne den Atem anzuhalten und ohne Anstrengung. Wenn du erkältet bist oder dir schwindelig wird, atme einfach natürlich durch beide Nasenlöcher.\n\nLass die Hand sinken und spüre die Wirkung nach.' },
  { id: 'm_atem_6', kind: 'atem', name: 'Quadratatmung (Boxatmung)', text: 'Setze dich aufrecht hin und lass die Schultern weich werden.\n\nAtme ein und zähle innerlich bis vier. Halte den Atem kurz, ebenfalls vier Zähler, ohne Druck. Atme aus und zähle bis vier. Bleibe leer für vier Zähler.\n\nStell dir vor, du zeichnest mit dem Atem ein Quadrat. Wenn das Anhalten unangenehm ist, verkürze es oder lass es weg.\n\nZum Schluss atme wieder frei und beobachte, wie klar und ruhig du dich fühlst.' },
  { id: 'm_atem_7', kind: 'atem', name: 'Summender Atem (Bhramari)', text: 'Setze dich bequem hin und schließe die Augen. Lass den Kiefer locker, die Lippen sind sanft geschlossen.\n\nAtme durch die Nase ein. Beim Ausatmen summst du leise, wie eine Biene. Spüre die Schwingung im Gesicht, im Kopf und im Brustkorb.\n\nWiederhole das einige Atemzüge lang. Das Summen darf weich und angenehm sein.\n\nBleibe danach still und spüre den Nachklang in dir.' },
  { id: 'm_mantra_3', kind: 'mantra', name: 'Om als Einstimmung', text: 'Komm in einen aufrechten, bequemen Sitz. Lege die Hände auf die Knie und schließe die Augen.\n\nAtme tief ein. Beim Ausatmen lass ein langes „Ooooommm“ erklingen, so lange es angenehm ist. Du musst keinen bestimmten Ton treffen, finde einfach deine Stimme.\n\nWir singen es gemeinsam einige Male. Nach dem letzten Klang bleibe still und spüre, wie die Schwingung in dir nachwirkt.' },
  { id: 'm_mantra_4', kind: 'mantra', name: 'Vorsprechen und Nachsprechen', text: 'Sitze aufrecht und mache es dir bequem. Ich spreche oder singe dir das Mantra Zeile für Zeile vor, und du wiederholst es.\n\nHab keine Scheu: Deine Stimme darf leise oder kräftig sein. Es geht um das gemeinsame Schwingen, nicht um Perfektion.\n\nAm Ende singen wir das Mantra einige Male zusammen. Lass es danach in die Stille ausklingen.' },
  { id: 'm_mantra_5', kind: 'mantra', name: 'Mantra mit Handhaltung', text: 'Komm in einen bequemen Sitz. Lege Daumen und Zeigefinger beider Hände leicht aneinander, die Handrücken ruhen auf den Knien.\n\nWiederhole das Mantra, zuerst leise, dann innerlich. Mit jeder Wiederholung kannst du Daumen und Zeigefinger kurz berühren, wie einen kleinen Anker.\n\nSpüre die Ruhe, die sich ausbreitet. Lass das Mantra am Ende verklingen und bleibe still.' },
  { id: 'm_mantra_6', kind: 'mantra', name: 'Mantra und Motto verbinden', text: 'Sitze aufrecht und atme ruhig. Erinnere dich an unser Motto „{motto}“ und an den Satz: {kernsatz}\n\nWir singen nun das Mantra und lassen es für dieses Motto stehen. Mit jeder Wiederholung darfst du dich ein Stück mehr damit verbinden.\n\nNach dem letzten Klang bleibe in der Stille und lass den Gedanken nachwirken.' },
  { id: 'm_mantra_7', kind: 'mantra', name: 'Stilles Lauschen nach dem Klang', text: 'Nachdem wir gesungen haben, bleibe aufrecht sitzen und lass die Hände ruhen.\n\nHöre dem Nachklang zu, bis er ganz verklungen ist. Lausche dann auf die Stille dahinter, auf den Raum, der entstanden ist.\n\nSpüre, wie sich dein Körper und dein Geist anfühlen. Es genügt, einfach da zu sein.' },
  { id: 'm_schluss_3', kind: 'schluss', name: 'Dankbarkeit und Namaste', text: 'Komm in einen bequemen Sitz und lege die Hände vor dem Herzen zusammen.\n\nDanke dir selbst, dass du dir diese Zeit genommen hast. Danke deinem Körper und deinem Atem, die dich durch die Stunde getragen haben.\n\nUnser Motto „{motto}“ darf dich noch begleiten: {kernsatz}\n\nNamaste. Das Licht in mir grüßt das Licht in dir.' },
  { id: 'm_schluss_4', kind: 'schluss', name: 'Mitnehmen in den Alltag', text: 'Bleibe noch einen Moment ruhig und spüre nach, was heute in dir lebendig geworden ist.\n\nÜberlege, was du aus dieser Stunde mitnehmen möchtest: ein Gefühl, einen Atemzug, einen Gedanken. Unser Motto „{motto}“ kann dir dabei helfen: {kernsatz}\n\nWenn der Alltag dich später wieder einholt, kehre zu diesem Gefühl zurück. Ein bewusster Atemzug genügt.' },
  { id: 'm_schluss_5', kind: 'schluss', name: 'Nachspüren in der Seitenlage', text: 'Rolle dich langsam auf eine Seite, die Knie dürfen angezogen sein, der Kopf ruht auf dem Arm oder einer Decke.\n\nSpüre die Wirkung der Übungen im ganzen Körper. Was ist weicher, wärmer, ruhiger geworden?\n\nBleibe, so lange du magst. Richte dich dann ohne Eile auf und komm in den Sitz.' },
  { id: 'm_schluss_6', kind: 'schluss', name: 'Sanftes Ausklingen im Sitzen', text: 'Komm in einen aufrechten Sitz. Die Hände ruhen auf den Knien oder im Schoß.\n\nSchließe die Augen und atme dreimal bewusst tief. Spüre deinen Sitz, deinen Rücken, deine Atembewegung.\n\nLass das Üben nun ausklingen. Öffne in deinem Tempo die Augen und nimm den Raum und die anderen Menschen wahr.' },
  { id: 'm_schluss_7', kind: 'schluss', name: 'Kurzer Gedanke zum Abschied', text: 'Die Stunde klingt aus. Schön, dass wir gemeinsam geübt haben.\n\nNimm einen Satz mit auf den Weg: {kernsatz}\n\nGehe gut mit dir um, bis wir uns wiedersehen.' },
  { id: 'm_shava_3', kind: 'shava', name: 'Shavasana mit Atemwelle', text: 'Lege dich bequem auf den Rücken, die Beine leicht geöffnet, die Arme neben dem Körper. Schließe die Augen.\n\nLass den Körper schwer werden und vom Boden tragen. Spüre den Atem, wie eine Welle, die kommt und geht. Mit jeder Ausatmung sinkst du ein Stück tiefer.\n\nDu musst nichts tun. Lass dich einfach vom Atem schaukeln.\n\nWiederhole innerlich: „{kernsatz}“\n\nKomm nach einer Weile langsam zurück: Atem vertiefen, Finger und Zehen bewegen, räkeln.' },
  { id: 'm_shava_4', kind: 'shava', name: 'Shavasana mit Schwere und Wärme', text: 'Komm in die Rückenlage und lass den Körper ganz schwer werden.\n\nSpüre die Schwere in den Beinen, im Becken, im Rücken, in den Armen und im Kopf. Alles darf in den Boden sinken.\n\nNun spüre eine angenehme Wärme: in den Händen, im Bauch, im Herzen. Sie breitet sich von innen aus.\n\nWiederhole innerlich: „{kernsatz}“\n\nBleibe in dieser warmen Ruhe, so lange du magst, und komm dann langsam zurück.' },
  { id: 'm_shava_5', kind: 'shava', name: 'Shavasana mit innerem Bild', text: 'Lege dich bequem hin und schließe die Augen. Lass den Atem ruhig fließen.\n\nStelle dir einen Ort vor, an dem du dich vollkommen sicher fühlst: ein sonniger Strand, eine weite Wiese, ein stiller Wald. Spüre die Wärme, die Luft, die Geräusche an diesem Ort.\n\nLass dich dort tragen und ruhen. Du musst nichts festhalten.\n\nLass das Bild langsam verblassen, spüre den Boden unter dir und komm in deinem Tempo zurück.' },
  { id: 'm_shava_6', kind: 'shava', name: 'Shavasana, sehr ruhig und still', text: 'Lege dich hin, so wie es für dich am angenehmsten ist. Eine Decke oder ein Kissen darf dich unterstützen.\n\nSchließe die Augen. Du hast nichts mehr zu tun. Lass los, was loszulassen geht, und beobachte nur.\n\nBleibe in dieser Stille.\n…\n\nBewege nun sanft Finger und Zehen, vertiefe den Atem und komm in deiner Zeit zurück.' },
  { id: 'm_shava_7', kind: 'shava', name: 'Shavasana mit Körperreise', text: 'Komm in die Rückenlage und werde still. Lenke deine Aufmerksamkeit durch den Körper und lass jeden Bereich weich werden.\n\nFüße und Beine. Becken und Bauch. Rücken und Brustkorb. Hände und Arme. Schultern und Nacken. Gesicht, Augen, Stirn.\n\nSpüre zum Schluss den ganzen Körper als Einheit, ruhig und schwer.\n\nWiederhole innerlich: „{kernsatz}“\n\nVertiefe dann den Atem, bewege Finger und Zehen und komm langsam zurück.' },
  { id: 'm_nidra_3', kind: 'nidra', name: 'Yoga Nidra, kompakt (10 Minuten)', text: 'Lege dich bequem auf den Rücken und richte dich so ein, dass du dich nicht mehr bewegen musst. Schließe die Augen. Höre meiner Stimme zu und bleibe wach.\n\nSpüre die Auflagefläche und lass dich tragen. Nimm drei tiefe Atemzüge und lass jedes Mal mehr los.\n\nSprich nun innerlich deinen Vorsatz: „{kernsatz}“. Wiederhole ihn dreimal.\n\nWandere mit der Aufmerksamkeit durch den Körper: rechte Seite, linke Seite, Rücken, Vorderseite, Kopf, dann der ganze Körper.\n\nBeobachte den Atem, ohne ihn zu verändern. Zähle ihn rückwärts von zehn bis eins.\n\nWiederhole den Vorsatz noch einmal dreimal: „{kernsatz}“.\n\nKomm langsam zurück: Atem vertiefen, Finger und Zehen bewegen, räkeln. Öffne die Augen, wenn du bereit bist.' },
  { id: 'm_nidra_4', kind: 'nidra', name: 'Yoga Nidra mit Naturbildern', text: 'Lege dich bequem hin und schließe die Augen. Du musst nichts mehr tun, nur zuhören.\n\nSpüre den Körper auf dem Boden und lass los. Sprich innerlich deinen Vorsatz: „{kernsatz}“.\n\nStelle dir einen Wald vor. Spüre die kühle, frische Luft, höre das leise Rauschen der Blätter. Du gehst langsam weiter und kommst zu einer Lichtung mit weichem Gras. Lege dich dort nieder.\n\nÜber dir ein weiter Himmel. Die Sonne wärmt dein Gesicht. Dein Körper wird schwer und weich.\n\nNimm diese Ruhe tief in dich auf.\n\nWiederhole deinen Vorsatz: „{kernsatz}“.\n\nKomm nun langsam zurück: Atem, Körper, Boden. Bewege Finger und Zehen und öffne die Augen, wenn du bereit bist.' },
  { id: 'm_nidra_5', kind: 'nidra', name: 'Yoga Nidra mit An- und Entspannung', text: 'Komm in die Rückenlage und schließe die Augen. Lass den Atem ruhig fließen.\n\nWir spannen nacheinander Körperbereiche an und lassen wieder los. Spanne die Füße an, halte kurz und lass los. Beine, Gesäß, Bauch, Hände, Arme, Schultern, Gesicht. Jedes Mal spürst du danach die Entspannung deutlicher.\n\nNun ist der ganze Körper weich. Spüre die Schwere und die Ruhe.\n\nSprich innerlich deinen Vorsatz: „{kernsatz}“. Wiederhole ihn dreimal.\n\nBleibe noch einen Moment still. Komm dann langsam zurück, bewege Finger und Zehen und öffne die Augen.' },
  { id: 'm_nidra_6', kind: 'nidra', name: 'Yoga Nidra am Abend (zum Einschlafen)', text: 'Lege dich bequem hin, am besten dort, wo du später schlafen möchtest. Schließe die Augen und lass den Tag hinter dir.\n\nSpüre die Schwere deines Körpers. Mit jeder Ausatmung sinkst du tiefer. Lass Beine, Rücken, Arme und Gesicht weich werden.\n\nSprich innerlich ein beruhigendes Wort oder deinen Vorsatz: „{kernsatz}“.\n\nZähle langsam die Atemzüge rückwärts. Wenn du dich verzählst, ist das gut, beginne einfach neu.\n\nDu darfst in diese Ruhe sinken, bis der Schlaf von selbst kommt.' },
  { id: 'm_nidra_7', kind: 'nidra', name: 'Yoga Nidra, belebend (Morgen oder Tag)', text: 'Lege dich auf den Rücken, schließe die Augen und werde still. Du bleibst wach und aufmerksam.\n\nSpüre den Körper und lass ihn ruhen. Nimm drei tiefe Atemzüge. Sprich innerlich deinen Vorsatz: „{kernsatz}“.\n\nLass die Aufmerksamkeit kurz durch den Körper wandern, vom Kopf bis zu den Füßen. Spüre Lebendigkeit und Kraft in jedem Bereich.\n\nStelle dir ein helles, warmes Licht vor, das dich mit Energie erfüllt. Atme es ein, mit jedem Atemzug mehr.\n\nWiederhole deinen Vorsatz: „{kernsatz}“.\n\nVertiefe nun den Atem, bewege Hände und Füße, strecke dich kräftig und öffne die Augen. Komm wach und klar zurück.' }
];
const txKindOf = (s, k) => (TX_KINDS[abOf(s, k)] ? abOf(s, k) : TX_KINDS[k] ? k : 'einl');
// Art der Vorlage im Auswahlfeld: manuell gewählt (ui.tplPick.kind) oder passend zum Textblock
const txPickKind = (s, k) => { const p = ui.tplPick; return (p && p.sid === s.id && p.k === k && TX_KINDS[p.kind]) ? p.kind : txKindOf(s, k); };
const txTplList = kind => TX_MUSTER.filter(t => t.kind === kind).concat((state.textTpl || []).filter(t => t.kind === kind));
const txTplFill = (t, s) => String(t.text || '').replace(/\{motto\}/g, (s && s.motto && s.motto.title) || '').replace(/\{kernsatz\}/g, (s && s.motto && (s.tx.kern || s.motto.kern)) || '').replace(/\{fokus\}/g, (s && s.motto && (s.tx.focus || s.motto.focus)) || '');
const txWords = t => (String(t).trim().match(/\S+/g) || []).length;

// Auswahl in der Einzelstundenplanung (unter dem Textfeld-Kopf)
function tplPickPanel(s, k) {
  const kind = txPickKind(s, k), list = txTplList(kind);
  return `<div class="tplpick"><div class="tph"><b>Vorlage einfügen</b><label class="tpk">Art: <select data-chg="tplKind" data-id="${s.id}" data-k="${k}">${Object.keys(TX_KINDS).map(x => `<option value="${x}"${x === kind ? ' selected' : ''}>${esc(TX_KINDS[x])}</option>`).join('')}</select></label><span class="muted">ersetzt den aktuellen Text · {motto} und {kernsatz} werden ausgefüllt</span><span class="grow"></span><button class="ghost sm" data-a="tplOpen" data-id="${s.id}" data-k="${k}">✕ schließen</button></div>${list.map(t => `<button class="tpo" data-a="tplUse" data-id="${s.id}" data-k="${k}" data-tid="${t.id}"><b>${esc(t.name)}</b> <span class="tag${t.id.startsWith('m_') ? '' : ' own'}">${t.id.startsWith('m_') ? 'Muster' : 'Eigene'}</span> <small class="muted">${txWords(txTplFill(t, s))} Wörter</small><span class="tpp">${esc(txTplFill(t, s).replace(/\s+/g, ' ').slice(0, 160))} …</span></button>`).join('') || '<p class="muted">Keine Vorlagen vorhanden.</p>'}<p class="muted">Eigene Vorlagen legst du auf der Seite „Textvorlagen“ an.</p></div>`;
}

// Seite „Textvorlagen“
function viewTexts() {
  ui.tplNew = ui.tplNew || { kind: 'einl', name: '', text: '' };
  const n = ui.tplNew;
  const card = t => {
    const own = !t.id.startsWith('m_');
    return `<div class="tcard${own ? ' own' : ''}"><div class="tch"><b>${esc(t.name)}</b> <span class="tag${own ? ' own' : ''}">${own ? 'Eigene' : 'Muster'}</span> <small class="muted">${txWords(t.text)} Wörter</small><span class="grow"></span>${own ? `<button class="ghost sm" data-a="tplDel" data-id="${t.id}">🗑</button>` : `<button class="ghost sm" data-a="tplCopy" data-id="${t.id}" title="Als eigene Vorlage kopieren, dann änderbar">⧉ Kopie bearbeiten</button>`}</div>
${own ? `<input type="text" value="${esc(t.name)}" data-chg="tplEdit" data-id="${t.id}" data-fld="name" class="tname"><textarea rows="${Math.min(14, Math.max(4, Math.ceil(t.text.length / 90)))}" data-chg="tplEdit" data-id="${t.id}" data-fld="text">${esc(t.text)}</textarea>` : `<div class="tpbody">${esc(t.text)}</div>`}</div>`;
  };
  const secs = Object.keys(TX_KINDS).map(k => `<section class="panel"><h3>${esc(TX_KINDS[k])}</h3><div class="tgrid">${txTplList(k).map(card).join('')}</div></section>`).join('');
  return `<div class="bar"><h1>Textvorlagen</h1></div>
<p class="muted">Mustertexte für jeden Textblock der Stunde. In der Einzelstundenplanung fügst du sie über „📋 Vorlage“ in den jeweiligen Text ein. Platzhalter: <code>{motto}</code>, <code>{kernsatz}</code>, <code>{fokus}</code> werden mit den Angaben der Stunde gefüllt. Mustertexte sind fest; mit „Kopie bearbeiten“ machst du eine eigene Version daraus.</p>
<section class="panel"><h3>＋ Neue Vorlage</h3><div class="grid">
${fld('Für Block', sel('u:tplNew.kind', Object.keys(TX_KINDS).map(k => [k, TX_KINDS[k]]), n.kind))}
${fld('Name der Vorlage', inp('u:tplNew.name', 'text', n.name, 'placeholder="z. B. Herbst-Einleitung"'))}
${fld('Text (Absätze mit Leerzeile, Platzhalter möglich)', `<textarea data-f="u:tplNew.text" rows="8" placeholder="Text der Vorlage …">${esc(n.text)}</textarea>`, 'wide')}
</div><div class="bar"><button class="primary" data-a="tplAdd">Vorlage speichern</button></div></section>
${secs}`;
}

const TXVORL_ACTIONS = {
  tplAdd() {
    const n = ui.tplNew; if (!n.name.trim() || !n.text.trim()) { toast('Bitte Name und Text eingeben.'); return; }
    (state.textTpl = state.textTpl || []).push({ id: 'u_' + uid(), kind: n.kind, name: n.name.trim(), text: n.text });
    ui.tplNew = { kind: n.kind, name: '', text: '' }; save(); render(); toast('Vorlage gespeichert.');
  },
  tplDel(d, el) { const t = (state.textTpl || []).find(x => x.id === d.id); if (t && confirmTwice(el, 'tpl' + d.id, `Vorlage „${t.name}“ löschen?`)) { state.textTpl = state.textTpl.filter(x => x !== t); save(); render(); } },
  tplCopy(d) { const t = TX_MUSTER.find(x => x.id === d.id); if (!t) return; (state.textTpl = state.textTpl || []).push({ id: 'u_' + uid(), kind: t.kind, name: t.name + ' (eigene)', text: t.text }); save(); render(); toast('Eigene Kopie angelegt – direkt darunter änderbar.'); },
  tplOpen(d) { ui.tplPick = (ui.tplPick && ui.tplPick.sid === d.id && ui.tplPick.k === d.k) ? null : { sid: d.id, k: d.k }; render(); },
  tplUse(d) {
    const { c, s } = sessionOf(d.id), t = txTplList(txPickKind(s, d.k)).find(x => x.id === d.tid); if (!t) return;
    s.tx[d.k] = txTplFill(t, s); s.txEdited[d.k] = true; ui.tplPick = null; save(); render(); toast(`Vorlage „${t.name}“ eingefügt.`);
  },
  txClear(d) { const { s } = sessionOf(d.id); s.tx[d.k] = ''; s.txEdited[d.k] = true; save(); render(); toast('Text geleert.'); },
  tplSaveFrom(d) {
    const { s } = sessionOf(d.id), txt = (s.tx[d.k] || '').trim(); if (!txt) { toast('Der Text ist leer.'); return; }
    const kind = txKindOf(s, d.k);
    (state.textTpl = state.textTpl || []).push({ id: 'u_' + uid(), kind, name: `${s.motto.title || 'Eigener Text'} (${fmtDate(todayIso())})`, text: txt }); save(); toast('Als Vorlage gespeichert (Seite „Textvorlagen“).');
  }
};
const TXVORL_CH = {
  tplKind(el) { if (ui.tplPick && TX_KINDS[el.value]) { ui.tplPick.kind = el.value; render(); } },
  tplEdit(el) { const t = (state.textTpl || []).find(x => x.id === el.dataset.id); if (t) { t[el.dataset.fld] = el.value; save(); } }
};
